### ISSUE TITLE
Check EntityRenderer

### ISSUE THREAD

**Issue by modmuss50** [asiekierka/MinecraftPOMF#100]
net/minecraft/client/render/entity/EntityRenderer might not be the correct name for this.

**Comment by copygirl** [comment]
Can you or someone else elaborate?

**Comment by exaskye** [comment]
In older mapping projects, EntityRenderer was the name used for a rendering class that did a _lot_ more than just rendering entities. We should make sure that our EntityRenderer mapping is actually for a class that is dedicated to rendering entities.

**Comment by asiekierka** [comment]
Our EntityRenderer is the name of the base class which other EntityRenderers inherit from and is dedicated to that purpose, much like BlockEntityRenderer. As such, solved!
