### ISSUE TITLE
Drop 'get' prefix for methods

### ISSUE THREAD

**Issue by Sollace** [asiekierka/MinecraftPOMF#1009]
Looking for feedback on this, as the standard libs seem to be no longer using get for their newer methods.

**Comment by liach** [comment]
So the current votes are 2 :+1: and 7 :-1:. Will take this as the result if there is no additional votes or comments in another 24 hours. Discord peeps mind take a look.

**Comment by i509VCB** [comment]
I support the change, but it needs some conventions written up as sometimes a `get` prefix is needed.

Ideally mirroring how the JDK approaches this.

**Comment by liach** [comment]
Does jdk have `get` prefix when there is a setter? We might need to split these into when there is a setter vs when there is not. 

For example, record getter methods don't have `get` prefixes, but they don't have setters and don't have potential name confusion.

**Comment by liach** [comment]
In fact, some new jdk getters have `get` prefixes while others don't. A striking example is in [`java.lang.invoke.CallSite`](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/invoke/CallSite.html), introduced relatively recently in jdk 7, frequently used by invokedynamic bytecode instruction's bootstrap method attribute, where there is a `MethodType type()` getter and a `MethodHandle getTarget()` getter (the type one is immutable while the target one is mutable; there is a `setTarget(MethodHandle)` as well). Also some other newer apis use `get` prefix as well, such as [`Class.getModule`](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Class.html#getModule()) from java 9.

**Comment by dexman545** [comment]
I believe the JDK's standard is immutable is no prefix, while mutable is prefixed - this can somewhat be seen with the new records not having getters or setters as their data is immutable.

**Comment by Juuxel** [comment]
Also closing this based on the decision of #2408 to keep `get` for non-record classes.
