### ISSUE TITLE
"does this have that tag" methods have very different names

### ISSUE THREAD

**Issue by quat1024** [asiekierka/MinecraftPOMF#1011]
As of Yarn 1.15+build.1, `Item#isIn`, `Fluid#matches`, `EntityType#isTaggedWith`, and `Block#matches` all have pretty much the same implementation - `return tag.contains(this)` - but have very different names. These all basically do the same thing so they should be unified to have the same name.

**Comment by liach** [comment]
I support `isIn`.

**Comment by Juuxel** [comment]
See also this: https://github.com/FabricMC/yarn/pull/712#discussion_r287569335

**Comment by YanisBft** [comment]
Additionnally, the method for entities should **not** be called `isTaggedWith`, as it seems it returns what the `Tags` nbt contains, instead of datapack tags

**Comment by Prospector** [comment]
I like `matches` personally

**Comment by liach** [comment]
it would have been `tag.matches(item)` than `item.matches(tag)`

**Comment by Prospector** [comment]
item.within(tag)
item.has(tag)
item.taggedWith(tag)

**Comment by liach** [comment]
`within` can be just `is in`, being in a tag isn't an intrinsic property of an item so `has` is inaccurate, and `taggedWith` is too long and isn't intrinsic either

**Comment by YanisBft** [comment]
I think `isIn` is the more accurate one
