### ISSUE TITLE
Orphaned datafix (RemovePoiValidTagFix)

### ISSUE THREAD

**Issue by quat1024** [asiekierka/MinecraftPOMF#1014]
`RemovePoiValidTagFix` is in `net.minecraft.datafixer`, but all other Minecraft datafixer things are in `net.minecraft.datafixers` with an `s` at the end.

**Comment by Pyrofab** [comment]
Shouldn't it be the opposite ? Package names are usually singular.

**Comment by liach** [comment]
We indeed should move all of them to `datafixer` package instead. Yarn uses singular names unlike mojang which uses plural names (seen from their foss libraries)
