### ISSUE TITLE
Use the registered names for Registry.MOB_EFFECT and Registry.MENU

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#1055]
The registries are currently called `STATUS_EFFECT` and `CONTAINER`. I think we should use the registered names for every registered object, which includes `Registry.MENU` and `Registry.STATUS_EFFECT` as well.

(This change was originally part of #1048, but I took it out because it's a major change compared to the other changed names.)

**Comment by liach** [comment]
I disagree. Let's look at the registry key for world and dimension(options). Both have the same instance, yet they are kept in different fields and cannot be assigned to each other due to different generic types. Mojang definitely ain't using the registered names for one of these two fields.

**Comment by apple502j** [comment]
See #3008

**Comment by Juuxel** [comment]
That's the opposite issue (keys matching the real IDs = keys not matching Yarn `Registry` object names), but yeah I agree that this is not planned.
