### ISSUE TITLE
VoronoiBiomeAccessType and .calcChance/distribute naming

### ISSUE THREAD

**Issue by Player3324** [asiekierka/MinecraftPOMF#1062]
The class `net.minecraft.world.biome.source.VoronoiBiomeAccessType` has a two improvable method names besides its own name:

`calcChance(long, int, int, int, double, double, double)` doesn't compute a chance, but a random position around a given point. It also carries the biome rng initialization+advancing steps (manually inlined).

`net.minecraft.world.biome.source.VoronoiBiomeAccessType.distribute(long)` doesn't distribute, but does the standard biome rng nextInt(1024) followed by some scaling to obtain an uniformly distributed random value in [0.45..0.45).

The `storage` parameter naming across the entire subsystem is not very accurate, it is just the parent data source with a little FIFO cache.

VoronoiBiomeAccessType effectively distorts the 3D grid holding biome IDs randomly (locked to the seed), zooms in 4x (for each dim), selects the closest grid point and finally samples it without interpolation. This grid distortion is up to +- 0.45 in every dimension.

The closest analogy to Voronoi diagrams is that biome boundaries more or less follow the same "closest point" rules on a micro level - ignoring quantization. This name however doesn't describe how the grid got actively distorted or zoomed in. A more appropriate name should mention grid distortion, nearest point sampling and the 4x zooming.

**Comment by haykam821** [comment]
This issue is no longer applicable in Minecraft 1.18, as the entire class has been removed.
