### ISSUE TITLE
getMiningSpeed -> getMaterialMultiplier

### ISSUE THREAD

**Issue by dexman545** [asiekierka/MinecraftPOMF#1069]
The function `getMiningSpeed` from `ItemStack`, `Item`, and its subclasses doesn't seem to actually determine mining speed, but the tool's base multiplier (which does influence mining speed) based on the tool's material. 
The returned values match what is expected for the material multipliers as shown in the wiki [(the table)](https://minecraft.gamepedia.com/Breaking#Speed).
This function is also unaware of things that do affect a tools mining speed, such as the efficiency enchantment, and the entity's status effects.

My suggested name probably isn't the best, but it should be changed to something more descriptive of what the function actually does.

**Comment by dexman545** [comment]
Based on discussion in Discord, other names were suggested:
getBaseMiningSpeed() - upcraft
getMiningSpeedMultiplier - prospector
getHarvestingEffectiveness - cosmicdan

**Comment by Prospector** [comment]
imo `getHarvestingEffectiveness` isn't right, because the speed is usually the same whether you can actually harvest it or not
