### ISSUE TITLE
PlayerEntity.addChatMessage -> addStatusMessage

### ISSUE THREAD

**Issue by YanisBft** [asiekierka/MinecraftPOMF#1072]
This method actually displays a message over the action bar, not in the chat.
In vanilla, it's used for sleep failure messages and locked containers.

**Comment by Pyrofab** [comment]
Doesn't it depend on the boolean parameter ? `true` prints to the action bar, `false` to the chat if I remember correctly. Maybe `addStatusMessage` would be adequate ?

**Comment by YanisBft** [comment]
Hum you're right actually. `addStatusMessage` is quite good yeah
Additionnally, `ChatMessageS2CPacket` class has to be renamed to match the method

**Comment by liach** [comment]
or a system message?

**Comment by YanisBft** [comment]
hum, system message does sound a bit like a log message, don't you think?

**Comment by liach** [comment]
i recall one of the enum entries in chat packet sub enum says something like that
