### ISSUE TITLE
Incorrect enchantment method names

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#1084]
- `EnchantmentHelper.contains(Collection<Enchantment>, Enchantment)` -> `hasNoConflicts`
  - The method returns true if the `Collection<Enchantment>` does not have conflicting enchantments.
- `Enchantment.isDifferent(Enchantment)` -> "can be on the same item"
  - basically `this.differs(other) && other.differs(this)`. `differs` itself is named wrong, so this method checks that both enchantments think the other one is a valid partner.
  - Example: `SilkTouchEnchantment.differs` returns false if the enchantment is `FORTUNE`, so they conflict even though Fortune uses the default impl.
- `Enchantment.differs(Enchantment)` -> also "can be on the same item"
  - Checks if this enchantment is mutually exclusive with the passed enchantment.

**Comment by bluebear94** [comment]
`isDifferent` would better be named as `isCompatibleWith`, though I'm not sure what to rename `differs` to.

**Comment by liach** [comment]
Imo `hasNoConflicts` is more like `canCombine`
