### ISSUE TITLE
How should `BlockView` arguments be named?

### ISSUE THREAD

**Issue by LambdAurora** [asiekierka/MinecraftPOMF#1098]
`BlockView` arguments should be named `view` or `world`?

**Comment by Prospector** [comment]
I personally like world for all the world-like parameters

**Comment by liach** [comment]
I prefer `view`. Guess we can vote on this comment (:+1: and :-1:)

**Comment by Juuxel** [comment]
Hm, aren't some of the `*View` interfaces only implemented on `World` and some implemented on `Chunk` as well?

**Comment by LambdAurora** [comment]
`BlockView` is implemented in something for rendering, worlds and chunks.
But `WorldView` is only implemented by world.

**Comment by liach** [comment]
Result is pretty clear. people support `world` overwhelmingly, and let's just use `world`

**Comment by liach** [comment]
Closing as we've decided and have applied to #1095.
