### ISSUE TITLE
isEffectiveOn -> ?

### ISSUE THREAD

**Issue by dexman545** [asiekierka/MinecraftPOMF#1140]
`isEffectiveOn` in `Item`, `ShearsItem`, `MiningToolItem`, and its subclasses is not clearly named.
The current name implies that if the current item can break the given blockstate, it will return true. This is not the case - most notably for axes on wood, but other tools also face this issue - shears, shovels, hoes.

Naming this as "effective" in the sense that using the item would produce a drop not normally available from the block is also incorrect, see shears and shovels.

Shear's `isEffectiveOn` _does_ slightly account for special behavior with tripwires, but it also returns true for redstone wire (of which there is no special behavior). 

Strangely enough, it does seem to be properly implemented for pickaxes.

This method might simply be something left over, or not fully implemented - but whatever it is, it isn't a check for if an item can mine a block effectively or not outside of pickaxes.

Some name proposals:

- hasProperLevel
- correctMiningLevelFor
- pickaxeCanMine
- isProperToolMaterial
- canMineIfHandFails
- miningOptsForTool
- hasCorrectLevelFor

(Mining)Level is used as it implies that the check is only for blocks/tools that have an associated mining level of which they must be broken by in order to obtain drops, implicitly invalidating it from consideration in regards to non-tool items, shears, shovels, and the like of which normal gameplay does not place tool material requirements.

**Comment by dexman545** [comment]
The method ultimately gets called through `ItemStack` by `PlayerInventory`'s `isUsingEffectiveTool`, which then maps to `PlayerEntity`'s `isUsingEffectiveTool`, which is then used by Block and BlockState for `calcBlockBreakingDelta`, `DoorBlock` for dropping items in `onBreak`, and something in `ServerPlayerInteractionManager`'s `tryBreakBlock`
The naming in `PlayerEntity` makes sense as it also checks if the block can be broken by hand (and seems to indicate the naming was about the blocks dropping items or not), so those names (from `PlayerEntity` onwards seem fine).

For clarity on what "effective" implies in these cases:
- using this tool will drop an item
     - this fails for axes on logs, shovels on dirt, gravel, or sand, and shears on vines and other foliage (it returns false in those cases). Works for pickaxes, and sword's special behavior with cobwebs
- using this tool will increase the speed of breaking
     - returns false for shears on wool, axes on logs, etc
- using this tool will do some special logic
     - this works _somewhat_ in that shears return true for tripwire, and pickaxes perform the check for mining level, but fails as it returns true for shears on redstone wire of which there is no special behavior, true for shovels on snow blocks, Note that it does not return true if there is special logic, just that there being special logic for a block implies that this method has a chance of returning true.

It should aslo be noted that not every tool implements this - hoes and axes do not have it.

**Comment by liach** [comment]
The fact that wood doesn't return true is because the method only needs to return true if the material of the block requires tool.

This behavior can be called "harvest" as in its run it drops the loot table, or "mine" because it increases `mined` stats. Maybe we should use `isMiningTool`/`isHarvestTool` and note that if the material of the block requires breaking tool and the tool is improper, the breaking of the block is not counted towards mining stats and will not drop the loot table

**Comment by dexman545** [comment]
Both of those are better than using some nonverbose variant of "effective." Some JD to indicate expected behavior would also be good.

**Comment by shedaniel** [comment]
~canSpeedUpBreaking~ /s

**Comment by liach** [comment]
doesn't relate to breaking speed as i see

**Comment by Prospector** [comment]
`hasMiningLevelFor`

Example: `stack.hasMiningLevelFor(Blocks.IRON_ORE.getDefaultState());`
