### ISSUE TITLE
getEffectiveHeight Removed?

### ISSUE THREAD

**Issue by T0paz** [asiekierka/MinecraftPOMF#1146]
I'm trying to convert the mod "NetherHigher" to 20w09a, and noticed that the method it relies upon to raise the Nether height, getEffectiveHeight (net.minecraft.world.World), is no longer mapped. It does this by overriding the constant "128" with "256" for when this method is called. Why was getEffectiveHeight unmapped? Is there another method that can be used to the same effect?

**Comment by modmuss50** [comment]
It seems like it was removed, what I usually do in these cases is see where it was used in vanilla 20w08a and and then look at those same places in 20w09a.

**Comment by Prospector** [comment]
Nothing really used the method anyway tbh. Everywhere things are just hard-coded to 256 mostly

**Comment by liach** [comment]
It may have been moved to the dimension or dimension type classes, I assume

**Comment by YanisBft** [comment]
The method is now `getDimensionHeight()` in `IWorld` class. It returns 128 if the dimension is the Nether, 256 otherwise.
