### ISSUE TITLE
Match Material Names to Those of the MC Wiki; Name Improvements

### ISSUE THREAD

**Issue by dexman545** [asiekierka/MinecraftPOMF#1185]
[As discussed in the Discord](https://discordapp.com/channels/507304429255393322/521545796882006027/688152058515161225), using names from the wiki would allow for easier referencing and other such utility.  Certain Yarn names, and those on the wiki, could do with some updating as well. Below is some naming conventions, and a table for the names.

Proposed Naming Conventions:
  1. When possible, match the wiki name for the material, otherwise change wiki name

		Creating a fabric/yarn wiki page that lists the relation between block and material would be useful if the above is not done
  2. Materials are descriptors, and as such, they should use adjective form of their name

		ie WOOD -> WOODEN
  3. When multiple materials should share a name, they are differentiated by the unique property that they differ by unless clearer with another name

		ie PLANT <=> REPLACEABLE_PLANT
  4. Unless the material only contains one block that can be described by its name, material names are not to be named using a block that it contains
	
2 is iffy, as it would likely add extra characters to each name without much benefit for several instances; as such, it is left off from the current suggestions (names should all be consistent though).
Some effort was also made to keeping old names.

| Current Yarn       | Wiki                    | Suggestion                                         | Reason                                                                                                                                                        |
|--------------------|-------------------------|----------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Underwater\_Plant  | Water Plant             | Underwater Plant, Water Plant                         | Match EntityGroup "Aquatic", or Match wiki                                                                                                                    |
| Earth              | Dirt                    | Topsoil, Earth                                     | Current yarn name is fine, but doesn't include grass or mycelium which is normally considered to be "earth"                                                   |
| Snow\_Block        | Snow                    | Snow, Snow Block                                   | Match Naming conventions                                                                                                                                      |
| Seagrass           | Replaceable Water Plant | Replaceable Underwater Plant, Replaceable Water Plant | Breaks convention set by replaceable plant, match wiki                                                                                                        |
| Snow               | Top Snow                | Replaceable Snow, Snow Layer                       | Match naming conventions                                                                                                                                      |
| Anvil              | Heavy Metal             | Repair Station, Heavy Metal                        | Has grindstone                                                                                                                                                |
| Pumpkin            | Vegetable               | Gourd                                              | Has melons, this name is more general                                                                                                                         |
| Organic            | Grass                   | Fodder, Forage, Silage                             | Includes target block\.   This name is a bit more specific than "organic," which would include a whole host of other blocks already in use by other materials |
| Packed\_Ice        | Solid Ice               | Dence Ice, Unmeltable Ice, Solid   Ice             | Name conflict with   packed ice block; this ice does not melt                                                                                                 |
| Part               | Decoration              | Decoration                                         | These blocks are sort of miscellaneous \(torches, flower pots, tripwire, scaffolding, repeaters\)\.   Could be improved                                       |
| Sand               | Sand                    | Aggregate                                          | Has gravel, soul sand,   concrete powder                                                                                                                      |
| Clay               | Clay                    | ?                                                  | Includes honey block, infested blocks, slime blocks, honeycomb                                                                                                |
| Glass              | Glass                   | ?                                                  | Includes sea lanterns, glowstone, beacons, conduits\. May be better suited for an adjective for glass than a noun                                             |
| Metal              | Metal                   | ?                                                  | Not entirely metals, includes the storage blocks \(redstone, emerald, etc\)                                                                                   |
| Wool               | Wool                    | ?                                                  | Includes beds; could be improved                                                                                                                              |
| Carpet             | Cloth Decoration        | UPDATE WIKI                                        |                                                                                                                                                               |
| Cobweb             | Web                     | UPDATE WIKI                                        |                                                                                                                                                               |
| Nether\_Wood       | N/A                     | UPDATE WIKI                                        | Does not include logs \(stems\), or planks; could be improved                                                                                                 |
| Redstone\_Lamp     | Buildable Glass         | UPDATE WIKI                                        |                                                                                                                                                               |
| Shulker\_Box       | Shulker Shell           | UPDATE WIKI                                        |                                                                                                                                                               |
| Structure\_Void    | Structural Air          | UPDATE WIKI                                        |                                                                                                                                                               |
| Unused\_Plant      | Coral\(?\)              | UPDATE WIKI                                        |                                                                                                                                                               |
| Air                | Air                     | MATCHES                                            |                                                                                                                                                               |
| Bamboo             | Bamboo                  | MATCHES                                            |                                                                                                                                                               |
| Bamboo\_Sapling    | Bamboo sapling          | MATCHES                                            | Name has been updated in lang file to "Bamboo Shoot", material name could be updated                                                                          |
| Barrier            | Barrier                 | MATCHES                                            |                                                                                                                                                               |
| Bubble\_Column     | Bubble Column           | MATCHES                                            |                                                                                                                                                               |
| Cactus             | Cactus                  | MATCHES                                            |                                                                                                                                                               |
| Cake               | Cake                    | MATCHES                                            |                                                                                                                                                               |
| Egg                | Egg                     | MATCHES                                            |                                                                                                                                                               |
| Fire               | Fire                    | MATCHES                                            |                                                                                                                                                               |
| Ice                | Ice                     | MATCHES                                            | Possible name conflict, has frosted ice; may be improved                                                                                                      |
| Lava               | Lava                    | MATCHES                                            |                                                                                                                                                               |
| Leaves             | Leaves                  | MATCHES                                            |                                                                                                                                                               |
| Piston             | Piston                  | MATCHES                                            |                                                                                                                                                               |
| Plant              | Plant                   | MATCHES                                            |                                                                                                                                                               |
| Portal             | Portal                  | MATCHES                                            |                                                                                                                                                               |
| Replaceable\_Plant | Replaceable Plant       | MATCHES                                            |                                                                                                                                                               |
| Sponge             | Sponge                  | MATCHES                                            |                                                                                                                                                               |
| Stone              | Stone                   | MATCHES                                            |                                                                                                                                                               |
| Tnt                | TNT                     | MATCHES                                            |                                                                                                                                                               |
| Water              | Water                   | MATCHES                                            |                                                                                                                                                               |
| Wood               | Wood                    | MATCHES                                            |                                                                                                                                                               |

"UPDATE WIKI" indicates the Yarn name being better/present when comparing to the wiki
"MATCHES" indicates names that match between yarn and the wiki
"?" indicates a lack of a better name. Default to current Yarn name

**Comment by liach** [comment]
If there is strings in mojang code, i'd stick to the strings first, then wiki, or if wiki is inaccurate we can argue here

**Comment by dexman545** [comment]
I have found no such strings in Mojang's code, leaving only the wiki. 
The first several names I list are Yarn/wiki names that are unsuitable for what they represent. Aside from looking at making all materials adjectives, I have not considered the names that match between yarn and the wiki aside from a cursory glance. I think doing a first pass to update the old names and getting Yarn to use them, followed by reviewing names that seem to fit on a cursory glance is the best course of action for something like this. 

The cursory glanced names could lead to issues in the future, for instance, stone technically breaks convention 4 (breaking this convention is also likely how the anvil material got outdated) but based on the definition of stone, and the general understanding of it in the context of MC the name is fine, but could always be debated. Getting the outdated names to work first should be the priority, old names that still work should be done later.

Any feedback for naming is appreciated (especially for clay).

(For clarity, the names that have suggestions or are marked with "?" are inaccurate in yarn (and maybe the wiki). "update wiki" marked ones simply have inaccurate wiki names).

**Comment by Runemoro** [comment]
> Aquatic Plant

Are lily pads this material? If not, it should stay "underwater plant".

**Comment by dexman545** [comment]
> > Aquatic Plant
> 
> Are lily pads this material? If not, it should stay "underwater plant".

True. Fixed

**Comment by YanisBft** [comment]
Closed by #1190 
Won't be able to match wiki names as they use the ones from mojmaps
