### ISSUE TITLE
"tick" or "update" and when to use them?

### ISSUE THREAD

**Issue by copygirl** [asiekierka/MinecraftPOMF#121]

**Comment by Darkhax** [comment]
I feel that tick describes a measurement rather than an action. A tick would be a bi-product of an update.

**Comment by copygirl** [comment]
@darkhax Can you explain what you mean by byproduct? I understand the time measurement part of it. A second is usually 20 ticks and 10 redstone ticks.

Should we ever use it as a verb ("Tick a redstone repeater.")?

**Comment by ryantheleach** [comment]
I dislike update, update is too generic and could be seen to mean a number of different things.

Ticking in games is pretty well known.

Although I think we should make a clear distinction between full ticks, and partial rendering lerps

**Comment by copygirl** [comment]
I'm fine with either as long as we decide on the vocabulary we want to use and are consistent in using it.

**Comment by mezz** [comment]
To me, update implies there is old state that is outdated and must be updated to become current.
A tick is more specific than an update. A tick is always called at regular intervals, and checks to see if the thing needs an update or not. If it does, then it is updated.

**Comment by MrIbby** [comment]
`onTick`?

**Comment by maxpowa** [comment]
I'm with @mezz / @ryantheleach on this, `update` is for explicit state updates and `tick` is for things on the game loop.

**Comment by kashike** [comment]
For reference: https://github.com/ModCoderPack/MCPBot-Issues/issues/703

**Comment by asiekierka** [comment]
Between that and what mezz said (and the support for that), I think mezz's is a fair approach to take.

**Comment by Prospector** [comment]
Agree on tick

**Comment by Player3324** [comment]
There are 2 distinct detail interpretations

a) ticks refer to the game loop, they happen at 20 Hz

- tick is for invocations that happen exactly once every tick+object unless there's an obvious hindrance like being unloaded or having opted out globally
- update is anything else - it may advance the internal state but doesn't have to

With this you could rely on tick being a mirror of the client/server tick, blocks "update" randomly or through scheduling.

b) ticks are arbitrary quantity time increments / polling+update triggers

- ticks are for any repeating time delayed invocation
- updates are generally only for events that have a specific cause / explicit request

With this there are random "ticks", but scheduled "updates" are quite muddy. They sometimes meet the tick definition by consistently rescheduling.

**Comment by asiekierka** [comment]
I'd much rather go for (a). A "tick" is very clearly defined on the server side, a bit less so on the client side, but in general I prefer that to (b).

**Comment by jamierocks** [comment]
:+1: for tick

**Comment by ChloeDawn** [comment]
tick sounds good to me

**Comment by codewarrior0** [comment]
"update" is too overloaded. I've seen it as referring to ticking something on server side, or to syncing the server-side data to the client, or to redrawing something on the client (either in response to a server sync or a local simulation effect), or to fetching new versions of files from a file server. I'd like never to see it again.
