### ISSUE TITLE
QuickCraft -> ItemSpread

### ISSUE THREAD

**Issue by immibis** [asiekierka/MinecraftPOMF#1240]
This name confused me because the feature doesn't have anything to do with crafting (except that you can use it in crafting tables).

Container:
* quickCraftStage -> itemSpreadStage
* quickCraftButton -> itemSpreadButton
* quickCraftSlots -> itemSpreadSlots
* endQuickCraft -> endItemSpread
* unpackQuickCraftStage -> unpackItemSpreadStage
* shouldQuickCraftContinue -> shouldItemSpreadContinue
* packClickData: parameter quickCraftStage -> itemSpreadStage

SlotActionType:
* QUICK_CRAFT -> ITEM_SPREAD

Instead of just raising an issue, I should not be lazy and make a PR. Remind me after the modfest.

**Comment by liach** [comment]
Uhh, the enum name is from Mojang's strings (you know how enum constructors compile to have extra ordinal and name parameters), and `QUICK_CRAFT` is the mojang name. Good proposal though.

**Comment by Earthcomputer** [comment]
By the way, I recently added Javadocs and already renamed some of the methods you mention to clearer names. Y'all should check out the situation on the latest snapshot, and the additions by https://github.com/FabricMC/yarn/pull/1198 before discussing further.

**Comment by immibis** [comment]
ContainerScreen also uses a different name, "cursor drag".
