### ISSUE TITLE
Game in dev fails to launch due to recurision with entity attribute method names

### ISSUE THREAD

**Issue by i509VCB** [asiekierka/MinecraftPOMF#1262]
Crash Log:
https://gist.github.com/i509VCB/fa02c52d84c4e45b494a53a26bb4274b

This is related to the new entity attribute changes and mappings from https://github.com/FabricMC/yarn/commit/cabb00e658919f284f0df71ebd4b0e03cb4eab78

**Comment by liach** [comment]
The method is clearly calling the superclass' static method. This is a decompiler issue as it maps the super class' static method to this class' static method (fernflower has a bug that it drops class name qualification for static field access, like)
```java
public class Singleton {
private static Singleton instance;
public static Singleton setInstance(Singleton instance) {
Singleton.instance = instance;
}
}
```
while ff decompiles to `instance = instance`, which is wrong

Or this could be a bug with tiny remapper.

**Comment by modmuss50** [comment]
How can it be a decompiler issue, we dont run the decompiled source

**Comment by i509VCB** [comment]
If you go back to build 4 before some of the changes, the issue does not occur.

**Comment by liach** [comment]
Hmm, this thing is weird... looking from the decompiled source, most other classes are calling the `createAttributes` method like
e.g. in class_1550 method_26909, it calls
`class_1577.method_26915()` (the call to super createAttr method is qualified)
This is the case for most classes, but for abstract donkey:
`class_1492` `method_26898`:
`class_1492.method_26899()`
but static method `26899` is not declared in class_1492 but in class_1496, its superclass.
So guess mojang just didn't qualify the method call when calling the static method (which had a different name at compilation)

After all static method name detection is tricky; like enigma currently just disables all static method names from being the same, which is wrong, but some static method indeed cannot have name conflicts if they are inherited. Maybe need an instruction scanner to scan static field/method usages and figure out which static fields/methods are inherited, and then enigma decide whether allow renaming based on that.

**Comment by liach** [comment]
Or another worse alternative is that we remap the jar so that all static method/field call's owner class be replaced by exact class and prevent any inference from happening, which... is invasive though easier to do than this funky collision detection.
