### ISSUE TITLE
EntityAttribute -> Attribute

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#1264]
In 20w14a, Mojang refactored living entity attributes. Now they get a registry which is just called `minecraft:attribute`. We may consider renaming `EntityAttribute` to `Attribute`.

Compared to painting motive, attribute shouldn't be too confusing, and we already use "attribute modifiers" than "entity attribute modifiers".

**Comment by Player3324** [comment]
That would be a very generic name for a special-purpose thing that doesn't see much mod exposure. It also shadows several equally named classes on the class path, harming auto import handling.

I wouldn't have used "attribute" at all, it is not a very meaningful description of its purpose and doesn't mesh well with the related classes. It is some weird facility for semi-dynamic properties that appear they'd have been better off being fields, while holding only double values and almost exclusively used for potions and related hacks. The way EntityAttribute, AbstractEntityAttribute, ClampedEntityAttribute, EntityAttributeInstance, EntityAttributeInstanceImpl, EntityAttributeModifier, EntityAttributeContainer and the parts in LivingEntity were designed is so ridiculously convoluted with plenty of single use abstractions and a whopping 13 uses in 1.15..

**Comment by liach** [comment]
Closing, as this rename is unpopular.
