### ISSUE TITLE
Publishing javadoc jar/javadoc for deobfuscated Minecraft

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#1266]
Now I have a plan for generating javadoc for each yarn build, based on that javadoc generation needs sources.

1. Generate dummy sources using something like https://github.com/square/javapoet or https://github.com/inria/spoon (generate all methods fields and classes but skip )
1. Run javadoc task on the generated dummy source
1. Build the jar/publish like done in the api and profit
1. Maybe add guides in example mod for add jd external links to generated mc javadocs

This change would prove the value of yarn and quell people's argument that fabric "lacks proper documentation"

**Comment by modmuss50** [comment]
Yes, I think this is a great idea.

I assume there is no way to pass the raw data into the javadoc generator.

Does it need to use the javadoc tool? or could an existing (or even a new) static site genertor be used/created for this?

One idea I had would be have a server side application genreate the pages on demand, this would allow the site to work with all the previously existing mappings, and provide more control over the entire site.

**Comment by liach** [comment]
https://github.com/modmuss50/MappingPoet for note
