### ISSUE TITLE
Hints at True Mojang names.

### ISSUE THREAD

**Issue by ryantheleach** [asiekierka/MinecraftPOMF#128]
In AIGoalArrowAttack there is an exception that reveals some of the potential names for the real names of the class, Which brings the question, 

Where possible, should we be attempting to use the real names that Mojang use? Avoiding their use? Or coming up with the best names that we can given the evidence?

e.g.

```
        if (!(aIDistantAttacker1 instanceof EntityLiving)) {
            throw new IllegalArgumentException("ArrowAttackGoal requires Mob implements RangedAttackMob");
        }
```

Implies that the class should really be called ArrowAttackGoal, IDistantAttacker called Mob, and EntityLiving called RangedAttackMob ? 

This seems confusing though, as I would have expected that the instanceof check is backwards considering the current naming.

**Comment by asiekierka** [comment]
From experience, I know that the Mojang names are sometimes left unupdated.

They're a hint, sure, but compatibility with Mojang's internal mappings was never a goal.
