### ISSUE TITLE
CanMine is reversed

### ISSUE THREAD

**Issue by valoeghese** [asiekierka/MinecraftPOMF#1280]
I think people have noticed this already, but, at least in 1.15.2, PlayerEntity#canMine is reversed
![image](https://user-images.githubusercontent.com/46117728/79217027-3cea2100-7ea2-11ea-8d38-340b56af505a.png)

**Comment by valoeghese** [comment]
![image](https://user-images.githubusercontent.com/46117728/79217094-5c814980-7ea2-11ea-8e87-5774adf4799e.png)

**Comment by valoeghese** [comment]
see ServerPlayerInteractionManager#tryBreakBlock

**Comment by Juuxel** [comment]
See #1232.
