### ISSUE TITLE
CookingRecipeJsonFactory spelling error with parameter

### ISSUE THREAD

**Issue by Prospector** [asiekierka/MinecraftPOMF#1292]
![image](https://user-images.githubusercontent.com/6166773/79820479-2a0f9a80-8341-11ea-9fdc-c8f153d2c3ad.png)
`ouptut` -> `output`

**Comment by liach** [comment]
net/minecraft/client/gui/screen/ingame/BookEditScreen.stripFromatting()

RuinedPortalFeaturePiece should be in structures, not world/gen
not only are Generators there but also base Piece classes

A few other notes from discord yarn channel so we get all of them fixed
