### ISSUE TITLE
Parameter names wrong in fillGradient(int top, int left, int right, int bottom, int color1, int color2) in DrawableHelper

### ISSUE THREAD

**Issue by 2No2Name** [asiekierka/MinecraftPOMF#1293]
using yarn_mappings=1.15.2+build.14
The parameter names/order in DrawableHelper.fillGradient(top, left, right, bottom, color1, color2)  seems to be wrong.
It should probably be DrawableHelper.fillgradient(**left**, **top**, right, bottom, color1, color2).
I tested this with the call 
    fillGradient(0, 100, 60, 120, 0x800000ff, 0x80ff00ff);
which fills a box that is 20 high, 60 wide and placed at the left border of the screen:

![Screenshot at 2020-04-21 16-18-10](https://user-images.githubusercontent.com/50278648/79876814-cc845800-83eb-11ea-96c0-230f1000e8d3.png)

**Comment by shedaniel** [comment]
in snapshots we renamed them to x1 y1 x2 y2, because top doesn't have to be the top, it can be the bottom

**Comment by YanisBft** [comment]
Outdated issue
