### ISSUE TITLE
Biome#getMaxSpawnLimit is wrong

### ISSUE THREAD

**Issue by valoeghese** [asiekierka/MinecraftPOMF#1301]
![image](https://user-images.githubusercontent.com/46117728/80091355-153b3d00-85b5-11ea-9dd5-33a83042e287.png)

![image](https://user-images.githubusercontent.com/46117728/80091388-23895900-85b5-11ea-9c3e-240eb18ff6ff.png)

**Comment by vini2003** [comment]
I approve, this is of utmost importance.

Not but for real though.
