### ISSUE TITLE
EntityCategory -> SpawnGroup

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#1315]
This category thing has little to do with the intrinsics of entity, but is actually often used for spawning checks of entities. This rename can also reduce confusion with `EntityGroup`, etc.

**Comment by Runemoro** [comment]
I think `SpawnType` would be better. Right not the only reason it's named "category" is that we have an `EntityType` class.

**Comment by liach** [comment]
We already have `class_3730` as `SpawnType`, which indicates the cause of spawning, such as `NATURAL`, `SPAWNER`, etc.

**Comment by liach** [comment]
Hmm, I think `SpawnGroup` may be better, as entities are grouped under this and have a cap for each group.

**Comment by Sollace** [comment]
`SpawnType` -> `SpawnReason`
`EntityCategory` -> `SpawnGroup`

**Comment by liach** [comment]
@Juuxel @Yanis48 want to hear your opinion on this as well. Maybe @sfPlayer1 as well

**Comment by YanisBft** [comment]
Looks like a good rename
