### ISSUE TITLE
New Level Properties Hierarchy

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#1337]
In one of the recent version (20w17a?) Mojang abstracted level properties to a hierarchy.

A bikeshedding thread is now available https://etherpad.wikimedia.org/p/levelproperties_bikeshed

## Inheritance tree: 
![inheritance](https://user-images.githubusercontent.com/7806504/81255314-f7c59480-8ff2-11ea-8f00-d7209b464861.png)

----
## Interface description
- `class_5217`: A basic interface, exposing some getters for spawn pos, raining, thundering, time, difficulty, generator info
- `class_5269`: additionally includes some setters (spawn pos/time). One protected final instance kept in `World` class.
- `class_5268`: additionally includes some getters for logical server side properties, e.g. dimensional data, weather time, wandering trader properties. One private final instance kept in `ServerWorld` class, same as that instance in `World` class but both are visible in `ServerWorld`
- `class_5219`: A basic interface for `level.dat` elements that applies to an instance of `MinecraftServer`. One instance of it is kept in `field_24372`. Includes data pack info, brand info, seed, difficulty, gamerule, etc. many of which are the same methods in the hierarchies of `class_5268`. Also used by `LevelSummary`.
----
## Implementation description
- `LevelProperties`: Seems like the old level properties, and the only implementation in this tree that comes from loading `level.dat` file.
- `SecondaryLevelProperties`: No longer extend `LevelProperties` as before; blanks out setters; has a delegate `class_5268` and a delegate `class_5219`, in which some properties are delegated from the `5219` and some from `5268`. Also has special handling of world data setting/getting, in which passes the dimension type object this properties hold to its delegate to get dimension-specific world data.
- `ClientWorld$class_5271`: Implements interface methods but additionally have two setters for difficulty and locking. One private final instance kept in `ClientWorld` class (but unused), same as that instance in `World` class but both are visible in `ClientWorld`. Updated through `ClientPlayNetworkHandler`'s packet reception where one instance is kept as well (created at `GameJoinS2CPacket`, difficulty updated in `DifficultyS2CPacket`, updated on player respawn as well).

----

### My two cents:
Mojang seems to start splitting off stuff from `level.dat` into components that should be available to the client world, each server world, and the server in general. Although the client and server split is clean, the server world and general server split seems to be half-done (as all worlds still uses the same world border and generator options from the main `level.dat` data, even for secondary/derived world properties).

----

### My plan:
I personally want to rename `LevelProperties` to `LevelData` as these are loaded from the `Data` subtag of the root NBT compound of the `level.dat` file, while the world-specific interfaces I suggest rename the series to `WorldData` `MutableWorldData` `ServerWorldData` `ServerData` `SecondaryServerWorldData`(data of secondary server world) `LevelData`(`level.dat`) `ClientWorld$Data`.
![my plan](https://user-images.githubusercontent.com/7806504/81257106-0ebab580-8ff8-11ea-8d22-9968355b0936.png)

----

## Final words
I want some quality bikeshedding here. Many prs attempt to work on this system, yet I find them confusing and incompetent to convey this updated structure. Please bikeshed here so we don't have to debate again for fixing up the upcoming poor names.

If you want to rename the existing `LevelProperties` to like `WorldData` or so, please suggest here as well!

**Comment by Pyrofab** [comment]
I wrote my thoughts in the [relevant PR](https://github.com/FabricMC/yarn/pull/1329#issuecomment-625288283) : 
- The `LevelProperties` name seems a bit outdated. Currently it seems to reflect the state of a single world/dimension. As such, I would recommend naming `class_5219` (the base interface) "WorldProperties".
- `class_5269` is a specialization of `class_5219` with setters. I would suggest naming it "MutableWorldProperties".
- `class_5271` and `class_5268` are the specializations of `class_5269` for `ClientWorld` and `ServerWorld`, respectively. As such, I would suggest simply naming them `ClientWorldProperties` and `ServerWorldProperties`.
- `UnmodifiableLevelProperties` is a specialization of `class_5268`, used by `SecondaryServerWorld`. It adds the property `"Derived"` to crash reports, which leads me to suggest `DerivedWorldProperties`.
- `class_5219` is the interface where every global method from the old `LevelProperties` went (eg. `getLastPlayed` or `getEnabledDataPacks`). If we consider `level` to mean "the whole save", this interface is the one that should be called `LevelProperties`.
- The class that is currently named `LevelProperties` implements `class_5268` and `class_5219`. It does not seem unlikely that it gets split in the future. I guess we could call it `PrimaryWorldProperties`.

**Comment by liach** [comment]
My few cents for @Pyrofab:
1. `Properties` -> `Data` (rename this part). 
`Properties` sounds resembling of something from a java `.properties` file, yet `level.dat` is not a `.properties` file. The main data of `level.dat` is stored in the `Data` subcompound in the root NBT compound, so I am using the name `Data`. There may be better alternatives.
2. `class_5219` shouldn't be `LevelProperties`:
`class_5219` is used in like `LevelSummary`, which means it is like a save(server) specific information (note that one Minecraft server can only run on one save). Calling it `Level` I disagree; a name with like `Save` `Server` should be used to outline that attribute.

**Comment by Pyrofab** [comment]
What exactly is wrong with `LevelSummary` using `LevelData` ?

**Comment by liach** [comment]
Now I decide to keep the `Properties` suffix and `class_5219` will be like `SaveProperties`. How does that sound @Pyrofab?

**Comment by liach** [comment]
Now the plan is like `WorldProperties` `MutableWorldProperties` `ClientWorld$Properties` `ServerWorldProperties` `SecondaryServerWorldProperties` `LevelProperties` (name kept) `SaveProperties`. How's that?

**Comment by liach** [comment]
This set of new names has been included in #1353. Can close this after that pr is merged.
