### ISSUE TITLE
Criterion -> Trigger

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#1343]
Observe the line `"trigger": "minecraft:inventory_changed",`.
We currently name such thing `Criterion`, and they should probably be `Trigger` or `CriterionTrigger`?

----
```json
{
  "display": {
    "icon": {
      "item": "minecraft:grass_block"
    },
    "title": {
      "translate": "advancements.story.root.title"
    },
    "description": {
      "translate": "advancements.story.root.description"
    },
    "frame": "task",
    "show_toast": false,
    "announce_to_chat": false,
    "hidden": false,
    "background": "minecraft:textures/gui/advancements/backgrounds/stone.png"
  },
  "criteria": {
    "crafting_table": {
      "trigger": "minecraft:inventory_changed",
      "conditions": {
        "items": [
          {
            "item": "minecraft:crafting_table"
          }
        ]
      }
    }
  },
  "requirements": [
    [
      "crafting_table"
    ]
  ]
}
```

**Comment by YanisBft** [comment]
I don't think it should be renamed, as the interface provides methods related to conditions. Docs should be added though

**Comment by liach** [comment]
Hmm, is there anywhere else where they are named by explicit strings?

**Comment by YanisBft** [comment]
I didn't see other strings. About clarification, maybe `getId()` should be renamed to `getTriggerId()`

**Comment by liach** [comment]
Criterion is actually seen in `Criteria` class' message `"Duplicate criterion id "`, so should probably leave it as is.
