### ISSUE TITLE
MessageType package

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#1359]
`MessageType` was moved to `network` package by jamierocks in the chat refactor. 

Looking at it now, it does fit networking more than text (overwhelming usage in client/server game message packets), but it is also used by the client's `ChatMessageListener` (probably wants a rename to `GameMessageListener` as well!) and hence by the Narrator.

Any idea for a better home (package) for `MessageType`?

**Comment by shartte** [comment]
I actually think it fits text better and is just used by networking (just as Direction is!). Then again. Is it worth moving?

**Comment by apple502j** [comment]
1.19 created a dedicated package. Closing.
