### ISSUE TITLE
Shorten IInventory methods?

### ISSUE THREAD

**Issue by copygirl** [asiekierka/MinecraftPOMF#139]
Currently the `IInventory` methods are called `setInvStack` etc, though I can't help but feel like I want to shorten them to simply `set` etc. Though things like block entities which implement the interface directly might suffer from it or it could make code more confusing if somebody is unsure about the object being an inventory. Thoughts?

**Comment by asiekierka** [comment]
It's very intentional, to prevent conflicts.

**Comment by copygirl** [comment]
@asiekierka Where for example?

**Comment by asiekierka** [comment]
In mods. IInventory should have, IMHO, been a component with some kind of getter... This prefix helps tell them apart from a modder's more intentional mtethods.

**Comment by copygirl** [comment]
Well ... if we expose vanilla inventories via a component that has a nicer looking interface ... I'd be fine with it! :smile:

**Comment by asiekierka** [comment]
You do it. I have other things to work on :)
