### ISSUE TITLE
Registry.DIMENSION -> Registry.WORLD

### ISSUE THREAD

**Issue by Earthcomputer** [asiekierka/MinecraftPOMF#1413]
As of 20w22a, there are two registries related to the different dimensions: `Registry.DIMENSION_TYPE` and `Registry.DIMENSION`. Since the latter stores actual World instances, I propose this be renamed to `Registry.WORLD`.

**Comment by Earthcomputer** [comment]
In fact, to make it absolutely clear, how about `Registry.SERVER_WORLD`? From what I understand so far, the registry appears to have replaced `MinecraftServer.worlds`.

**Comment by ImUrX** [comment]
i always tried writing Registry.WORLD instead of Registry.DIMENSION. i like this idea

**Comment by The-Code-Monkey** [comment]
I think Registry.WORLD makes sense and we can use that to help differentiate between the two registry entries.

**Comment by liach** [comment]
yeah we might call what has always been a "world" before a world

**Comment by liach** [comment]
@Earthcomputer What do you recommend for the `DIMENSION_OPTIONS` one? That field's value `==` to the `DIMENSION` one's value, even though they don't appear so (for the dummy generics used). Related #2151, maybe we can call one `WORLD` and the other one `WORLD_SPEC`

**Comment by Earthcomputer** [comment]
Are those new registries? Can't say I've looked at them so I don't know.

**Comment by liach** [comment]
Those are old ones that were added back when the data pack registry custom dimensions were first added.

**Comment by liach** [comment]
renamed to WORLD_KEY in #2253.
