### ISSUE TITLE
Material-/MapColor Field Renames

### ISSUE THREAD

**Issue by dexman545** [asiekierka/MinecraftPOMF#1451]
For longterm discussion about how to best rename them. 

It should be noted that while bad, they are at least moderately functional (when you know they're for colors on a map).

The field names are currently named using three different systems:
- The color that it actually is
- The material that uses the color (outdated/abbreviated names)
- The block that uses the color

At the very least they should all follow a unified naming scheme, of which there are three practical ones:
- Naming color based on the color it actually is
    - Bikeshed time
    - Difficult as we have about 12 shades of brown.
- Based on the blocks that use it
    - More work to compile, maintain, and leads to names similar to the new Material one's, but with more mess as color is _per blockstate_, so this is likely impossible to do well.
- The hex value of the color
    -  Each rename is simple, but now each name is also useless unless you can interpret hex color codes.

The first option would be the most reasonable to use. We can also "cheat" a little and refer to MC textures, though that will require a Javadoc disclaimer (eg Emerald Green doesn't mean dark green, but MC's emerald color). Slightly complicated by MC's naming being off for some colors. Naming them in terms of *blockReference_baseColor* would make things more uniform and easier to understand, but would mean 16 more renames for the terracotta colors.

Here are all the color's hex values, and setup so Idea will show you the color on the side: https://pastebin.com/nTXgt3Dr

**Comment by YanisBft** [comment]
Only partially fixed by #1490

**Comment by dexman545** [comment]
Here are some names: https://gist.github.com/dexman545/aa6e9bac9eb2dfd8de28b8023781e288

**Comment by Prospector** [comment]
Those look pretty good to me tbh

**Comment by TelepathicGrunt** [comment]
I APPROVE! ANYTHING IS BETTER THAN MCP NAMES. AND IDK WHY I AM YELLING

Joking aside, I really like the color names. I can picture all of them much easier. The only one that I stumbled a bit on is PALE_ORANGE_BROWN but that's tough to name
