### ISSUE TITLE
EntryListWidget.Entry has wrong params for render method

### ISSUE THREAD

**Issue by i509VCB** [asiekierka/MinecraftPOMF#1460]
~~Params are currently:~~
~~`public abstract void render(MatrixStack matrices, int index, int y, int x, int entryWidth, int entryHeight, int mouseX, int mouseY, boolean hovered, float tickDelta);`~~

~~Should be~~
~~`public abstract void render(MatrixStack matrices, int x, int y, int index, int entryWidth, int entryHeight, int mouseX, int mouseY, boolean hovered, float tickDelta);`~~

**Comment by i509VCB** [comment]
Upon further look above may not be correct. so now it's just generally document this

**Comment by shedaniel** [comment]
I remember this method being absurd and having y before x, I am not sure if that's the case anymore, but probably.

This method should be fairly easy to understand though, not sure if you really need any doc?

**Comment by i509VCB** [comment]
Not having a fun time trying to figure out what params go where in gamerules tbf

**Comment by shedaniel** [comment]
modding with this before v2 was a thing was hell.

**Comment by i509VCB** [comment]
If it's y before x, I'd say we should document it because it's confusing
