### ISSUE TITLE
MobEntityWithAi is inaccurate

### ISSUE THREAD

**Issue by Draylar** [asiekierka/MinecraftPOMF#1463]
To me, `MobEntityWithAi` implies:
   - `MobEntity` can't have AI
   - `MobEntityWithAi` provides AI capabilities

This is not the case. The `MobEntityWithAi` class provides the following differences:
  - `getPathfindingFavor`, which lets entities say, "I like walking through lava!"
  - an override of `canSpawn` to account for pathfinding favor
  - `isNavigating`, used in raids and for wolves
  - an overridden `updateLeash` function  and 2 utility methods for it

Given the fact that this class seems to surround pathfinding favors, a name like `PathAwareMobEntity` (suggested by Thalia) or `FavoredPathingMobEntity` might be more appropriate. 

"*But wait!*", you say: "*there are AI tasks that exclusively ask for MobEntityWithAi! Wouldn't that mean MobEntities can't do certain AI tasks?*" That's correct, but if you look at the usages within those tasks, what you'll see is that AI tasks and mechanics that use `MobEntityWithAi` *generally* utilize the pathfinding favor method for things like `TargetFinder`. 

Interestingly enough, `MobEntity` has pathfinding penalties, while `MobEntityWithAi` has pathfinding favors. Not sure if the two are related.

I might be missing something (and be completely wrong), but I can't find anything else that would support the `WithAi` ending. Let me know what you think about potential alternative names.

**Comment by Draylar** [comment]
cc #400, I don't think `PathfinderMob` is appropriate *only because* the base `MobEntity` still has pathfinding capabilities, from what I can see with `MobEntity#pathfindingPenalties`.

**Comment by liach** [comment]
Imo either `FavoredPathingEntity` or `PathAwareEntity` should be good (yes, we should drop the `mob` part as only mobs have pathing)
