### ISSUE TITLE
BoulderFeatureConfig -> ForestRockFeatureConfig

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#1480]
It's only used for `Feature.FOREST_ROCK` (which comes from a registry name).

**Comment by YanisBft** [comment]
I think it was named like that because the registry name was boulder, but if it has changed it definitely needs to be changed

**Comment by Juuxel** [comment]
Yeah, this is how it's registered:
![](https://user-images.githubusercontent.com/6596629/84921215-daddb000-b0cc-11ea-843d-511ad876e4b5.png)
