### ISSUE TITLE
GameRules automatic mapping is broken due to #1381

### ISSUE THREAD

**Issue by DreenDex** [asiekierka/MinecraftPOMF#1493]
## Issue
Fields of [net/minecraft/world/GameRules](https://github.com/FabricMC/yarn/blob/779b1dc2f52747784d4ee61b2683c53eac5360c3/mappings/net/minecraft/world/GameRules.mapping) was mapped automatically (from strings), but in #1381 documentation was added **without names** and mappings are not longer applied automatically.

### Expected behaviour
Mapping names should automatically be named (if possible) from strings without `FIELD` nor `COMMENT` notation at all.

### Yarn version:
1.16-rc1+build.4 _(latest atm)_

### How it looks in `.mapping` file
![image](https://user-images.githubusercontent.com/6661231/85232317-b6544180-b406-11ea-903a-a1af80e0d32a.png)
### The names are not detected automatically
![image](https://user-images.githubusercontent.com/6661231/85232513-f36d0380-b407-11ea-979f-e19427f3efac.png)
### In the library and generated sources there is no names too:
![image](https://user-images.githubusercontent.com/6661231/85232278-72f9d300-b406-11ea-95b0-2fd619e287c3.png)

**Comment by modmuss50** [comment]
humm, thats annoying.

**Comment by modmuss50** [comment]
I think the best thing to do for now is to copy the names over and then look to find where the real issue is.

**Comment by i509VCB** [comment]
looks like comments are popping the autonaming away
