### ISSUE TITLE
LevelProperties#isHardcore returns whether the world has structures [20w29a]

### ISSUE THREAD

**Issue by i509VCB** [asiekierka/MinecraftPOMF#1593]
![image](https://user-images.githubusercontent.com/30619168/87884620-25f12880-c9d5-11ea-9b0a-2a7a27e5ea94.png)

**Comment by shartte** [comment]
According to updateProperties it seems like hardcore would be right:

```
tag.putBoolean("hardcore", this.field_25030.hasStructures());
```
