### ISSUE TITLE
LivingEntity.canPickUp -> ?

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#1614]
It seems to be more of a "can equip" check, where the implementations usually check whether the preferred slot for the item stack is empty.

(If this gets a new name, `EntityPredicates.CanPickup` should also be renamed to match.)

**Comment by liach** [comment]
well, don't mobs with custom goals usually just pick up stuff they can make use of? like pick up helmets, armor, etc.

You should check their usage as well.

**Comment by Juuxel** [comment]
This is used in places like the dispenser behavior that equips armor on entities. (edit: and possibly that entity pick up equipping, which is still equipping)

**Comment by sylv256** [comment]
He's right. The entities equip the items. It would be a little easier to understand what "canEquip" does than "canPickUp" since the entity will equip the items it picks up. As far as I know, entities cannot "pick up" items without equipping them, so it only makes sense to rename it to "canEquip."

**Comment by sylv256** [comment]
I don't think `canEquip` fits the mapping name since modded entities and piglins can pick up items (such as gold nuggets) without equipping them. `canTake` fits the name more because it's easier to type and makes more sense than `canEquip`.

**Comment by sylv256** [comment]
Nevermind. Apparently piglins and other entities don't even use this method. I'll make sure to check how something is used before changing it. I'm re-opening the PR right now.

**Comment by gbl** [comment]
It seems like #1640 breaks the build as there are a few more classes that use canEquip. See my comment in that PR.

**Comment by liach** [comment]
#1643 should resolve that.

**Comment by YanisBft** [comment]
Fixed by #1640
