### ISSUE TITLE
Biome.Settings -> Biome.Builder

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#1641]
The `toString` method calls it `BiomeBuilder`, and in 1.16.2-pre1 it actually is a real builder. The only way to get a biome instance is by calling `build()` on a biome settings/builder instance.

**Comment by liach** [comment]
When mojang actually makes it a builder  ![concern](https://cdn.discordapp.com/emojis/707016186281590855.png?v=1)

**Comment by Juuxel** [comment]
It's a builder in the latest snapshots / pre-releases.

Here's an example of biome creation in 1.16.2-pre1:
![usage of `Biome.Builder`](https://user-images.githubusercontent.com/6596629/89262419-3b528d80-d638-11ea-9edd-0de5cb26866c.png)
