### ISSUE TITLE
NbtOps$MapBuilder and CompoundTag have to be in the same package

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#1649]
`net/minecraft/class_2509$class_5320` (`net/minecraft/datafixer/NbtOps$MapBuilder`) and `net/minecraft/class_2487` (`net/minecraft/nbt/CompoundTag`) have to be in the same package.

In the `DataResult<Tag> build(CompoundTag compoundTag, Tag tag)` method of `NbtOps$MapBuilder`, it calls `method_29143` (unnamed, maybe `toMap`), which is a protected method in `CompoundTag`. Since `MapBuilder` is not a subclass of `CompoundTag`, it is fairly clear they should be in the same package.

I personally suggest moving NbtOps to the nbt package.

**Comment by i509VCB** [comment]
That sounds reasonable as NbtOps is directly related to nbt itself.
