### ISSUE TITLE
AbstractBlock.Settings.lightLevel -> luminance

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#1654]
It sets the `luminance` field and controls the value of `BlockState.getLuminance`.

**Comment by TheBrokenRail** [comment]
Why not just change the ``luminance`` field to ``lightLevel`` and ``getLuminance`` to ``getLightLevel``. I personally like ``lightLevel`` more than ``luminance``.

**Comment by TheBrokenRail** [comment]
Anyone have any other thoughts on this? Or should I make a PR?
