### ISSUE TITLE
RegistryKey -> TypedIdentifier

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#1674]
Though this key is pretty much designed around registry, much of the key now is used for generic type-identification purpose (like for worlds), and `TypedIdentifier<Registry<T>>` is easier to understand than `RegistryKey<Registry<T>>`, or `TypedIdentifier<DimensionType>` vs `RegistryKey<DimensionType>`

**Comment by Earthcomputer** [comment]
I prefer the name `TypedIdentifier` to `TypedKey`. However I still think we should wait a little longer for where Mojang takes this class. It still has a little too many registry-specific methods in it for me to be comfortable with the rename as of 1.16.2.

**Comment by liach** [comment]
Does it look fit to be named `TypedIdentifier` now?

**Comment by apple502j** [comment]
Given the introduction of `RegistryEntry` this probably should be closed as not accepted.
