### ISSUE TITLE
SpawnGroup fields are inconsistent

### ISSUE THREAD

**Issue by YanisBft** [asiekierka/MinecraftPOMF#1696]
As seen on the picture below, SpawnGroup fields are not correctly named, especially the "animal" one which should obv not apply to misc entities
![image](https://user-images.githubusercontent.com/16228338/90313219-16e59380-df0b-11ea-91c2-5c726839b261.png)

**Comment by haykam821** [comment]
The `peaceful` field is used only for this:

```java
if ((spawnAnimals || !spawnGroup.isPeaceful()) && (spawnMonsters || spawnGroup.isPeaceful()) && (shouldSpawnAnimals || !spawnGroup.isAnimal()) && info.isBelowCap(spawnGroup)) {
	spawnEntitiesInChunk(spawnGroup, world, chunk, (entityType, blockPos, chunkx) -> {
		return info.test(entityType, blockPos, chunkx);
	}, (mobEntity, chunkx) -> {
		info.run(mobEntity, chunkx);
	});
}
```

The `shouldSpawnAnimals` used in this context is determined by `worldProperties.getTime() % 400l == 0l`. Perhaps it should be `shouldSpawnRarely` then?

**Comment by liach** [comment]
I think `animals` is something from server properties file. Need to check again.

**Comment by liach** [comment]
Not a problem in latest yarn 07a.

**Comment by YanisBft** [comment]
Why? "Misc" spawn group still passes `true` for the "animal" field, which doesn't make sense

**Comment by liach** [comment]
Hmm, so it's looking for usage of `isAnimal`

**Comment by liach** [comment]
Afai see, that `isAnimal` is never called on `MISC` instances. In fact, it is only called in `SpawnHelper.spawn(ServerWorld, WorldChunk, SpawnHelper.Info, boolean spawnAnimals, boolean spawnMonsters, boolean shouldSpawnAnimals)` (the boolean fields have inadequate names) in a loop over `SPAWNABLE_GROUPS`, which has everything except `MISC`.

**Comment by liach** [comment]
Now I see. that is not `isAnimal`, more like `isRare`. pr coming soon
