### ISSUE TITLE
method_8323 - not chunk center pos but lowest northwest corner

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#1707]
`method_8323` for now is named `getCenterBlockPos`, which is wrong as it is `return new BlockPos(this.getStartX(), 0, this.getStartZ())`, i.e. returning the lowest northwest corner pos of the chunk.

**Comment by TheBrokenRail** [comment]
Well if it is ``getStartX`` and ``getStartZ``, why not ``getStartPos``?
