### ISSUE TITLE
Make sense of .util.shape.*

### ISSUE THREAD

**Issue by asiekierka** [asiekierka/MinecraftPOMF#171]
Some of the classes are in, but I'm not sure what the DoubleLists are for. Can someone with a better working knowledge of the area chime in?

**Comment by grondag** [comment]
I can help with these.  These look to be new so prior exposure to MCP names shouldn't exclude me.

I built my own routines for Octree & voxel-based procedural collision box generation.  They aren't doing the same thing here but similar domain.

Will take me a while to get to it.  Want to grok the new render changes first.

**Comment by grondag** [comment]
Also, to answer your question directly, DoubleList is clever hack to index the division coordinates of a volume that is equally subdivided into an arbitrary number of slices.  Mojang _really_ likes collections.
