### ISSUE TITLE
Serialization/deserialization method naming

### ISSUE THREAD

**Issue by asiekierka** [asiekierka/MinecraftPOMF#172]
```
@asie | pomf, JSON serialization: JsonObject serialize() vs JsonObject asJson() vs JsonObject toJson()
@asie | likewise for ByteBufs: serialize() vs. writeToPacket() vs. writeToBuf() vs. write()
@asie | and likewise for JSON deserialization: deserialize() vs fromJson()
@asie | and ByteBuf reading: deserailize() vs. readFromPacket() vs. readFromBuf() vs. read()       
```

**Comment by Player3324** [comment]
serialize -> too generic, it's not yielding an opaque format "protected" from external modification, but also insufficiently descriptive with MC commonly serializing to NBT trees, NBT strings, JSON trees, JSON strings or binary blobs
as* -> implies a direct equivalent, which is not necessarily the case, also no easy reverse name
to* -> descriptive, short, from* is the direct reverse equivalent

**Comment by liach** [comment]
We have determined to use `toXxx` `fromXxx` per player. See https://github.com/FabricMC/yarn/blob/19w40a/CONVENTIONS.md#serialization
