### ISSUE TITLE
Item#getStackForRender is misleading

### ISSUE THREAD

**Issue by enbrain** [asiekierka/MinecraftPOMF#1767]
This method is called from non-rendering code. For example, `CowEntity#interactMob` uses this method to create a milk bucket.

**Comment by i509VCB** [comment]
The name might have been from an earlier time where it was used exclusively for rendering. I'd probably name it `createItemStack`

**Comment by enbrain** [comment]
I'd suggest `getDefaultStack` for consistency with `Block#getDefaultState`.
