### ISSUE TITLE
Sticking to net.minecraft.reference.*?

### ISSUE THREAD

**Issue by asiekierka** [asiekierka/MinecraftPOMF#177]
Advantages: In my personal opinion, cleaner

Disadvantages: Requires modifying access levels to get there, which is not a good thing for a _mapping_ and adds complexity to projects willing to use pomf; ultimately not worth it IMO

**Comment by jamierocks** [comment]
I think that pomf should totally avoid requiring access level changes, though it is kinda clean to have all them under one roof - though under their respective packages is clean too.

**Comment by asiekierka** [comment]
Well then, that's decided.
