### ISSUE TITLE
Change MinecraftClient#close to MinecraftClient#shutdown

### ISSUE THREAD

**Issue by RDIL** [asiekierka/MinecraftPOMF#1784]
Right now, some eclipse-based IDEs (e.g. [Theia](https://github.com/eclipse-theia/theia)) raise warnings because of the fact that it thinks `MinecraftClient#close` indicates that it is a **disposable object** (like a `FileWriter`).

For example:
![Screenshot 2020-10-08 at 10 29 54 AM](https://user-images.githubusercontent.com/34555510/95472589-3cae7800-0951-11eb-8666-4bd736b18bb7.png)

Yes, this isn't THAT important, but it is still a pretty big thing that triggers my OCD, so it might be worth changing.

I'm welcome to any thoughts or other names for it, as long as it isn't called `close`.
I'm also happy to open a PR if you want me to.

**Comment by shedaniel** [comment]
MinecraftClient actually implements AutoClosable

**Comment by RDIL** [comment]
Oh huh, I didn't know that.

I feel like there must be some way around this?

**Comment by RDIL** [comment]
Closing since this isn't a yarn matter.
