### ISSUE TITLE
will old versions, like 1.7.10, ever get mappings?

### ISSUE THREAD

**Issue by ghost** [asiekierka/MinecraftPOMF#1826]
simple question, hope there's a simple answer

**Comment by modmuss50** [comment]
There are no plans to make offical mappings, as there is enough to be getting on with newer versions. Possibly if we get bored but I dont see it happening.

There are a number of unoffical older mappings projects that may have a 1.7.10 version, failing that there is a wiki page if you wanted to look at doing it yourself: https://fabricmc.net/wiki/tutorial:updating_yarn
