### ISSUE TITLE
Change PotionEffect and PotionEffectType to EffectStack and Effect

### ISSUE THREAD

**Issue by reoseah** [asiekierka/MinecraftPOMF#185]
- remove Potion prefix from Effect classes, move them to `effect` package 
- switch what is "base" name and what is "qualified" name
Compare to similar classes for items: stateless thing is just `Item`, and wrapper around it is `ItemStack`.

Also, I personally prefer `EffectDamageModifier` to `EffectDamage`, despite it's a bit longer.

List of classes to cnange:
```
PotionEffect -> EffectStack
PotionEffectType -> Effect
PotionEffectTypeAbsorption -> EffectAbsorption
PotionEffectTypeDamage -> EffectDamageModifier
PotionEffectTypeHealthBoost -> EffectHealthBoost
PotionEffectTypeInstant -> EffectInstant
PotionEffectTypes -> Effects
PotionEffectUtil -> EffectUtils
```

**Comment by asiekierka** [comment]
There's another precedent: AttributeInstance. Likewise, we could use EffectInstance. ItemStack relates to the *stackability* of Items, which potion effects, well, don't.

**Comment by asiekierka** [comment]
In fact, official nomenclature refers to them as "mob effects". So MobEffect and MobEffectInstance it is.
