### ISSUE TITLE
ScreenHandler#unpackQuickCraftStage() and ScreenHandler#unpackQuickCraftButton() are swapped

### ISSUE THREAD

**Issue by stenlan** [asiekierka/MinecraftPOMF#1886]
The names for ScreenHandler#unpackQuickCraftStage() and ScreenHandler#unpackQuickCraftButton() seem to be swapped, since the result of the former is actually assigned to a field named quickCraftButton, and the latter to a variable named quickCraftStage.

**Comment by stenlan** [comment]
Now that I look at what the functions actually do, I see that actually the field names are swapped instead, and the function names are correct.

This also reflects on the parameter named _stage_ in ScreenHandler#shouldQuickCraftContinue(int stage), which should be _button_. There might be more functions influenced by it.

**Comment by stenlan** [comment]
One last thing, I think it might be better to rename both functions to use _extract_ or something instead of _unpack_, since unpack implies that it _receives_ that kind of value, while it actually _returns_ it. It receives a raw "quickCraftData" in both cases.

**Comment by liach** [comment]
Moved to #1986
