### ISSUE TITLE
Fabric isn't capable of loading classes with EnumProperty<>

### ISSUE THREAD

**Issue by lucbf** [asiekierka/MinecraftPOMF#1923]
This tutorial uses _BooleanProperty_: [https://fabricmc.net/wiki/tutorial:blockstate](https://fabricmc.net/wiki/tutorial:blockstate)
but replacing it with an _EnumProperty_ causes an _ExceptionInInnitializerError_, even if you just leave the field alone. Tested on 20w49a and 20w51a

I also posted this issue at the fabric loader repository: [https://github.com/FabricMC/fabric-loader/issues/348](https://github.com/FabricMC/fabric-loader/issues/348)
I'm also posting this here because I have no idea which project is responsible for this error.

**Comment by pluiedev** [comment]
Yarn is the set of mappings (or names) Fabric uses for de-obfuscating Minecraft class files. It has nothing to do with your problem.

**Comment by Player3324** [comment]
this is a fabric-api issue if any, moved the fabric-loader one there
