### ISSUE TITLE
`getSelected` -> `getSelectedOrNull`

### ISSUE THREAD

**Issue by yyny** [asiekierka/MinecraftPOMF#1925]
`EntryListWidget` contains a mapping `getSelected` for `method_25334`, which returns a `EntryListWidget.Entry`.

However, there also exists a `method_20159` which is a wrapper around `method_25334` returning an `Optional<EntryListWidget.Entry>` (via `return java.util.Optional.ofNullable(this.method_25334());`).

I propose changing the name of the former function to inform the user of the nullability of its return type, and name the second function `getSelected`.

For the sake of following convention, we might also consider naming `method_20159` `getOptionalSelected` or `getSelectedOrEmpty`.

The convention that exists so far might be sufficient, but I haven't actually found any other examples of a getter function having a non-nullable alternative, and explicitly mentioning the nullability of the return type seems beneficial for the programmer so they can more easily avoid making a mistake.

**Comment by Sollace** [comment]
`getSelectedOrEmpty` is the convention I've seen (and follow myself) where you have both a nullable and Optional<?> version of a getter.
