### ISSUE TITLE
Cannot generate Javadocs

### ISSUE THREAD

**Issue by altrisi** [asiekierka/MinecraftPOMF#1942]
When running `gradlew javadoc`, Gradle is unable to generate javadocs, failing with `javadoc: error - cannot read Input length = 1` in the `:javadoc` task.

Workaround:
After searching ways to fix this, I found that passing `-Dfile.encoding=UTF-8` to Gradle makes it work correctly. I think this should not be needed.

Environment:

- Windows 10
- Java 11 (Zulu openjdk 11.0.9.1)

**Comment by YanisBft** [comment]
Can't reproduce with Adopt OpenJDK

**Comment by liach** [comment]
Afaik mappingpoet is always outputting .java files in utf8 as that's javapoet's default behavior. Not sure what part uses other encoding.

**Comment by YanisBft** [comment]
Do you still have this issue?

**Comment by altrisi** [comment]
Tested right now in 8276930, not failing anymore.
