### ISSUE TITLE
Serious problems with Block class mappings

### ISSUE THREAD

**Issue by maityyy** [asiekierka/MinecraftPOMF#1951]
My experience and tests show that it is impossible to use mixin injection for Block classes. All crashes indicate that the overridden class method was not found and the refmap was not loaded.

**Comment by maityyy** [comment]
Mixin class: https://pastebin.com/EtLYL96F
Refmap: https://pastebin.com/YCQ5xkJe
Crash-log: https://pastebin.com/UurQuG7B

**Comment by maityyy** [comment]
I really have never been able to inject into these classes yet... If you are a member of Fabric Discord server, you can read about my other deplorable experience with other mixins. And the problem is the same.

https://discord.com/channels/507304429255393322/507982478276034570/787423658875682847

**Comment by Chocohead** [comment]
This is not really the repo for this kind of thing but having tried essentially the same Mixin as you...
```java
@Mixin(NoteBlock.class)
public class NoteBlockMixin {
    @Inject(
            method = "onSyncedBlockEvent",
            // Note block played
            at = @At(
                    value = "INVOKE",
                    target = "Lnet/minecraft/block/BlockState;get(Lnet/minecraft/state/property/Property;)Ljava/lang/Comparable;",
                    ordinal = 0
            )
    )
    private void notifyMobs(BlockState state, World world, BlockPos pos, int type, int data, CallbackInfoReturnable<Boolean> callback) {
        int distance = 16;

        List<PlayerEntity> players = world.getEntitiesByClass(
                PlayerEntity.class,
                new Box(pos.getX(), pos.getY(), pos.getZ(), pos.getX() + distance, pos.getY() + distance, pos.getZ() + distance),
                mob -> mob instanceof PlayerEntity
        );

        Instrument instrument = state.get(NoteBlock.INSTRUMENT);

        for (PlayerEntity player : players) {
        	player.sendMessage(new LiteralText("Near " + instrument.asString()), true);
        }
    }
}
```
I got the same refmap produced but the game loaded fine. If you are setting the refmap name explicitly in your `build.gradle` I would make sure it is being added to your mixin JSON, Loom will generate and add it for you if you're not setting it. This also has nothing to do with `Block`, nor the mappings `Block` has, the same issues and resolution would come from any Mixin requiring a refmap entry.

**Comment by Juuxel** [comment]
These problems are with Mixin and not at all related to Yarn's mapping contents for `Block`, so I'll be closing this issue.
