### ISSUE TITLE
MobEffect?? -> StatusEffect

### ISSUE THREAD

**Issue by Prospector** [asiekierka/MinecraftPOMF#198]
While MobEffect is the confirmed Mojang name, I have no idea where it came from because it's a pretty bad name. Not only mobs have status effects. Status effect is the common name used by the community, so I think it makes the most sense.

**Comment by liach** [comment]
Or `LivingEffect` as they are applicable to all livings.

**Comment by Prospector** [comment]
Perhaps...but I like sticking with the community used names if possible, even if slightly less descriptive

**Comment by asiekierka** [comment]
https://github.com/FabricMC/pomf/tree/18w47b
