### ISSUE TITLE
EntityFactory -> EntityType; EntityType -> EntityCategory

### ISSUE THREAD

**Issue by Prospector** [asiekierka/MinecraftPOMF#199]
EntityFactory just makes little sense...a factory should build entities not be the actual type of entity. Also mojang calls it EntityType.

EntityType is ok, but I think EntityCategory is a more fitting name. This is the class that defines an entity as either MONSTER, CREATURE, AMBIENT, or WATER_CREATURE.

**Comment by asiekierka** [comment]
In favor.
