### ISSUE TITLE
getPlayerFacing -> getPlayerHorizontalFacing

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#2028]
- `ItemUsageContext.getPlayerFacing` -> `getPlayerHorizontalFacing`
  It calls `player.getHorizontalFacing()`. The current name leaves out the "horizontal" part which is an important fact about the method.
- ~~`ItemPlacementContext.getPlayerLookDirection` -> `getPlayerFacing`~~
  It calls `Direction.getEntityFacingOrder(getPlayer())`.
  - This one is more risky of a rename: `ItemPlacementContext` extends `ItemUsageContext` so old code using the horizontal method could start using this one and crashing.

**Comment by liach** [comment]
Hmm, can we name the all-direction version just `getPlayerDirection`, and the other `getPlayerHorizontalDirection` as they return `Direction`?

**Comment by Juuxel** [comment]
Works for me, though the debug hud does call the horizontal direction "facing". ("Facing" also implies that the entity in question is *looking*. A player "direction" could refer to the movement direction, and the player can walk backwards.)
