### ISSUE TITLE
Add package javadoc

### ISSUE THREAD

**Issue by LambdAurora** [asiekierka/MinecraftPOMF#2035]
Since yarn javadocs is now published (https://maven.fabricmc.net/docs/yarn-21w05b+build.11/), it would be cool to have package info Javadocs.

**Comment by liach** [comment]
Someone finally found the links! :smile:
Given how yarn works, I guess we might make actual `package-info.java` files for the docs.
In addition, it would be cool to think about generating an overview-summary.html as well from some html description. I've thought about using pandoc (we can install that on github actions) to convert readme to an html for javadoc tool to use.

**Comment by Player3324** [comment]
The tooling and mapping formats don't support packages yet.

**Comment by liach** [comment]
Yeah, package docs will only be included in the generated jd jar (like how mappingpoet inserts block tags for mappings in the fake source generated) and stored in yarn for now in a different format (I plan to use actual package-info.java files). The package docs will only be in the javadoc jars (and online views), but that should suffice for many purposes (at least for now)

**Comment by liach** [comment]
Now we have constant source set and javadocs. Would not be too hard to introduce a new package doc source set, which would function similarly to constants sources, and possibly have package docs distributed in extra files like the unpick definitions or with the constants jar.
