### ISSUE TITLE
Move gradle script contents to buildSrc

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#2038]
https://docs.gradle.org/current/userguide/authoring_maintainable_build_scripts.html#sec:avoid_imperative_logic_in_scripts
Gradle suggests moving logic into buildscripts.
In addition, with an independent buildSrc, we can possibly move enigma away from buildscript dependencies and only call it from forked javaexec (like how loom decompiles minecraft)

**Comment by i509VCB** [comment]
While I do agree yarn needs a definite buildscript cleanup (fabric api as well), but there seems to be a disagreement to this issue.

**Comment by zml2008** [comment]
It's not too tricky to avoid buildSrc -- and yarn is complex enough that you might want to do a standalone gradle plugin. What you could do that's somewhere in-between is start with a `build-logic` included build, and refactor to a plugin within that. Then, if issues come up with IDE support for that composite build or with build times for contributors, it'd be trivial to publish that to fabric's maven as a standalone plugin.

**Comment by liach** [comment]
We now have filament, so this is somewhat resolved.
