### ISSUE TITLE
Improper names from #200 prefix -> suffix move

### ISSUE THREAD

**Issue by Prospector** [asiekierka/MinecraftPOMF#205]
- [x] **ListMultiWidget** should be **MultiListWidget** (though now that I think about it... I don't know what is Multi about the list at all? Either way, ListMultiWidget is not right)
- [x] **SkeletonBaseEntity** should be **AbstractSkeletonEntity**
- [x] **EntityCat** should be **CatEntity**
- [ ] Entity datafixers...there's a few https://i.imgur.com/qsdgdZm.png

**Comment by LemmaEOF** [comment]
- [x] BlockState was incorrectly changed to StateBlock

**Comment by jamierocks** [comment]
As far as data fixers are concerned, I think they are fine.

1. They are following already specified names
2. In the absence of `entity`, etc packages, the prefix is justified

**Comment by Prospector** [comment]
hmm maybe. Not sure I agree though. I'd suggest make an entity package then.

**Comment by asiekierka** [comment]
I don't agree that the prefix is justified and am siding with @ProfessorProspector on this.

**Comment by liach** [comment]
`PlayerServerEntity` -> `ServerPlayerEntity`

**Comment by asiekierka** [comment]
Actually, I agree the prefix is justified. Looking into it myself now.

**Comment by SquidDev** [comment]
Possibly also

- [x] FactoryBlockEntity` -> `BlockEntityFactory`?

**Comment by SquidDev** [comment]
A few more:

 - [x] `PlacementContextItem` -> `ItemPlacementContext`
 - [x] `net.minecraft.server.command.OutputCommand` -> `CommandOutput`
 - [x] `net.minecraft.server.command.SourceCommand` -> `CommandSource`
 - [x] `EntityProviderBlock` -> `BlockEntityProvider`. Maybe `BlockEntityProviderBlock`, but probably not?

💯
