### ISSUE TITLE
Entity#playFlySound is misleading

### ISSUE THREAD

**Issue by enbrain** [asiekierka/MinecraftPOMF#2080]
The implementation `ChickenEntity#playFlySound` doesn't play sound at all. It looks more like an event listener.

**Comment by haykam821** [comment]
I assume this was because it used to just be for generic flapping which involved sound only until flapping caused a game event to be emitted. I would suggest the name `flap` in that case.

**Comment by liach** [comment]
should i include this in #2062 since it maps entity's game event emission and sound making during movement?

**Comment by liach** [comment]
Included it in #2062.
