### ISSUE TITLE
ItemStack.isSectionHidden is misleading

### ISSUE THREAD

**Issue by enbrain** [asiekierka/MinecraftPOMF#2095]
This method returns true if the section should appear in tooltip.

_Originally reported by Cozy Glow in https://discord.com/channels/507304429255393322/521545796882006027/813162440678309918_

**Comment by liach** [comment]
Is this like that hide flag check? i recall item stacks have an nbt bit mask to hide attributes from rendering

**Comment by haykam821** [comment]
Yes, it is used by the base `getTooltip` method using the stack's `HideFlags`, but since it is a static method, any flags can be passed.
