### ISSUE TITLE
ItemEntity#age shadows Entity#age

### ISSUE THREAD

**Issue by Sollace** [asiekierka/MinecraftPOMF#2110]
I think the name needs to be changed to something else, though I'm not sure exactly what. Calling it `age` is problematic because it shadows Entity#age and makes it private, making it difficult to reference the field from the parent class without a cast.

Also ItemEntity#age appears to function differently between client and server, meaning code that makes use of that field will cause weird desyncs and jumping of item entities, wheras Entity#age does not exhibit this behaviour.

ItemEntity#age also doesn't seem to properly reflect the way it's used. i.e. From implementing a similar entity for my own mod, I've been able to identify that it's used for two things:

1. It controls whether an item despawns, is merged, and can be picked up
2. It controls the rotation and vertical bobbing of the item on the client.

// ItemEntity.java
```
   @Environment(EnvType.CLIENT)
   public float method_27314/*getRotation*/(float tickDelta) {
      return ((float)this.getAge() + tickDelta) / 20F + this.hoverHeight;
   }
```
and
// ItemEntityRenderer.jsva
```
float verticalOffset = MathHelper.sin(((float)itemEntity.getAge() + tickDelta) / 10F + itemEntity.hoverHeight) * 0.1F + 0.1F;
```

I also suggest the following name changes:
`Item#method_27314` -> `Item#getRotation`
`Item#hoverHeight` -> `Item#uniqueOffset`

Maybe calling it `itemAge` would do as a possible workaround, since Mojang appears to have called it Age in the nbt? I would also add a javadoc to the field so people are aware of the above noted desync issue. I've seen it occur white a few times in the past, both in vanilla and with mods, where items jump sporadically so it may be a more common problem that anyone seems to have noticed.

Also before anyone asks: The reason i noticed this as an issue was because:
A: Way back in the forge days I was trying to make items float on clouds, and they would jitter and ghost through before jumping back.
B: More recently I was implementing logic to make feathers float to the ground realistically, and saw somewhat similar behaviour. It would jump occassionally when using ItemEntity#age but would move smoothly when using Entity#age, which is why I recommend the change.

**Comment by liach** [comment]
Seems this item.age is one of those fields that's only initially sent by packets and whose synchronization doesn't occur at all (expects client and server to increase that field consistently together). 

In addition, this age has a special handling logic when it has Short.MIN_VALUE, like the pick up delay.
