### ISSUE TITLE
PlayerListS2CPacket$class_5893 -> PlayerListS2CPacket$Action

### ISSUE THREAD

**Issue by PlanetTeamSpeakk** [asiekierka/MinecraftPOMF#2111]
As mentioned in the title, the class `PlayerListS2CPacket$class_5893` should be renamed to `PlayerListS2CPacket$Action` as it was named before. Aside from that, its enum constants should be renamed to `ADD_PLAYER`, `UPDATE_GAME_MODE`, `UPDATE_LATENCY`, `UPDATE_DISPLAY_NAME` and `REMOVE_PLAYER` respectively as these were their names before.  
The entire class got rewritten in the latest snapshot, so these mappings appear to have vanished, but the order of the enum constants and the class's function remain the same, so these mappings can just be brought over from the previous version.  

The other two methods that were added, `method_34150` and `method_34151`, can be renamed to something along the lines of `read` and `write` respectively.

**Comment by liach** [comment]
https://github.com/FabricMC/yarn/pull/2108/commits/127c504ff870967454b97460cbbf5debb4b66e2e#diff-78363a668e2c49984939861654da9c10d3e85f61a207fcb0b12fb471cf57885f maybe we can carry this one back on

**Comment by YanisBft** [comment]
Has been mapped
