### ISSUE TITLE
ServerPlayerEntity#cameraPosition and others are misleading

### ISSUE THREAD

**Issue by The-PPWD** [asiekierka/MinecraftPOMF#2178]
I believe that the naming of the following attributes/methods/parameters are misleading:

1. `ServerPlayerEntity#cameraPosition` (and associated getter and setter)
2. `ServerChunkManager#updateCameraPosition`
3. `ThreadedAnvilChunkStorage#updateCameraPosition`
4. `ThreadedAnvilChunkStorage$EntityTracker#updateCameraPosition` (both)
5. The parameter `useCameraPosition` in `ThreadedAnvilChunkStorage#getChebyshevDistance`

Here's my reasoning:

Starting with `ServerPlayerEntity#cameraPosition`, the only time this is updated is within `ThreadedAnvilChunkStorage#updateCameraPosition`, where it is set to the `ChunkSectionPos` that the `ServerPlayerEntity` is currently in. This position is stored so that when the `ServerPlayerEntity` changes `ChunkSectionPos`s, chunks within the range of this but not within the range of the `ServerPlayerEntity`'s current chunk position can be unloaded (this is my understanding). It isn't related to `ServerPlayerEntity#cameraEntity`, only the `ServerPlayerEntity` itself.

Next with `ServerChunkManager#updateCameraPosition`, `ThreadedAnvilChunkStorage#updateCameraPosition`, and both `ThreadedAnvilChunkStorage$EntityTracker#updateCameraPosition`s; the only argument given to these methods is a `ServerPlayerEntity`. Within the methods, the `ServerPlayerEntity#cameraEntity` is never queried. Instead, the `ServerPlayerEntity`'s chunk position is used (or in the case of `ThreadedAnvilChunkStorage#updateCameraPosition` where `ServerPlayerEntity#cameraPosition` is also used... see above regarding that attribute).

Finally with the `useCameraPosition` parameter in `ThreadedAnvilChunkStorage#getChebyshevDistance`, this boolean is used to determine if `ServerPlayerEntity#cameraPosition` should be used instead of the `ServerPlayerEntity`'s current chunk position. If `ServerPlayerEntity#cameraPosition` is renamed, this should be also.

I feel that names for these attributes/methods/parameters would be better if they were focused around the player instead of some "camera." While it could be thought that the camera referenced in these places is more of a "server camera" where chunk loading and unloading takes place, I still feel that the name conflicts with `ServerPlayerEntity#cameraEntity` as it reads that the position of this and `ServerPlayerEntity#cameraPosition` should be equivalent, but this is not the case.

I'd like to become more involved with the development of Yarn mappings, so I wouldn't mind submitting a PR with different names, but I'd rather get the community's feedback on this first. Also, if there are other attributes/methods/parameters within this part of the code that bear similar names and I missed, please let me know. Thanks!

**Comment by liach** [comment]
Very likely that matcher matched those in minecraft updates incorrectly.

**Comment by liach** [comment]
Hmm, it's from here https://github.com/FabricMC/yarn/pull/576/files#diff-8ce52bd08b24691684887c72b113c8da5e7901e5cd679ededc78c9914cea8926. Dunno what was really the original reason that it's named `cameraPosition`.

**Comment by liach** [comment]
Looking at it, this is like a general chunk section position for the player, used by entity tracking (updating) than for any specific "camera" purpose or alike.

**Comment by The-PPWD** [comment]
> Looking at it, this is like a general chunk section position for the player, used by entity tracking (updating) than for any specific "camera" purpose or alike.

Primarily, `ServerPlayerEntity#cameraPosition` is used for chunk unloading as I understand it. The entity tracking done in `ThreadedAnvilChunkStorage$EntityTracker#updateCameraPosition` only uses the chunk position from the `ServerPlayerEntity` itself. Still, you are correct in that it doesn't pertain to any camera.

**Comment by liach** [comment]
Ah, I think I find why it's called "camera". Because if the player has a camera entity, this `updateCameraPosition` is called every tick. This is more like a chunk section position from which the player and the client watches the entity.

**Comment by The-PPWD** [comment]
> Ah, I think I find why it's called "camera". Because if the player has a camera entity, this `updateCameraPosition` is called every tick. This is more like a chunk section position from which the player and the client watches the entity.

That would make sense as to why it was named that originally. However, it is also called in `ServerPlayerNetworkHandler` once in `onVehicleMove` and twice in `onPlayerMove` when the client sends the server one of these movement packets, so I still think that "camera" is a bad name for it to have as it is called even if `this.cameraEntity == this`.

As you've self-assigned this, are you planning on making a PR? Totally fine by me... I'm just wondering if I should ask for name feedback in Discord or wait for your PR. (I was hoping there'd be more name suggestions before I started work on it.) 🙂

**Comment by liach** [comment]
Yes. I am planning to call this `watchingPosition`, as the field and getter/setter in server player entity is related to chunk loading and unloading (called watching chunks from clients, I think). Meanwhile, the entity tracker ones will be renamed to `updateTrackedStatus` as they are a different system (2 systems only happened to be updated together from the same call path)
