### ISSUE TITLE
Move Ender Eye class to projectile package

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#2203]
Mojang has changed the hierarchy of `EyeOfEnderEntity` to extend projectile and its constructor calls the package private constructor of `ProjectileEntity` (see build logs), which wasn't the case when it was last visited in #1199. Feel free to open a pr to move it around.

**Comment by YanisBft** [comment]
Actually, projectile inheritance didn't change, and EyeOfEnderEntity is only extending Entity

**Comment by liach** [comment]
Hmm, why are they in one package cluster then? Weird https://github.com/FabricMC/yarn/runs/2220718904#step:5:232

**Comment by liach** [comment]
Oh, it calls `float ProjectileEntity.updateRotation(float, float)` which is protected. Weird story after all.
