### ISSUE TITLE
Work on javadoc for Brain, MemoryModule, Sensors and related.

### ISSUE THREAD

**Issue by i509VCB** [asiekierka/MinecraftPOMF#2210]
These are used quite heavily in Piglins, Villagers and Hoglins. Discord discussions showed these are not very easy to understand.

A high level overview of what I know about these off head, please check yourself while writing javadoc of course:

- `Brain`: A data container for memories which store a value.
- `MemoryModule`: A registered memory entry in a brain.
- `Sensor`: Used to get context for the brain from a world.

**Comment by liach** [comment]
I can work on them. I think I mapped a lot of brain stuff back when they were added.
