### ISSUE TITLE
The massive interface question

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#2240]
So with 21w13a, Mojang added a lot of unused annotated package-private interfaces to the jar. There is little clue on what they do; but as I see, class_6013, one of those interfaces, sit closely to class_6014, which is a thread factory. That might yield some insights. Also annotations 6319 and 6328 are related to them.

**Comment by apple502j** [comment]
Decompiled jars using official mapping. It seems like all packages got `package-info.class`. Of course they are not used in any other places. I'm not going to mention any more info in case it is against EULA.

**Comment by liach** [comment]
yeah, better not look at mojmap at all, since the inspiration it gives technically is under mojmap license and against cc0. i am thinking about using number suffixes and look at obf names (proguard name them alphabetically) for clues.

**Comment by Juuxel** [comment]
Yeah, analysing the order would be good like in #649 where I last saw it.

**Comment by liach** [comment]
@Juuxel Hmm, so those are indeed `package-info.class`es. Should we make a new package just to dump all of them :trollface: because otherwise they are still just useless

**Comment by Juuxel** [comment]
Yeah, that's what was determined on fabricord as well. #2249 should be a nice solution to this.

**Comment by liach** [comment]
fixed by #2249. nice!
