### ISSUE TITLE
Unpick doesn't transform 0 constants in some cases

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#2268]
Say there is a use case of an unpick:
```java
private static final int SOME_VALUE = 0;

public void user() {
  call(0);
}

public void call(int value) {
  if (value == 0) { /* do stuff */ }
}
```
If it's unpicked, unpick will only replace the 0 in the `user()`; it won't replace that in `call(int)`'s `value == 0` check.

Screenshot:
![image](https://user-images.githubusercontent.com/7806504/113480121-63f58600-9458-11eb-95b7-dbd09b615da7.png)

**Comment by liach** [comment]
@modmuss50 If you don't mind, consider allowing issues on unpick (and cfr) so we can track these bugs better.

**Comment by modmuss50** [comment]
I’ve enabled issues on unpick
