### ISSUE TITLE
Criterion `trigger`/`test` inconsistency

### ISSUE THREAD

**Issue by williambl** [asiekierka/MinecraftPOMF#2269]
`AbstractCriterion` has a method, `test(ServerPlayerEntity player, Predicate<T> tester)`.

This is protected, and is used by subclasses in methods which look like this (in `BeeNestDestroyedCriterion`):

```java
public void test(ServerPlayerEntity player, Block block, ItemStack stack, int beeCount) {
    this.test(player, (conditions) -> { return conditions.test(block, stack, beeCount); });
}
```

or (in `BrewedPotionCriterion`):

```java
public void trigger(ServerPlayerEntity player, Potion potion) {
   this.test(player, (conditions) -> { return conditions.matches(potion); });
}
```

all subclasses of `AbstractCriterion` have a method like this - some call it `trigger`, and some call it `test`. The name should be consistent, as all these methods do basically the same thing.

**Comment by liach** [comment]
What do you suggest then? Just `test` I guess?

`trigger` sounds more intuitive in case people use advancements as event callbacks. But it does both trigger and perform testing.

**Comment by liach** [comment]
Hmm, given advancements can have quite a bit side effects, I support `trigger`.
