### ISSUE TITLE
Rename Block/Item.Builder to .Properties or something else?

### ISSUE THREAD

**Issue by asiekierka** [asiekierka/MinecraftPOMF#232]
Please discuss.

**Comment by Prospector** [comment]
I vote for changing it..but not sure what to. Properties is the best suggestion I've heard so far. Don't like Config or Settings

**Comment by kashike** [comment]
:+1: 
`Properties` gets my vote.

**Comment by SquidDev** [comment]
While `Builder` isn't entirely accurate as it doesn't make a block, the class still has many of the traits of the builder pattern (mutable, fluent style, etc...). `Properties` somewhat implies something like `BlockState`: some immutable facts about the block.

`PropertyBuilder` would probably be the more accurate name, but that's pretty verbose.

**Comment by Prospector** [comment]
Property builder sounds even more like a BlockState thing to me

**Comment by Prospector** [comment]
New idea. Block.Settings. because it sets shit

**Comment by asiekierka** [comment]
Block.Properties is confusing wrt state properties, so that's a no.

I guess the best we have is Block.Settings, then?

**Comment by Prospector** [comment]
Classes that would be changed if people approve:

Block.Settings, Item.Settings, Biome.Settings

Meanwhile EntityType.Builder is an actual builder and other non-biome worldgen stuff use generics instead of settings/builder classes

**Comment by asiekierka** [comment]
Renamed to Settings.

**Comment by LemmaEOF** [comment]
proposal to re-open since Cory called them properties

**Comment by Prospector** [comment]
el tweet in question https://twitter.com/Cojomax99/status/1105859900675145728
