### ISSUE TITLE
Separator text fields suggest they are the only separators rather than the defaults

### ISSUE THREAD

**Issue by haykam821** [asiekierka/MinecraftPOMF#2353]
Despite separators being customizable as of Minecraft snapshot 21w15a, the naming of two `LiteralText` fields with the contents `, ` suggests that they are the only separators for text, rather than simply the default.

https://github.com/FabricMC/yarn/blob/a99ec0c4f06ce1a1309378b18685b8102800dccf/mappings/net/minecraft/text/Texts.mapping#L3-L4

**Comment by apple502j** [comment]
Yep my bad, I mapped it after 15a, thought adding `DEFAULT` makes it too long...
