### ISSUE TITLE
MinecraftClient createWorld method

### ISSUE THREAD

**Issue by PlanetTeamSpeakk** [asiekierka/MinecraftPOMF#2370]
The `MinecraftClient#method_29607(String, LevelInfo, DynamicRegistryManager$Impl, GeneratorOptions)` method should be renamed to `createWorld` as its use and code suggests it is used to create worlds.
This suspicion can easily be confirmed by looking at the `CreateWorldScreen#createLevel()` method which calls it in the last line.
You can also see this method is used to create worlds as the very last paremeter it passes to the `MinecraftClient#startIntegratedServer` method is `WorldLoadAction.CREATE`.

**Comment by liach** [comment]
Most likely it's some method added in some snapshot and people just didn't notice it out of hundreds of new methods within each new update
