### ISSUE TITLE
MatrixStack$Entry.modelMatrix -> positionMatrix

### ISSUE THREAD

**Issue by enbrain** [asiekierka/MinecraftPOMF#2377]
> multiplyModel is incorrect: MC uses a projection and a modelview matrix, both the "modelMatrix" and the normalMatrix affect the combined ModelView transformation step (local space to camera space). IMO all instances of "model(Matrix)" in MatrixStack should be replaced with position(Matrix) or similar - the matrix used to transform positions.

_Originally posted by @sfPlayer1 in https://github.com/FabricMC/yarn/issues/2364#issuecomment-830860126_

**Comment by liach** [comment]
Yeah, I think before the introduction of the normal matrix, we simply called the 4 by 4 old matrix "matrix".
