### ISSUE TITLE
*Tag -> Nbt*

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/MinecraftPOMF#241]
With the addition of the tag system in 1.13, an ambiguity has arisen between object tags and nbt tags. This ticket proposes a change for nbt classes to better respect their data type. Another proposed change in lieu of this migration is to switch to prefix-style naming, as it is more fluent and readable in this case.

 - `Tag` -> `Nbt`
 - `AbstractListTag` -> `AbstractNbtList`
   - `LongArrayTag` -> `NbtLongArray`
   - `ByteArrayTag` -> `NbtByteArray`
   - `IntArrayTag` -> `NbtIntArray`
   - `ListTag` -> `NbtList`
 - `AbstractNumberTag` -> `NbtAbstractNumber`
   - `ShortTag` -> `NbtShort`
   - `DoubleTag` -> `NbtDouble`
   - `FloatTag` -> `NbtFloat`
   - `ByteTag` -> `NbtByte`
   - `IntTag` -> `NbtInt`
   - `LongTag` -> `NbtLong`
 - `CompoundTag` -> `NbtCompound`
 - `StringTag` -> `NbtString`
 - `EndTag` -> `NbtEnd`

Furthermore, I propose the following changes as a way of simplifying the current naming pattern.
 - `NbtAbstractNumber` -> `NbtNumber`
 - ~~`NbtAbstractList` -> `NbtList`/`NbtCollection`~~
 - ~~`NbtList` -> `NbtArrayList`~~

The number type has no reason to expose its abstraction modifier, much like `Number` in Java. ~~`NbtAbstractList` is also used for collections that can represent themselves as serialized primitive arrays, so although this type extends from Java's `AbstractList`, it seems rather misleading to express it as one. `NbtCollection` would be the most appropriate name for this type imo. Following this proposal, `NbtList` can be expressed more explicitly as the internal list type it defers to, `ArrayList`.~~

**Comment by asiekierka** [comment]
* NbtAbstractList or AbstractNbtList?
* I'd say NbtArrayList is unnecessary, as generally we operate on NbtLists and not AbstractNbtLists. Code returns NbtList instances, not NbtAbstractList instances. Judging by the format's design, I disagree with this change.
* NbtAbstractNumber -> NbtNumber is, however, fine to me.

**Comment by ChloeDawn** [comment]
`AbstractNbtList` definitely sounds better. The ticket has been updated accordingly.

**Comment by Player3324** [comment]
I agree with Tag->Nbt, but not with the word order, we decided to abandon prefixes afaik.

As suggested something like NbtDouble implies a special kind of double for NBT, but really it is a kind of NBT that holds a standard double value. Similarly NbtAbstractList may be a list implemented using a nbt backend, not a list of named binary tags.

In general I'd rather substitute Tag->Nbt 1:1

**Comment by asiekierka** [comment]
Fair.

**Comment by ChloeDawn** [comment]
@sfPlayer1 	How do you propose we handle array classes, which can represent as Lists of NBT primitives, and also primitive arrays?

**Comment by Player3324** [comment]
ByteArrayNbt is the nbt for a byte[], ByteNbtArray would be ByteNbt[] (not that such a thing exists, it'd be List instead of Array)

**Comment by Prospector** [comment]
Yay we get to change all the toTag/fromTag method names /again/

**Comment by Prospector** [comment]
Did someone mention if there was a script or something to remap un-built code?

**Comment by asiekierka** [comment]
No script to remap un-built code yet, jamie is working on something.

Any additional thoughts? I'd like to push this today or tomorrow.

**Comment by jamierocks** [comment]
I don't like this change, but whatever I guess. :(

**Comment by asiekierka** [comment]
Neither do I per se, but Tag is used for, well, JSON-defined object tags.

**Comment by jamierocks** [comment]
I don't think this is going to cause issues in many places - I should think it's rare to be using the raw nbt/Tag and tag/Tag. I don't think it's worth changing - especially when these are known Mojang names.

**Comment by asiekierka** [comment]
Are they?

**Comment by jamierocks** [comment]
Yes - see anvil converter.

**Comment by jamierocks** [comment]
And when they released their nbt library, which come to think of it may have been anvil converter - I forget now.

I have all these sort of resources in a repository which makes it really quick to find stuff.

**Comment by Vexatos** [comment]
I'd still prefer spelling it `NBT` instead of `Nbt`, as it is not a single word.

**Comment by Player3324** [comment]
It's better to use lower case trailing characters for abbreviations to indicate the word boundary, allow for a distinct capitalized name and keep naming consistency.

E.g. SomeNbtSerializer is keeping NBT together or "static final Nbt NBT = ..." for a field.

This way you also know that NBT is a (constant) field, Nbt is a type and nbt is a variable or member without looking at anything else.

**Comment by Frontrider** [comment]
I would think that because object tags are gonna be pretty commonplace in our discussions when it comes to mod compatibility, it has to be called Nbt to avoid confusion.
Mojang also refers to it as NBT, and not Tag, so it just causes inconsistency.

Just don't double up on the "tag" like Voldemap.

**Comment by Prospector** [comment]
Does anyone have a better idea or can we get this done?

**Comment by Runemoro** [comment]
> Does anyone have a better idea

Yes, keep it `*Tag`. It's a known Mojang name.

**Comment by RedstoneParadox** [comment]
Except Tag is also used for json-defined object tags; this change is to avoid confusion.

**Comment by Runemoro** [comment]
@RedstoneParadox One is just `Tag`, the others are `<type>Tag`. They're also in different packages.

**Comment by jamierocks** [comment]
There are plenty of conflicting non-qualified names in Java, this is absurd - nbt's Tag is rarely used by mods, this really is a non-issue. These are known names.

**Comment by liach** [comment]
@ChloeDawn If you do perform a rename, I suggest names like `NumberNbt` instead of `NbtNumber` because these objects are nbt before they are numbers, strings, etc.

And we can get another round of vote here. Need to decide this for 1.15.

**Comment by ChloeDawn** [comment]
Yes, if this change is still desired I would also like to be using suffixes (FooBarNbt), as suggested here in December: https://github.com/FabricMC/yarn/issues/241#issuecomment-444508543

**Comment by Frontrider** [comment]
I think it would be desired. It makes the mapping easier to work with for newcomers. Two things that are not the same thing are called the same way.

**Comment by YanisBft** [comment]
Started to be old
