### ISSUE TITLE
Cannot open yarn for 21w20a

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#2411]
```
Caused by: java.lang.RuntimeException: duplicate class target name mappings detected
        at net.fabricmc.tinyremapper.TinyRemapper.checkClassMappings(TinyRemapper.java:556)
        at net.fabricmc.tinyremapper.TinyRemapper.refresh(TinyRemapper.java:828)
        at net.fabricmc.tinyremapper.TinyRemapper.apply(TinyRemapper.java:729)
        at net.fabricmc.tinyremapper.TinyRemapper.apply(TinyRemapper.java:718)
        at net.fabricmc.tinyremapper.TinyRemapper$apply$0.call(Unknown Source)
        at build_7n73lkngyeuw9te9mda88ivlj.mapJar(C:\code\yarn\build.gradle:1001)
        ... 155 more
```

@sfPlayer1 Mind check this out? Just running `gradle yarn` is sufficient to reproduce this.

Edit: This is more like a problem with the intermediary data.

**Comment by liach** [comment]
This is the same as https://paste.ee/p/7NSK3 which is from a fabric loader installation on 20a using the broken intermediary

**Comment by Chocohead** [comment]
In 21w19a
```
CLASS	ecy$1	net/minecraft/class_5519$1
FIELD	ecy$1	Lecy;	a	field_26910
CLASS	ecy$2	net/minecraft/class_5519$2
FIELD	ecy$2	Lecy;	a	field_26911
```
In 21w20a
```
CLASS	edi$1	net/minecraft/class_5519$1
FIELD	edi$1	Lduy;	a	field_33839
FIELD	edi$1	Ledl;	b	field_33840
FIELD	edi$1	Ledi;	c	field_33841
METHOD	edi$1	(Ledl;Ldpu;II)V	a	method_37084
CLASS	edi$2	net/minecraft/class_5519$2
FIELD	edi$2	Ledi;	a	field_26911
CLASS	edi$3	net/minecraft/class_5519$3
FIELD	edi$3	Lduy;	a	field_33842
FIELD	edi$3	Ledl;	b	field_33843
FIELD	edi$3	Ledi;	c	field_33844
METHOD	edi$3	(Ledl;Ldpu;II)V	a	method_37085
CLASS	edi$4	net/minecraft/class_5519$1
FIELD	edi$4	Ledi;	a	field_26910
```

**Comment by liach** [comment]
Hmm, is this a matcher bug where in a new version there is new anonymous classes inserted before the existing ones, the existing ones' members may fail to match? Possible, but the top priority is to fix intermediary (namely change that line to
```
CLASS	edi$4	net/minecraft/class_5519$4
```
) before we investigate matcher.

**Comment by Chocohead** [comment]
That fix is wrong, it should be
```
CLASS	edi$1	net/minecraft/class_5519$3
FIELD	edi$1	Lduy;	a	field_33839
FIELD	edi$1	Ledl;	b	field_33840
FIELD	edi$1	Ledi;	c	field_33841
METHOD	edi$1	(Ledl;Ldpu;II)V	a	method_37084
CLASS	edi$2	net/minecraft/class_5519$2
FIELD	edi$2	Ledi;	a	field_26911
CLASS	edi$3	net/minecraft/class_5519$4
FIELD	edi$3	Lduy;	a	field_33842
FIELD	edi$3	Ledl;	b	field_33843
FIELD	edi$3	Ledi;	c	field_33844
METHOD	edi$3	(Ledl;Ldpu;II)V	a	method_37085
CLASS	edi$4	net/minecraft/class_5519$1
FIELD	edi$4	Ledi;	a	field_26910
```
Based on the match files and field assignment order

**Comment by Chocohead** [comment]
Essentially the previously first anonymous class is now the fourth, with the second still second. Which means the new first is Intermediary's third and the third Intermediary's fourth

**Comment by liach** [comment]
Hmm, no? In intermediary all official classes like `abc$5`'s intermediary still end in the same number `$5`. Since these anon/local classes aren't exposed to apis, it won't really break mods

**Comment by Chocohead** [comment]
It's a little self defeating to match anonymous class members then not bother with the classes they're in (you might as well not bother at all). You are right though that either way this is mostly academic as it only impacts people who have Mixin'd the previous first anonymous class

**Comment by Player3324** [comment]
Should be fixed now
