### ISSUE TITLE
Determine the purpose of field_29709 and field_29735 when 1.17 is released

### ISSUE THREAD

**Issue by haykam821** [asiekierka/MinecraftPOMF#2448]
As per #2447, these two fields are suspected to be for whether the current version is a development version and the protocol version of the target release respectively.

**Comment by YanisBft** [comment]
As well, field_29738 and field_29739 are probably resource and data packs versions (their value are 7), but to determine which one is what we have to wait one of them to be increased

**Comment by IotaBread** [comment]
`field_29736` has been increased by one every snapshot since 21w14a, except between 21w16a and 21w17a, when it increased by 2. This leads me to think that this is something like the *internal* snapshot/development version number for the target release
