### ISSUE TITLE
HitResult -> ???

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/MinecraftPOMF#245]
I feel this should be changed from the Mojang name, as it is misleading when taking into consideration the hit type can be a `MISS`. A result of a hit that is a `MISS` makes no sense from a logical perspective. This class would be better just representing the data it contains, rather than what it *tried* to achieve. 

A possible name could be `RaytraceContext`, but I'll leave this up for proper discussion.

**Comment by asiekierka** [comment]
I think the lack of a result with a hit attempt is a perfectly fine result.
