### ISSUE TITLE
MathHelper -> Mth

### ISSUE THREAD

**Issue by asiekierka** [asiekierka/MinecraftPOMF#249]
Advantages:

* Mojang uses it.
* It rolls off the keyboard better.

Disadvantages:

* A bit confusing?

**Comment by Prospector** [comment]
definitely confusing. when it was first brought up I thought it was a joke... but hey. it's shorter so whatever

**Comment by quat1024** [comment]
`Math2`?

**Comment by kashike** [comment]
`Math2` goes along the lines of Guava's [`Collections2`](https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/Collections2.java).

**Comment by Lordmau5** [comment]
> `Math2`?

Math 2: Electric Boogaloo
___
As long as it'll have a JavaDoc saying that it's a Math Helper, and it's documented later on, then yes.

**Comment by Player3324** [comment]
Mth doesn't match the naming conventions and imo is not sufficiently descriptive.

I'd rather go with something like McMath to also imply that it's kind of like math, but not very accurate or universal since it sometimes uses low precision approximations.

**Comment by exaskye** [comment]
`FastMath`?

(~~`Mth` reads as "meth" to me~~)

**Comment by asiekierka** [comment]
~~I'm not sure if implying Mojang's math is faster is good idea~~

**Comment by exaskye** [comment]
`MathExceptSlightlyWorseButMaybeItsFasterIDunno`

**Comment by Prospector** [comment]
~~meanwhile implying their math is like meth may not be an issue~~

**Comment by liach** [comment]
`Maths`. In Great Britain and Australia, mathematics is shortened as "Maths" instead of "Math".

**Comment by RedstoneParadox** [comment]
~But the USA doesn't, so we don't either~

Maths seems a little close to Math, which is already a Class in the Java libraries, so people might get confused. Since its purpose seems to be related to in-world math, maybe something like BlockMath could work.

**Comment by liach** [comment]
Some methods like square root and partialtick and locatiom is used for rendering.

**Comment by Vexatos** [comment]
I prefer `MathHelper` over an unpronounceable classname.

**Comment by shadowfacts** [comment]
Agreed. `MathHelper` is fine, and it's used rarely enough by modders that typing it out is not an issue.

**Comment by Prospector** [comment]
Mth is good IMO. Good to use the Mojang names, *especially* on classes like this that aren't used too much

**Comment by Prospector** [comment]
I think we should get a decision made on this soon

**Comment by JamiesWhiteShirt** [comment]
I'll quote @tterrag on this:

> so the two sides of the war seem to be expressiveness vs conciseness. So isn't the middle ground Math2?
> 
> It's perfectly expressive
> Easy to autocomplete
> Matches an existing pattern

There is currently no class called Math2 in a default loom workspace. I think it's a very good fit.

**Comment by liach** [comment]
Guava has a lot of utility classes that have name clashes with Java Library classes. While older clashes are named like `Collections2`, the newer classes are prefixed with `More` instead, such as `Objects` -> `MoreObjects`. As a result, I still suggest `MoreMath` or `McMath` coined by player.

**Comment by shedaniel** [comment]
I like both of them but surely MathHelper is intuitive.

**Comment by 3TUSK** [comment]
If I have to say I would like to propose `MathTool` or `MathTools`. Sure `Mth` rolls off keyboard faster, but from a non-native speaker's POV... I am not sure if this doesn't create a mess.  
Personally I am fine with `Mth`.

**Comment by Prospector** [comment]
I'll point out this issue has 12 upvotes and only 4 down. Perhaps a PR should be considered.

**Comment by NeunEinser** [comment]
Since you commented that, it got 4 more downvotes and only one upvote. So I'd call this controversial at best.

I don't think we should sacrifice a good meaningful name to a bad Mojang Name.

**Comment by liach** [comment]
Given the current result 12 :+1: versus 13 :-1:, will keep the current `MathHelper` name. 
![image](https://user-images.githubusercontent.com/7806504/66447352-c57b9680-ea13-11e9-977a-25f6c4c3d239.png)

Comment if there is more concerns.
