### ISSUE TITLE
"net.minecraft.client.options does not exist"

### ISSUE THREAD

**Issue by matthew-cline** [asiekierka/MinecraftPOMF#2496]
Trying to port my mod to MC 1.17 I get the error `net.minecraft.client.options does not exist` when attempting to import `net.minecraft.client.options.KeyBinding`.  I know that that class hasn't been moved or renamed in 1.17 since my mod loads under 1.17, it just doesn't run properly.  I've tried deleting `$HOME/.gradle` and the project `.gradle`, then doing `gradle genSources`, but that didn't help any.

My setup:
* Gradle 7.0.2
* Oracle JDK 16.0.1
* My [`build.gradle`](https://github.com/FabricMC/yarn/files/6650578/build.gradle.txt)
* My [`gradle.properties`](https://github.com/FabricMC/yarn/files/6650579/gradle.properties.txt)
* My [`settings.gradle`](https://github.com/FabricMC/yarn/files/6650581/settings.gradle.txt)

(Sorry if this is the wrong part of Fabric to file the bug against)

**Comment by haykam821** [comment]
The package was made singular in #1921. You can use the `migrateMappings` task to update the mappings used in your code automatically, so all instances of `import net.minecraft.client.options.KeyBinding` would be changed to `import net.minecraft.client.option.KeyBinding`.

**Comment by EnderDragon114514** [comment]
so anyone knows why it was wrong when im importing net.minecraft.client?

**Comment by EnderDragon114514** [comment]
my gradle version: gradle 8.7

**Comment by carsupper665** [comment]
how to use migrateMappings 
i have same issues
```
error: package net.fabricmc.fabric.api.client.rendering.v1 does not exist
import net.fabricmc.fabric.api.client.rendering.v1.EntityRendererRegistry;
```
