### ISSUE TITLE
Capitalization of "tooltip"

### ISSUE THREAD

**Issue by apple502j** [asiekierka/MinecraftPOMF#2504]
Am I correct that "tooltip" is not capitalized in method names, and capitalized as toolTip in fields/params?

**Comment by Juuxel** [comment]
`toolTip` seems to be a (common?) typo. In modern usage outside of Yarn, the term is generally capitalised as `tooltip` (as seen on [Wikipedia](https://en.wikipedia.org/wiki/Tooltip) or the [Material Design docs](https://material.io/components/tooltips), for example).

I'd recommend using that as the capitalisation, unless someone disagrees. In any case, it should be consistently one of them without mixing `tooltip` and `toolTip`, especially in the same class.

**Comment by apple502j** [comment]
Seems like this is just a typo in realms package. Fixing it in #2505.
