### ISSUE TITLE
Sapling generator createXxxFeature -> getXxxFeature

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#2506]
~~1. `SaplingBlock` is not in the sapling subpackage. It probably should as it uses `SaplingGenerator` from that package.~~
2. `SaplingGenerator` has `createTreeFeature` and subclass `LargeTreeSaplingGenerator` has `createLargeTreeFeature`; however, these methods return a constant reference to a feature than creating a new configured feature on each call.

**Comment by liach** [comment]
Note: Thanks to FabricMC/fabric#1507 for spotting these issues

**Comment by Juuxel** [comment]
As for (1), I'm not so sure about moving since all the block classes are currently in the same package (even though there are packages like `block.piston` and `block.cauldron`). Moving them into that package would break the current "semi-convention".

(On the other hand, fixing (2) is just fine.)

**Comment by liach** [comment]
Oh right, didn't realize the sapling package only has generators but no block classes. My bad!
