### ISSUE TITLE
Using subpackages for block and item classes

### ISSUE THREAD

**Issue by haykam821** [asiekierka/MinecraftPOMF#2507]
Currently, the package tree for blocks and items looks similar to the following:

- `net.minecraft.block` package
  - **`CauldronBlock` class**
  - **`DispenserBlock` class**
  - `cauldron` subpackage
    - `CauldronBehavior` class
  - `dispenser` subpackage
    - `DispenserBehavior` class
    - `FallibleDispenserBehavior` class

Should we use subpackages for the corresponding block and item classes as well? For example:

- `net.minecraft.block` package
  - `cauldron` subpackage
    - `CauldronBehavior` class
    - **`CauldronBlock` class**
  - `dispenser` subpackage
    - `DispenserBehavior` class
    - `FallibleDispenserBehavior` class
    - **`DispenserBlock` class**

Relates to #2506

**Comment by liach** [comment]
I think we destroyed subpackages before due to package access issues. If you do such moves, changes in the "error: must be in the same package" status after rename would be a good evidence on the feasibility of these renames.

**Comment by liach** [comment]
Since the votes are mostly against such a move, I will close this one.
