### ISSUE TITLE
PortalUtil -> BlockLocator?

### ISSUE THREAD

**Issue by apple502j** [asiekierka/MinecraftPOMF#2510]
While the half of PortalUtil is used for nether portals, there is one method that is totally unrelated to portals; `method_34851`, which handles big dripleaf's growing mechanics. It is kinda similar to `moveWhile` method on the class.

`method_34851` returns the position of first block from position `arg2` in `arg4` direction that isn't `arg3`, if the block found is `arg5`. For example, you can call it like `method_34851(world, pos, Blocks.LADDER, Direction.UP, Blocks.AIR)` to locate the air above ladders.

The class is probably for general calculations to locate certain blocks, so I suggest renaming to something like BlockLocator, and moving this package to `net.minecraft.util.math`.

**Comment by liach** [comment]
This reminds me of my proposed rename of [`net.minecraft.entity.ai.Durations`](https://github.com/FabricMC/yarn/pull/2478/files#diff-cdc0a86fe0cba054785409af6a5aad952ad8570f89891ecda50b3820566f8c95) into [`net.minecraft.util.TimeHelper`](https://github.com/FabricMC/yarn/pull/2478/files#diff-338c7bdd5b79bb08f355bdea4cfb86f8995b51d22218a9791abb3a150c2b61ca).

On a side note, I believe the `world` package is more suitable for any utility using `World` instances than `util`, even though they may be math-heavy. If they have a more specific purpose, like for entity ai, they can go into other more-specific packages.
