### ISSUE TITLE
Fabric maven rejects uploading of javadoc jar

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#2519]
https://github.com/FabricMC/yarn/runs/2905106022#step:8:3576

> `Could not PUT '***/net/***/yarn/1.17.1-pre1+build.8/yarn-1.17.1-pre1+build.8-javadoc.jar'. Received status code 413 from server: Payload Too Large`

From the artifact at https://github.com/FabricMC/yarn/runs/2905105933, it appears the javadoc jar exceeds 40MB. Is that the upload limit for the fabric maven?

What should we do to address this? Shrink javadoc size, or allow uploading larger jars?

cc @modmuss50 for the recommended solution on this.

**Comment by modmuss50** [comment]
No, I’ve been messing with the server. The limit should be 100MB but I think it defaults to 10.

Will fix shortly.

**Comment by modmuss50** [comment]
Fixed.
