### ISSUE TITLE
update-base label is not properly removed

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#2534]
![image](https://user-images.githubusercontent.com/7806504/123835115-c7fbdf00-d8cd-11eb-91e1-23c09b0064cf.png)
(Note: I removed the label for one pr manually)

**Comment by modmuss50** [comment]
I have rewritten this action as its own standalone project that we can pull in. Its now in typescript so should make it much less of a guessing game. And it has full unit tests that should hopefully make it much easier to test without having to try it out on a real github repo. It has also been designed to be easily expended to support any other custom action task we may wish to have down the line.

I should have something ready to use fairly soon.

**Comment by modmuss50** [comment]
This has been fixed, see the new code repo here: https://github.com/FabricMC/fabric-action-scripts

This repo has been setup in such a way where we can easily add new custom logic, generating changelogs is something that I have been wanting to do for a while and this will enable that. If you have any suggestions (doesnt need to be yarn related) please feel free to open an issue/PR on that repo.
