### ISSUE TITLE
FollowTargetGoal is not accurate

### ISSUE THREAD

**Issue by Draylar** [asiekierka/MinecraftPOMF#2560]
**Class Description**
`FollowTargetGoal` is the standard tracking goal used for entity AI. It first locates a nearby entity matching a predicate (if any); if one is found, the goal assigns it as the target of the `FollowTargetGoal`'s owner.

**Issue**
My issue with this name is that the goal does not actually make the entity "follow" anything, and "follow" implies action. Because the goal is based around `findClosestTarget` and setting a `target` on the mob, I think `TrackClosestTargetGoal` might be more appropriate (or something to that degree). The parent class is already named `TrackTargetGoal`, so adding a "closest" (which is pretty much the only thing `FollowTargetGoal` does) makes sense.

**Other Thoughts**
I'm guessing the "Follow" part of the name was taken from the `getFollowRange` (`GENERIC_FOLLOW_RANGE` attribute) method called inside the goal, but that seems to do more with the size of the goal rather than what it actually does.

**Comment by liach** [comment]
After thinking, we should just rename `TrackTargetGoal` to `TargetGoal`, as that seems to the common superclass of goals that go into the target goal selector? And rename the rest of the classes accordingly.

**Comment by frqnny** [comment]
Well, that doesn't really describe what it does with the target? I like TrackTargetGoal, or we can do FindTargetGoal

**Comment by liach** [comment]
that target goal is generally surrounding the cleanups on an entity when the target is set/unset. It doesn't itself actively set targets, but more like providing a template, like an `AbstractList` to `ArrayList`. These target goals are also used mainly in the target goal selector of entities.

For `FollowTargetGoal`, now I think `ActiveTargetGoal` may be better as it actively searches for new targets as opposed to responding to owner attacks, etc.

**Comment by frqnny** [comment]
![image](https://user-images.githubusercontent.com/45723631/124408607-8f686500-dd14-11eb-8535-da17213fe777.png)
Hmm, here are all child classes if you want to see them.
