### ISSUE TITLE
RegistryOps & other dynamic registry 1.17 changes

### ISSUE THREAD

**Issue by frqnny** [asiekierka/MinecraftPOMF#2562]
Been thinking some time about this. 

![image](https://user-images.githubusercontent.com/45723631/124411211-1a982980-dd1a-11eb-946e-5b86f16e099a.png)

The above methods create a RegistryOps and load it from dynamic registry, so we could do `ofLoaded` 

Thoughts?

**Comment by liach** [comment]
Imo the whole class definitely needs a revisit. It's been quite a while since I last named them.
