### ISSUE TITLE
[<1.15] Blaze3D Does Not Yet Exist

### ISSUE THREAD

**Issue by halotroop2288** [asiekierka/MinecraftPOMF#2572]
I'm happy to create a pull request to fix this issue, but it seems it requires further discussion here after quickly being shut down by @BoogieMonster1O1 in https://github.com/Legacy-Fabric/yarn/issues/113. I have checked the existing threads and found that it hasn't been discussed before on Github.

The package `com.mojang.blaze3d` should not exist in (mainline) versions below `1.15`.
Instead, these classes should be found somewhere under `net.minecraft.client`.
@MenschenToaster's suggestion was `net.minecraft.client.gl`.

This only affects a small number of versions for Fabric, but it affects every single version of Legacy Fabric. So I hope that we can come to a consensus.

**Comment by YanisBft** [comment]
I'm fine with this as long as you can proof Blaze3D wasn't in the works in 1.14.

Though keep in mind that:
- If you open a PR, target 1.14.4 only, the other branches are not worth it
- The focus of yarn is usually to map the latest release and latest snapshot, so such issues/PRs should not become a habit (imo)

**Comment by halotroop2288** [comment]
> proof Blaze3D wasn't in the works in 1.14

While versions before 1.15 did share many similarities with the Blaze3D engine, a version officially (partially) implementing it was not released until [snapshot 19w34a](https://minecraft.fandom.com/wiki/Java_Edition_19w34a#Changes).
And it was followed by many snapshots introducing minor changes to the implementation which seemed to cause new bugs with every update until Minecraft 1.15 was finally released.
I remember it fondly as snapshot reviews on YouTube pointed out just how bad it was during the process.

**Comment by modmuss50** [comment]
We cannot build/release versions for 1.14.4 anymore without quite a bit of effort to get it going again. Anything older than 1.14.4 I dont really care for much.

In 1.14.4 there are classes in in b3d package, https://github.com/FabricMC/yarn/blob/1.14.4/mappings/com/mojang/blaze3d/platform/GlStateManager.mapping#L1

This is a none issue as far as I can see, and idk why it would be an issue in the first place.
