### ISSUE TITLE
AxolotlEntity.Variant method/field name inappropriacy

### ISSUE THREAD

**Issue by Dogeon188** [asiekierka/MinecraftPOMF#2574]
### Problem

So we have two public methods in `net.minecraft.entity.passive.AxolotlEntity.Variant`, namely `getRandomAll` and `getRandomNatural` as in the mapping, which is kind of an interface to another private method `getRandom`.
However, the names of these methods aren't quite reflective of what they actually do -- `getRandomAll` actually chooses one of the "`natural=true`" variants, while `getRandomNatural` returns the "unnatural" one.

### My Solution

I personally think we should rename those methods (also the arguments) as follows:
- `getRandomAll` -> `getRandomNatural`
- `getRandomNatural` -> `getRandomUnnatural`
- `boolean getRandom#includeUnnatural` -> `useNatural`

which will look something like this in the mapping file:
```mapping
CLASS class_5767 Variant
	...
	METHOD method_33235 getRandomNatural (Ljava/util/Random;)Lnet/minecraft/class_5762$class_5767;
		ARG 0 random
	METHOD method_33236 getRandom (Ljava/util/Random;Z)Lnet/minecraft/class_5762$class_5767;
		ARG 0 random
		ARG 1 useNatural
	METHOD method_33240 getRandomUnnatural (Ljava/util/Random;)Lnet/minecraft/class_5762$class_5767;
		ARG 0 random
```

### Some other thingies

This is my first submission to the yarn mapping project, hopefully I didn't make something wrong or so. Therefore I also chose to raise an issue rather than changing the mapping directly. Thank you for reading this anyways :)

**Comment by YanisBft** [comment]
You indeed right, the current names are wrong. The parameter should be named "natural" though, as "useNatural" suggests that when false, it can includes both natural and unnatural.
Feel free to open a PR!

**Comment by Dogeon188** [comment]
Thanks! I tried and made a PR, wish I didn't mess it up.
