### ISSUE TITLE
ActionResult.CONSUME_PARTIAL is not documented

### ISSUE THREAD

**Issue by haykam821** [asiekierka/MinecraftPOMF#2579]

**Comment by liach** [comment]
What, I didn't even know this thing exists! Definitely needs documentation on their usages and examples

**Comment by haykam821** [comment]
It's only used for one scenario in vanilla, so I'm a bit confused on how it would be used as well. It is considered to be accepted just like `ActionResult.SUCCESS` and `ActionResult.CONSUME`, though.

**Comment by liach** [comment]
Yeah, from the class we can see it probably simply doesn't swing hand and doesn't increase usage stats. Other side effects and use cases definitely worth exploring as well.
