### ISSUE TITLE
DynamicRegistryManager -> RegistryManager

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#2614]
Since the class has getter methods that first find a dynamic registry and then delegates back to the `Registry.REGISTRY` (universal registries), calling this `RegistryManager` should suffice; I think mojang may move more registries from universal registries to here as well. Most of our parameters and field names already call this a `registryManager`.

I propose to rename once the snapshot cycle starts; in addition, I will clean up the other codec stuff (which has caused a few problems as we see) in the rename.

**Comment by frqnny** [comment]
But it doesn’t handle all registries which RegistryManager suggests. Only Datapacks. “Dynamic” probably refers to datapacks since DatapackRegistryManager isn’t attractive.

**Comment by haykam821** [comment]
I disagree with this rename.

It acts as an overlay for built-in registries, making it a manager for the dynamic extensions to those registries. There are also registries that do not follow this system at all, like type registries. 

Having a clear distinction between these three classifications of registries is essential to understanding the registry system.

**Comment by liach** [comment]
> But it doesn’t handle all registries which RegistryManager suggests.

It has methods to obtain registries from the manager, looking up from the contained data first and then falling back to the static data. This covers all usages of the static registries as well.

> There are also registries that do not follow this system at all, like type registries

Hmm, what are type registries? Mind elaborate?

---

Guess we can decide when we see the trend of change when Mojang rolls out 1.18; if its registries start taking over the current code-based registries or exposed to more contexts to replace `Registry.REGISTRY.get` calls, then I think this rename would still be meaningful.

**Comment by haykam821** [comment]
There are many registries that don't make sense to have dynamic registries, like trunk placer types and block state provider types. These are usually used as parts of other codecs used for dynamic registries, but by themselves don't make sense to be dynamic.
