### ISSUE TITLE
method_7672 of class_1735 has protected access but is accessed in a public way by class_1703

### ISSUE THREAD

**Issue by ghost** [asiekierka/MinecraftPOMF#2622]
line 444 (procyon) of class_1703 net/minecraft/screen/ScreenHandler calls protected method method_7672 onTake of class_1735 net/minecraft/screen/slot/Slot. ScreenHandler doesnt have access to the method (onTake) as it it protected. the method needs to be updated to be public.

**Comment by liach** [comment]
See https://github.com/FabricMC/yarn/issues/2057#issuecomment-808949368

The yarn mappings intentionally ignores a few of such access issues (for the better organization of classes into packages). If you are running in dev, these are always patched public by the fabric loader fyi. In intermediary and usual installed games, they are just organized similar to in obf, so the issues are not there either.

The list of all such clashes are still reported for referential purposes. See: https://github.com/FabricMC/yarn/runs/3219557940#step:6:197

If you do want to run an application with yarn named minecraft, use the fabric loader for now.
