### ISSUE TITLE
Javadoc should be built using an official JDK 17 distribution

### ISSUE THREAD

**Issue by haykam821** [asiekierka/MinecraftPOMF#2670]
In #2445, GitHub Actions workflows were changed to download a distribution of JDK 17 that was uploaded to the FabricMC maven:

https://github.com/FabricMC/yarn/blob/a0592ba0ce2a0d80153818a489a0776ea4d87ce6/.github/workflows/build.yml#L15-L17

Since [JDK 17 is releasing on September 14](https://openjdk.java.net/projects/jdk/17/), it would be better to use an official distribution again.

**Comment by modmuss50** [comment]
I think this is just waiting on gradle to run on J17, im not sure if that is the case. There already appears to be openjdk docker images for 17 (and 18!) so thats not an issue.

**Comment by haykam821** [comment]
Yep. The Gradle issue is gradle/gradle#16857 for tracking.
