### ISSUE TITLE
Disallow linking to the Minecraft Wiki

### ISSUE THREAD

**Issue by haykam821** [asiekierka/MinecraftPOMF#2672]
The Minecraft Wiki is linked to twice within documentation in Yarn:

https://github.com/FabricMC/yarn/blob/a0592ba0ce2a0d80153818a489a0776ea4d87ce6/mappings/net/minecraft/block/Block.mapping#L16

https://github.com/FabricMC/yarn/blob/a0592ba0ce2a0d80153818a489a0776ea4d87ce6/mappings/net/minecraft/world/World.mapping#L84

These references should be removed, and contributor documentation should explicitly disallow linking or referencing the Minecraft Wiki for names or documentation.

**Comment by liach** [comment]
Hmm, agree. Especially given that now the wiki is in the hand of fandom, which is known to be greedy, we don't want to get into troubles here.
