### ISSUE TITLE
LazyCachedSupplier -> Lazy

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/MinecraftPOMF#268]
- [ ] `net.minecraft.util.LazyCachedSupplier` -> `net.minecraft.util.Lazy`

Example declaration:
```java
private final Lazy<String> foo = new Lazy<>(this::formatName);
```
- Cleaner declaration/reference syntax
- More readable type (e.g Lazy String)

If there were to be any concerns on the semantics of the class, it could be documented (once Yarn supports JavaDocs that is).

**Comment by liach** [comment]
Yes. This `Lazy` sounds exactly like `Optional`, and its usage is so similar to it (an object wrapper)
