### ISSUE TITLE
Record methods have mojang name inside; do we use them?

### ISSUE THREAD

**Issue by apple502j** [asiekierka/MinecraftPOMF#2681]
`class_6521` (a class in JFR recording, exp yarn name `net/minecraft/util/profiling/jfr/sample/ChunkGenerationSample`) has `toString`/`hashCode`/`equals` with a `MethodHandle` whose argument contains `propA;propB;propC;propD;propE;propF` (prop being mojang names). Can/should/must we keep them?

My understanding is that it is okay to reference mojang names if it's in the actual code, which is the case. However, some contain things like "level" which is referred to as "world", etc. Also, I am not sure if the names are something we can mess with (i.e. not crash loader).

**Comment by ghost** [comment]
My understanding that yarn has always allowed you to submit mappings found in the minecraft jar itself (or maybe this is only strings which could reasonibly be outputted during runtime?), however prefer better names if you can think of any.

**Comment by liach** [comment]
This is as "mojang name" as those exposed enum names. Since we are using enum names straight, I don't oppose using these names (except when there are more clarifying/straightforward names)

**Comment by liach** [comment]
Moving to #2708 which implements name inference for records.
