### ISSUE TITLE
mappings accidentally reverted in exp import

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#2686]
some mappings, particularly ones from 1.17.1 that's not merged into exp are accidentally reverted in the port, such as target selection goal renames.

in addition, a few exposed single abstract methods are renamed, dunno if those should be kept or not.

**Comment by Player3324** [comment]
I gave exp priority since it was the newer branch, the bits that are wrong in this regard need to be ported manually.
