### ISSUE TITLE
publish script shouldn't try to run on forks

### ISSUE THREAD

**Issue by apple502j** [asiekierka/MinecraftPOMF#2696]
This causes "check failure" to appear on commits pushed on fork branches.

![image](https://user-images.githubusercontent.com/33279053/133877913-7e850681-f902-4f56-9565-45f5050ffb63.png)

https://github.com/FabricMC/yarn/blob/21w37a/.github/workflows/publish.yml should be fixed by adding `if: github.repository_owner == 'FabricMC'` to L7.

**Comment by liach** [comment]
interesting, does this conditional statement exist? i couldnht find it on github's docs after all

**Comment by apple502j** [comment]
See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif
