### ISSUE TITLE
`class_6561`'s record components not handled

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#2700]
In 21w37a, in `class_6561` (in `PaletteContainer`, a nested class holding runtime data for palette container), only 1 record component is handled as `comp_74`, while the other two stay as `field_34564` and `field_34565`. What might be the cause of this discrepancy?

@sfPlayer1 for investigation.

**Comment by Player3324** [comment]
Well the java language spec says " A component field is private, final, and non-static. ", but apparently that isn't the case after proguard had a go either.. I'll look into adjusting for this.

**Comment by liach** [comment]
Hmm, those fields are package private somehow. Maybe proguard stripped those due to it seeing being used in the same nest? Though record component fields can be used directly for classes in the same nest due to the java 13 new access control, maybe proguard saw that and did some old-school transformation?

**Comment by Player3324** [comment]
They both have accesses from the outer class

**Comment by liach** [comment]
> They both have accesses from the outer class

Yeah, nowadays you can access them in another nested class/local class/anonymous class in the same outer class as well, like in https://github.com/FabricMC/Enigma/pull/431/files#diff-ecc810a511435d12e2389701d810d37fd95e75b55969cca0356fa76c535076b2R226 I call another local record's components by field access. I wonder what we need to do to better replicate a mojang proguard obfuscation environment so we can find out how it works.

**Comment by liach** [comment]
Now matcher has this patch, should be good to go.
