### ISSUE TITLE
ChestAnimationProgress is in client/block despite being implemented in ChestBlockEntity

### ISSUE THREAD

**Issue by apple502j** [asiekierka/MinecraftPOMF#2723]

**Comment by liach** [comment]
Is it still a client-only interface? It was and its usage was pretty much just for client compatibility the last time I visited this class.

**Comment by NinjaPhenix** [comment]
In 1.17.1 it is common, 21w39a however it is back to being in client side only.

**Comment by ghost** [comment]
Both `ChestLidAnimator` and `ChestAnimationProgress` are in common in 1.17.1 and 21w39a however they do serve a client only role.

**Comment by ghost** [comment]
Note, my previous comment regarding 1.18 might be wrong since the loom version I'm using (my own fork) seems to apply the client annotation to all classes...
