### ISSUE TITLE
VertexBuffer.texture(int,int) probably named wrong

### ISSUE THREAD

**Issue by McJty** [asiekierka/MinecraftPOMF#274]
The VertexBuffer.texture(int,int) corresponds to a lightmap coordinate. While that technically still is a UV coordinate the name is a bit confusing as it is meant to be used with a lightmap

**Comment by LemmaEOF** [comment]
Yep. It should probably be something like `.lightmap(int, int)`, since `.texture(double, double)` does something completely different. Same-name methods should do similar things, but since these don't, they should have different names.

**Comment by dblsaiko** [comment]
Both of these do the same thing, write two values into the buffer. There's actually no difference between them in the code except for the parameter types and var names

**Comment by Chocohead** [comment]
As they're order dependent to what they're being used for, even if they end up doing the same thing, surely it makes sense to name them differently so people are more likely to put things the right way around? Rather than guessing that it's UV then lightmap.

**Comment by LemmaEOF** [comment]
That'd actually come from the `VertexFormat`, which is currently missing a mapping for the lightmap.

**Comment by dblsaiko** [comment]
Why should they be named differently to each other? They both write texture coordinates, the meaning of those coordinates is determined by the vertex format

**Comment by JamiesWhiteShirt** [comment]
Yes, this is actually a misunderstanding of how BufferBuilder (previously called VertexBuffer) works and likely a result of voldemapping habits. `texture(int, int)` and `texture(double, double)` both put two values to the buffer depending on the current vertex format element. The only difference is the type of input and the casting behavior. They can be used interchangably.
