### ISSUE TITLE
Is "tacs" really an acceptable abbriation?

### ISSUE THREAD

**Issue by apple502j** [asiekierka/MinecraftPOMF#2759]
`ThreadedAnvilChunkStorage` is long, sure, but should we abbreviate it to "tacs"?

See #2756 where someone else mapped it "tacs" and I mapped "threadedAnvilChunkStorage".

Some suggestions:

1. Use "tacs"
2. Use "threadedAnvilChunkStorage"
3. Use "chunkStorage"
4. Use "storage"

**Comment by haykam821** [comment]
I think `chunkStorage` or `threadedAnvilChunkStorage` is fine to use.

**Comment by liach** [comment]
I recall `ThreadedAnvilChunkStorage` was some name leaked in mojang string. That class indeed is not anvil, and being threaded isn't its definitive feature either. However, it is pretty sure to be some sort of chunk storage (chunk loader), so I would support `chunkStorage` or `storage` (in case there is no name conflicts)

**Comment by enbrain** [comment]
Fixed by #2852.
