### ISSUE TITLE
RE: Mapping a lot of block related classes #267

### ISSUE THREAD

**Issue by modmuss50** [asiekierka/MinecraftPOMF#276]
- [ ] `BlockState.ShapeCache` might not be correct

- [ ] `BlockState.getCullShape` needs looking at

- [ ] `SystemUtil.toMap` needs looking at `toMapCollector `or `entriesToMapCollector` ? Could be ok as is

**Comment by dblsaiko** [comment]
Also `VerticalEntityPosition` needs a better name, imo.

**Comment by liach** [comment]
I can no longer find `toMap` method in SystemUtil; and the shape stuff has been checked fairly thoroughly in #839.
