### ISSUE TITLE
SkyProperties -> DimensionEffects

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#2766]
Following some confusion about this on Fabricord and with a Fabric API PR, this should be renamed to `DimensionEffects`.

- It's stored in the `effects` property of the dimension type codec.
- It doesn't only apply to the sky and includes other things like fog, cloud height and lighting.
- `DimensionEffects` is to `DimensionType` what `BiomeEffects` is to `Biome`.

In addition to this, `DimensionType.skyProperties` should be renamed to `effects` along with any related getters to match the better class name and the serialised name.

**Comment by liach** [comment]
Looking at the commit history, this is probably a match between good and misleading when they performed a refactor (we still have such ambiguous names, like `AreaHelper` that was once nested in `NetherPortalBlock`)
