### ISSUE TITLE
Floors and ceilings are not walls

### ISSUE THREAD

**Issue by haykam821** [asiekierka/MinecraftPOMF#2828]
Currently, the `WallMountLocation` enum and `Properties.WALL_MOUNT_LOCATION` field are used for the `face` property, which has three values: `floor`, `wall`, and `ceiling`.

It is quite clear that floors and ceilings are not walls, but the mappings seem to think this:

https://github.com/FabricMC/yarn/blob/e0df689e614bd476818c601bd04307194f310159/mappings/net/minecraft/state/property/Properties.mapping#L170-L171

Would it be better to simply rename both mappings to 'face'? Is another name more descriptive and thus better?

**Comment by zOnlyKroks** [comment]
I personally, would rename it to face. seems a lot clearer to me atleast.

**Comment by zOnlyKroks** [comment]
I would rename it to block. only connects to blocks or other walls. Even though face could also be good.
