### ISSUE TITLE
Use --ignore-source-errors option in javadoc

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#2873]
Per https://bugs.openjdk.java.net/browse/JDK-8268582 javadoc has such an option. Using this option to generate partial documentation is preferable to having blank content when Minecraft undergoes a big update and the fake source generated doesn't comply to the minimum compilation standards required by javadoc tool, such as package-private access, etc.

**Comment by apple502j** [comment]
Note that 22w06a javadoc does not build due to the issue.

**Comment by liach** [comment]
yeah, see https://github.com/FabricMC/MappingPoet/issues/27
