### ISSUE TITLE
Rename `NbtNull` to `NbtEnd`

### ISSUE THREAD

**Issue by Technici4n** [asiekierka/MinecraftPOMF#2882]
I've tried using it as a `null` value multiple times, but it will actually end the serialization in many cases. Renaming it will ensure that mods won't use it as a null value by mistake, like they could with JSON. See also AztechMC/Modern-Industrialization#161.

**Comment by LambdAurora** [comment]
`NbtEnd` is misleading, see:
#2090 
https://github.com/FabricMC/yarn/pull/2090#discussion_r588860544

If you're doing low-level programming it is common to use null as a character to end the treatment of data, but it's not only treated as an end.
