### ISSUE TITLE
`ReadOnlyChunk` is no longer always read only

### ISSUE THREAD

**Issue by Shnupbups** [asiekierka/MinecraftPOMF#2886]
As of the recent 1.18 pre releases, `ReadOnlyChunk` (`class_2821`) now has a boolean, which if true makes it read-write. Therefore, the name `ReadOnlyChunk` is no longer accurate and a new name needs to be thought of.

**Comment by haykam821** [comment]
`LockableChunk` seems good.

**Comment by liach** [comment]
Both `ReadOnlyChunk` and `LockableChunk` is problematic: This type is explicitly used in `ChunkHolder.setCompletedChunk`. The boolean field is final, and is `true` for regeneration and `false` for regular world gen; this field enables slightly more capabilities but is still more restricted than a regular chunk.

**Comment by Shnupbups** [comment]
I named it `WrappedChunk`, as that seems to more represent what it is.

**Comment by Shnupbups** [comment]
Changed to `WrapperProtoChunk` as it, itself, is not the wrapped chunk but the wrapper around it, and it's also a `ProtoChunk`.

Also `WrappedChunk.getWrappedChunk()` is dumb lol
