### ISSUE TITLE
Entity intersection related methods are probably incorrect

### ISSUE THREAD

**Issue by apple502j** [asiekierka/MinecraftPOMF#2901]
It looks from impl and code usage (e.g. mob spawning related methods) that methods in EntityView, CollisionView etc that return whether an entity collides/intersects with other entities (e.g. `EntityView#intersectsEntities`) returns `false` when it intersects. Can anyone confirm this?

**Comment by enbrain** [comment]
You are right. I confirmed it with the following code:

```java
HudRenderCallback.EVENT.register((matrices, tickDelta) -> {
    MinecraftClient client = MinecraftClient.getInstance();
    boolean result = client.world.intersectsEntities(null, VoxelShapes.cuboid(0, 0, 0, 1, 1, 1));
    client.textRenderer.draw(matrices, client.player.getPos().toString(), 10, 10, 0xFFFFFFFF);
    client.textRenderer.draw(matrices, String.valueOf(result), 10, 20, 0xFFFFFFFF);
});
```

Result:

https://user-images.githubusercontent.com/69905075/144606974-4014b74a-0da7-42fd-99cf-68b21f667bb4.mp4
