### ISSUE TITLE
The AbstractBlock#hasSolidTopSurface method can be used for other sides

### ISSUE THREAD

**Issue by haykam821** [asiekierka/MinecraftPOMF#2913]
Although the `hasSolidTopSurface(BlockView, BlockPos, Entity)` method uses the top face of a block, the `hasSolidTopSurface(BlockView, BlockPos, Entity, Direction)` method can use any other side depending on the direction parameter.

**Comment by NoahvdAa** [comment]
Looks like this issue wasn't auto closed when #2981 was merged (probably because I didn't mention a keyword like "fixed").
