### ISSUE TITLE
Entity.inanimate field named incorrectly

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#2920]
The `Entity.inanimate` (`field_23807`) is named incorrectly; it means if an entity should be considered for shape intersection calculation, which is its exclusive usage. Discovered while reviewing #2903.

**Comment by apple502j** [comment]
The first name I came up with was `collidable`. But there is a problem.

In Minecraft entities there are 2 types of collision - the general collision (what this `inanimate` is doing; basically any `LivingEntity`s, boats or minecarts - which can be "nudged"), and the "strict collision" that ignores the gravity (e.g. you can stand on a shulker or a boat, but you cannot stand on a cow or a creeper) which is what `Entity#isCollidable` is doing. These two are different and should have different naming.

**Comment by apple502j** [comment]
Is "intersectable" a word?

**Comment by liach** [comment]
Think we can call that and just document it (mainly used in block placement like frost walker and mob spawning to prevent clashes)
