### ISSUE TITLE
NarratorOptionsScreen -> ?

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#2933]
It's also used for options screens that have nothing to do with the narrator: chat and online options. This class just happens to handle the narrator button's label **if it's present**.

My main rename suggestion is `ButtonListOptionsScreen`. This could also be something like `SimpleOptionsScreen`, since it seems to just be used for the simplest screens with a button list (for example, video options don't use this), so I'm a bit unsure what to call it.

**Comment by apple502j** [comment]
`SimpleOptionsScreen` sounds good.
