### ISSUE TITLE
Colorful Mapping Proposals

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/MinecraftPOMF#297]
- [ ] `ItemColorMap` -> `ItemColors`
- [ ] `ItemColorMapper` -> `ItemColorProvider`
- [ ] `BlockColorMap` -> `BlockColors`
- [ ] `BlockColorMapper` -> `BlockColorProvider`
- [ ] `method_1704` -> `getColor`
- [ ] `method_1708` -> `register`

**Comment by asiekierka** [comment]
+1 to all six

**Comment by EliteMasterEric** [comment]
Like this change. The change from Mapper to Provider makes the purpose more clear.
