### ISSUE TITLE
Particle spawning method

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#300]
`World.method_8494` spawns particles.

Edit: There's already `World.addParticle`. Unlike it, `8494` sets a boolean flag to true.

**Comment by SquidDev** [comment]
If you've time, we really recommend you create a PR for the changes you propose. The README details how to get everything set up, and it's surprisingly easy to start mapping!

**Comment by Juuxel** [comment]
Hm... I think it's a problem that I know the Voldemap name for it?

**Comment by asiekierka** [comment]
Yes. Lord Voldemap is watching.
