### ISSUE TITLE
Top-level registry package

### ISSUE THREAD

**Issue by haykam821** [asiekierka/MinecraftPOMF#3002]
Since tags are greatly tied to registries now, it would be ideal to restructure registries to have a more promenient top-level package, like tags already do.

Here's a potential structure:

- `net.minecraft.registry`
  - The `Registry` class and its subclasses
  -  `.tag`
  - `.entry`
- `net.minecraft.world`
  - The `DynamicRegistryManager` class

**Comment by liach** [comment]
imo dynamic registry manager would go to server.registry since it's loaded server-wide

**Comment by haykam821** [comment]
The dynamic registry manager exists on the client as a destination for synced registries. With this in mind, it could also go into `net.minecraft.network`.

**Comment by liach** [comment]
hmm, then imo just putting it in the registry or its subpackages are fine. refer to where we place universal command stuff
