### ISSUE TITLE
`TagKey#intern` (`method_40092`) -> `of`

### ISSUE THREAD

**Issue by enbrain** [asiekierka/MinecraftPOMF#3014]
Reasons:

* `method_40092` is a replacement for the `@Deprecated` constructor. `intern` doesn't convey that.
* `Interner#intern` getting called in `method_40092` is an implementation detail for optimization.

I'd avoid naming it `create` because it doesn't always return a new instance. Related to https://github.com/FabricMC/yarn/issues/2492#issuecomment-860154932.

**Comment by haykam821** [comment]
Keep in mind that the `RegistryKey` class also caches instances and uses `of` methods. As such, this refactor seems good to me.
