### ISSUE TITLE
ServerResourceManager -> ?

### ISSUE THREAD

**Issue by apple502j** [asiekierka/MinecraftPOMF#3016]
`ServerResourceManager` is a bad name, since it's not a `ResourceManager` and it doesn't manage resources by itself. Plus, new records in 06a have both `LifecycledResourceManager` and `ServerResourceManager` in their items, which is confusing.

~~I suggest `DataPackManager` as the new name, and will make a PR to address the name (along with 6904, potentially.)~~

Hmm, `DataPackManager` isn't good either (`ResourcePackManager` also exists) - better names? or can we call it `DataPackManager`?

**Comment by apple502j** [comment]
`DataPackContents` maybe?

**Comment by liach** [comment]
DataPackContents sounds great to me.
