### ISSUE TITLE
NoiseChunkGenerator constructor incorrect parameter names

### ISSUE THREAD

**Issue by Kalaxian** [asiekierka/MinecraftPOMF#3040]
the constructors are really long, but the first params of both are
`Registry<StructureSet> noiseRegistry, Registry<DoublePerlinNoiseSampler.NoiseParameters> structuresRegistry`
and more "evidence" is from the body of the constructor
`this.noiseRegistry = structuresRegistry;`

**Comment by enbrain** [comment]
Fixed by #3056 and #3067.
