### ISSUE TITLE
HorseBaseEntity -> AbstractHorseEntity

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#3082]
Some legacy names that were not fully converted when we convert away from prefix naming.

**Comment by haykam821** [comment]
Would `AbstractHorseEntity` be better? Also, `HorseBaseEntityRenderer` must be renamed accordingly.

**Comment by apple502j** [comment]
`AbstractHorseEntity` sounds good (aside from the "is llama a horse, and is carpet a horse armor" question; my answer would be "who cares")

**Comment by haykam821** [comment]
Llamas are already donkeys when going off of superclasses; the `LlamaEntity` class extends the `AbstractDonkeyEntity` class.

**Comment by liach** [comment]
true, AbstractHorseEntity is a better choice that fits with the skeletons and piglins.
