### ISSUE TITLE
generate mappings for 22w16a

### ISSUE THREAD

**Issue by Bixilon** [asiekierka/MinecraftPOMF#3111]
Hi there,

I wrote a script that runs for every minecraf version and generates data from it. 22w16a got mapped with fe3a599b38f3306ee2826f528c0fcf3f416209b0, but the build failed and got fixed for 22w16b in e62e025019389979e7520f9724d78d35d2e6cb8d.

My script is now reporting erros, it is missing the mappings for that version. Could you maybe manually generate it and publish it to your servers? It is not about me being to lazy to ignore that version, I can easily exclude specific versions (https://gitlab.bixilon.de/bixilon/pixlyzer/-/blob/yarn/wrapper/PixLyzer.py#L16), but imho it should be generated for completeness.

(And yes I know, that version is broken or whatver, thats the reason for the hotfix and I should not  use it, but I am aware of that)

Thanks

**Comment by modmuss50** [comment]
Yes, I’ll get a build our for 16a shortly for completeness sake. 👍

**Comment by modmuss50** [comment]
And done! https://github.com/FabricMC/yarn/commit/e78b15e6d7b3d1d8a11bd03d51435b7516b7549c

**Comment by Bixilon** [comment]
Thanks!
