### ISSUE TITLE
Fix Text#asString() mapping

### ISSUE THREAD

**Issue by PlanetTeamSpeakk** [asiekierka/MinecraftPOMF#3115]
With 22w16b, the mapping for Text#asString() was lost and has now returned to its intermediary name (`method_10851`) even though its intermediary name has remained the same.

**Comment by apple502j** [comment]
It should've received a new intermediary since its function changed.

**Comment by PlanetTeamSpeakk** [comment]
I did just notice that it returns something else now, it no longer returns a string, but it definitely still has the same intermediary mapping.

Seems like it now returns the object the MutableText was created with. (E.g. LiteralText or TranslatableText)

**Comment by haykam821** [comment]
This method is likely going to be named `getContent`.

**Comment by enbrain** [comment]
#3105 named it `getContent` and has been merged.
