### ISSUE TITLE
AbstractRandom -> Random

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#3125]
Nowadays, seems mojang moved pretty much all use cases of `java.util.Random` to the current `AbstractRandom` interface. I hence recommend simply renaming it to `Random`.

The JDK has some nice documentation for understanding random: https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/util/random/RandomGenerator.SplittableGenerator.html

**Comment by liach** [comment]
@apple502j How do you think since you initially mapped these randoms? I feel we should rename the base class to `Random` and have a few other simplifications, as it's now the norm for the whole game codebase. In addition, for other terminologies, we can probably look at JDK, such as rename `derive` to `split` as in that javadoc link above.

**Comment by apple502j** [comment]
@liach That sounds fine - still snapshot phase, we can make this change I think.

**Comment by haykam821** [comment]
This issue was fixed by #3140.
