### ISSUE TITLE
`Program` and `Shader` are confusing

### ISSUE THREAD

**Issue by enbrain** [asiekierka/MinecraftPOMF#3128]
Currently, `class_281` is named `net.minecraft.client.gl.Program` and `class_5944` is named `net.minecraft.client.render.Shader`.

`class_281` is actually a single shader stage in the graphics pipeline. In other words, it's a shader object that can be created by `glCreateShader`. Calling it "program" is only correct in the sense that it's a program that runs on a GPU. `class_5944` is actually a shader program (with some uniform variables). In other words, it's a program object that can be created by `glCreateProgram`. Abbreviating "shader program" as "shader" is plainly wrong.

The fact that complicates this stuff is that Minecraft calls `class_5944` "shader" in strings (and this is probably why yarn contributors decided to call it "shader" as well). The most notable one is the `RenderSystem#getShader` method, which is not obfuscated by Mojang. For that reason, simply swapping `Shader` and `Program` will introduce another confusion.

I propose renaming `Shader` to `ProgramObject` and renaming `Program` to `ShaderObject` with some warning javadoc that explicitly says Mojang's names are misleading. The `Object` suffix makes it clear that it is using OpenGL terms, not names Mojang uses.

Apparently, this has caused too much trouble for shader/rendering engine mod developers.

**Comment by liach** [comment]
Makes sense. I recommend linking to https://www.khronos.org/opengl/wiki/GLSL_Object for the source of the `ProgramObject` and `ShaderObject` names, as they are otherwise confusing to java-oriented programmers.
