### ISSUE TITLE
`identifierCodec` and `stringCodec` in `TagKey` → `codec` and `hashPrefixCodec`

### ISSUE THREAD

**Issue by enbrain** [asiekierka/MinecraftPOMF#3132]
Both current names are confusing because both codecs serialize an identifier to a string.

**Comment by haykam821** [comment]
Since the unprefixed codec is deprecated, could these two fields be named `unprefixedCodec` and `codec` respectively instead?

**Comment by enbrain** [comment]
> Since the unprefixed codec is deprecated, could these two fields be named `unprefixedCodec` and `codec` respectively instead?

How is it deprecated? I don't see the `@Deprecated` annotation on the `identifierCodec` method.

**Comment by haykam821** [comment]
The unprefixed codec is deprecated in data packs. When registry entry lists were introduced, Mojang said that fields accepting unprefixed tag keys would eventually accept direct or reference registry entry lists instead.
