### ISSUE TITLE
Rename WorldAccess#createAndScheduleBlockTick

### ISSUE THREAD

**Issue by apple502j** [asiekierka/MinecraftPOMF#3161]
First, sorry for causing this mess.

When I mapped this in 1.18 snapshots I did not realize how often this method was used. The name is very long for a simple method. It doesn't feel very yarn-y. Maybe mapping stuff at 4AM didn't work.

I propose renaming this to `scheduleBlockTick`. This is very impactful, but I think this needs to be renamed.

**Comment by haykam821** [comment]
The `createAndScheduleFluidTick` method should also be renamed to `scheduleFluidTick`.
