### ISSUE TITLE
Vector classes have inconsistent multiplication method naming

### ISSUE THREAD

**Issue by haykam821** [asiekierka/MinecraftPOMF#3168]
I consider the `Vec3d` class the baseline for vector naming, so I will list deviations from its standards:

- `Vec3f#multiplyComponentwise(FFF)` should match `Vec3d#multiply(DDD)`
- `Vec3f#scale(F)` should match `Vec3d#multiply(D)`

If the term should be different because `Vec3f` is mutable (such as `relativize` versus `subtract`), then the `multiplyComponentwise` method should simply be renamed to `scale`.

**Comment by apple502j** [comment]
@haykam821 `multiplyComponentwise` might be from `Vector4f` - but this one should be named `scale` or `multiply`.

**Comment by apple502j** [comment]
Welp, I didn't expect this issue to be resolved by removing the class entirely :P
