### ISSUE TITLE
Registry initializer method names post-22w19a

### ISSUE THREAD

**Issue by apple502j** [asiekierka/MinecraftPOMF#3170]
Before 22w19a, the registry initializer methods were named like this:

- `initAndGetDefault` for non-DRM registries
- `registerAndGetDefault` for DRM registries

Since 22w19a the method is considered a functional interface named `BuiltinRegistries$Initializer`. The class name was chosen because `InitAndGetDefaulter` doesn't sound great. But this raises a question: what should the methods be named then?

Ideas:

- Keep current one
- Rename to `init`. (`initialize`, but yarn convention abbreviates that.) The "get default" part is an implementation detail and should be documented on the functional interface.
- Something else?

**Comment by haykam821** [comment]
I think these methods should be named `initialize`. After all, the `ModInitializer` method is named `onInitialize`.
