### ISSUE TITLE
StructureType renames

### ISSUE THREAD

**Issue by apple502j** [asiekierka/MinecraftPOMF#3182]
There are two `StructureType`s in yarn, `structure.StructureType` (`s.ST`) and `world.gen.StructureType` (`w.g.s.ST`). This is already concerning.

`w.g.s.ST` is a type of a structure registered to `structure` dynamic registry, while `s.ST` is a type of a structure type registered to `structure_type` normal registry. This is also explained by the fact that `s.ST` is just a fancy `Supplier<Codec>`.

~~If we follow the conventions, `s.ST` should be named `StructureTypeType`, but since that's also bad I suggest renaming everything to `StructureCodecType` (registry and class). Also, given that this has nothing to do with `n.m.structure` it should belong to `w.g.s`.~~

Given `w.g.s.StructureType` is a singleton it should follow `X` and `Xs` convention (`Block`/`Blocks`) instead of `X` and `XType` (`BlockEntity`/`BlockEntityType`). Problems arise from `Structure` being taken by `s.Structure` - thus I propose naming it `GeneratedStructure`/`GeneratedStructures`. This isn't far too stretched from vanilla registry, which is `worldgen/structure`. (Subclass names can stay.) `s.StructureType` should be moved to `w.g.s`.

**Comment by apple502j** [comment]
Updated this issue with a better proposal - this is essentially redoing #3079. After I've seen the mess it caused on Enigma (which does not differentiate different classes with the same name) I now believe this should not be shipped to 1.19.

**Comment by liach** [comment]
I recall mojang called the `structure.Structure` something like structure template in their blog posts. Since that one is less used by modders, feel free to rename all those ones.

**Comment by haykam821** [comment]
@liach The `/place feature` command implies that the structures managed by structure blocks can also be called templates as well.

**Comment by apple502j** [comment]
Renaming `s.Structure` to `StructureTemplate` sounds good. (And this is exposed and used already; `ChunkStructuresTemplateRenameFix`, `SimpleStructurePiece#template`, `ArgumentTypes` having `template_mirror` and `template_rotation`, etc)

**Comment by apple502j** [comment]
@liach How much can we rename before it gets too impactful? Specifically, can we touch StructureManager? That (or at least methods) should be renamed to StructureTemplateManager/getTemplate.

**Comment by liach** [comment]
I think we can rename now, as now pres are just snapshots. real pre releases are now called release candidates

**Comment by apple502j** [comment]
LOL, apparently I am not the first one who came up with `StructureTemplateManager` name :D

![record mapping on Enigma, showing StructureTemplateManager structureTemplateManager](https://user-images.githubusercontent.com/33279053/169794078-5c218605-f8bb-4a24-9d43-a9a11d68a0b2.png)
