### ISSUE TITLE
Slow update of versions.json

### ISSUE THREAD

**Issue by Bixilon** [asiekierka/MinecraftPOMF#3188]
The `versions.json` (https://maven.fabricmc.net/net/fabricmc/yarn/versions.json) always takes hours to update. I'd love to instantly use the published builds. 

I suspect cloudflare to be the issue here, their caching cdn service probably caches it. There could be some ways to "solve" this:
 - Disable caching (probably not the way to do it :P)
 - Reduce caching for index files
 - Clear the cache for that file after a publish

Moritz

(minor thing)

**Comment by modmuss50** [comment]
This was deprecated years ago and replaced by https://meta.fabricmc.net/v2/versions/yarn full docs: https://github.com/fabricMC/fabric-meta#v2

This has a 60 second cache.


The url you posted will be stop recieving updates at somepoint.

**Comment by Bixilon** [comment]
Good to know, thanks!
