### ISSUE TITLE
client.network.abusereport -> client.report

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#3225]
In authlib (see https://libraries.minecraft.net/com/mojang/authlib/3.9.47/authlib-3.9.47.jar), the related content are located in the `com.mojang.authlib.minecraft.report` package. Though the reports poll data from networking, it is never a part of networking infrastructure, hence should be moved into `client.report`, given it's client-only.

**Comment by liach** [comment]
In addition, `client.network.chat` can be merged into `client.report` as well, since those classes are only accessed via `AbuseReporter` (IMO should be renamed to `AbuseReportContext` or just `ReportContext`)

**Comment by apple502j** [comment]
Yeah, was unsure how to package them. I didn't want to introduce a new package directly under client, was too big to put in util, so I chose network.

Rename and repackage seems good, should not be impactful since nobody mods these. @liach Could you make the PR since I'm kinda busy?
