### ISSUE TITLE
Improper method and field name

### ISSUE THREAD

**Issue by CaveNightingale** [asiekierka/MinecraftPOMF#3231]
`LivingEntity#setForwardSpeed` is actually acceleration instead of speed.
Here are the screen record and code.
```java
public void tick(){
        if(!world.isClient) {
                entity.setNoGravity(true);
		entity.setUpwardSpeed(0.0f);
		entity.setForwardSpeed(0.5f);// here we see the entity moves faster and faster
		entity.setSidewaysSpeed(0.0f);
        }
        ...
}
```
![Peek 2022-07-06 20-36](https://user-images.githubusercontent.com/51874645/177552593-9719d1f7-497f-47f0-ae52-b56966962971.gif)

Above all, I think it's better to rename it to `setForwardAcceleration`. So as the field `LivingEntity#forwardSpeed`.

**Comment by modmuss50** [comment]
We have a very strict policy around not looking at mojmap names when developing yarn, please see: https://github.com/FabricMC/yarn#contributing.

Thanks.

**Comment by CaveNightingale** [comment]
> We have a very strict policy around not looking at mojmap names when developing yarn, please see: https://github.com/FabricMC/yarn#contributing.
> 
> Thanks.
I'm not talking about using any mojmap names. I was mislead by yarn during mod development and found this error while debugging.
Sorry for mentioning mojmap. It has been removed now.
