### ISSUE TITLE
JavaDoc grammar issue: 'Emits an game event'

### ISSUE THREAD

**Issue by dvitski** [asiekierka/MinecraftPOMF#3238]
The sentence 'Emits an game event' should read 'Emits a game event'.

https://github.com/FabricMC/yarn/blob/5a3bdbd522adfa5ad26bd4220ce5ca7cfefff269/mappings/net/minecraft/world/WorldAccess.mapping#L7

**Comment by enbrain** [comment]
That sentence does not add useful information to be honest. It's repeating the method name.

**Comment by apple502j** [comment]
I think there's still some value in providing javadoc for such methods; the ability to show that a method is noteworthy is one of the benefits.
