### ISSUE TITLE
AreaHelper -> NetherPortal

### ISSUE THREAD

**Issue by apple502j** [asiekierka/MinecraftPOMF#3267]
The current name `AreaHelper` is so bad, it makes zero sense:

- It is unclear what "area" means.
- This can only handle "area" on the vertical axis, not horizontal ones.
- Despite being named a helper, this is used by instantiating and not a collection of static methods.
- An instance can be invalid, which is also odd for a helper.
- There are several hardcoded references to nether portal.

I suggest renaming this to `NetherPortal`, because an instance does represent a (potentially broken) nether portal. Note that instances are created on the fly during portal related operations, and are not stored anywhere as far as I can see. That said I do not believe that should not matter here.

**Comment by liach** [comment]
Fyi this was once NetherPortalBlock.AreaHelper.

**Comment by apple502j** [comment]
@liach Yeah, but no instantiatable class should be called helper.
