### ISSUE TITLE
Some classes are missing

### ISSUE THREAD

**Issue by Danjhop4** [asiekierka/MinecraftPOMF#3292]
Can’t find the mappings for biomes in yarn

**Comment by Danjhop4** [comment]
And for blocks ether note I am new to modding

**Comment by apple502j** [comment]
Please explain in more detail. They should all be mapped.

**Comment by Danjhop4** [comment]
Can’t find code showing the block info the game version of the fabric example or class files to point to were they are tried the mojimap mappings too

**Comment by Danjhop4** [comment]
Here’s an example that exists in 20w16a net.minecraft.world.biome.DarkForestBiome 
But has no modern version used biomes as an example but first saw it with blocks

**Comment by apple502j** [comment]
Mojang does remove classes.

**Comment by Danjhop4** [comment]
Hard to tell if intended
