### ISSUE TITLE
Change scoreboardTags -> tags (and all related methods)

### ISSUE THREAD

**Issue by Draylar** [asiekierka/MinecraftPOMF#3308]
### Tag System

The `/tag` command system, and by extension all related methods in `Entity`, allow you to "tag" entities with persistent string flags that can be queried through `getScoreboardTags`. This feature is handy (and underused!) for storing additional data points on entities that are not cleared after they die - such as whether a player has passed a checkpoint, or has a mechanical property for a game mode. 

### Change Justifications

I propose removing the `scoreboard` prefix from all related methods & fields. I think it gives you a misleading idea as to what the system does. My reasons are as follows:
1. The system is entirely unrelated to scoreboards. The internal tag system does not interact with the scoreboard/team API at any level.
2. The data is serialized under the key `Tags`.
3. The entity selector operator key is `tag`, such as `@e[tag=foo]`.
4. Minecraft: Bedrock Edition has the same `/tag` system, but it is (also) untied to scoreboards, and is heavily relied upon for storing data on entities. You can tell what the intention of the system is (flagging entities with data, not interacting with scoreboards) based on how they use it on the other side.
5. The management command is named `TagCommand` in yarn. 

My *primary* reason is that calling `entity.addScoreboardTag`, and related methods, is more distracting/misleading than `entity.addTag`. You would normally think the method call has something to do with scoreboards based on the name, but that is not the case.

### Specific Changes

`Entity#scoreboardTags` -> `Entity#tags`
`Entity#addScoreboardTag(tag)` -> `Entity#addTag(tag)`
`Entity#getScoreboardTags()` -> `Entity#getTags()`
`Entity#removeScoreboardTag(tag)` -> `Entity#removeTag(tag)`

I would be happy to send in a pull request for this change after getting the go-ahead on it. :)

**Comment by Juuxel** [comment]
I agree that these should be renamed since they don't really have anything to do with scoreboards.

One thing to consider is that especially `getTags` could be easily confused with data pack tags. Should we call these command tags or something?

(The renaming here also isn't impactful I'd say, not many people use this system)

**Comment by apple502j** [comment]
"Tag" is also used to refer to NBTs. Simply renaming it would be very confusing.

**Comment by apple502j** [comment]
@Draylar Would `commandTags` be good?

**Comment by YanisBft** [comment]
Has been renamed to `commandTag` in #3480
