### ISSUE TITLE
Inconsistent parameter names in WanderAroundFarGoal and WanderAroundGoal's constructors

### ISSUE THREAD

**Issue by bldhf** [asiekierka/MinecraftPOMF#3318]
The parameters "pathAwareEntity" and "d" in WanderAroundFarGoal(PathAwareEntity pathAwareEntity, double d) should be renamed to "mob" and "speed" respectively to match its other constructor and WanderAroundGoal's constructors.

Also, the parameter "entity" in WanderAroundGoal(PathAwareEntity entity, double speed, int chance, boolean canDespawn) should be renamed to "mob" to match its other constructors.

**Comment by apple502j** [comment]
Seems to be fixed.
