### ISSUE TITLE
Modifying parts of Commit #331

### ISSUE THREAD

**Issue by EliteMasterEric** [asiekierka/MinecraftPOMF#332]
Commit #331 "Various small rendering related renames." makes several changes, including this one:

`net/minecraft/client/render/block/BlockRenderManager/render -> renderAsItem`

Why was this change made? It is used by Iron Golems and Endermen (fair, they are holding them as items), Minecarts containing blocks (okay...), Mooshrooms for the mushrooms on their backs, and... primed TNT to render the TNT entity the same as the block.

This function is designed to allow rendering a given BlockState directly, and is not exclusively related to items.

@covers1624 created this commit.

**Comment by covers1624** [comment]
I must have derped somewhere, i actually had a different name for that. I was initially going to go with `renderAsItem` but reverted it, ill open a fix later on.

**Comment by covers1624** [comment]
Fixed as of https://github.com/FabricMC/yarn/commit/f07fc18ffbfab19463ee877f54a13d5e0c36f55c#diff-06c141e02a45b08663f6eff4a478fe31R12 Modmuss made the change for me.
