### ISSUE TITLE
Entity.getHeadPitch() and setHeadPitch() likely misnamed

### ISSUE THREAD

**Issue by MamiyaOtaru** [asiekierka/MinecraftPOMF#334]
see BoatEntity (~line 711) where they are called in relation to Entity.yaw.  yaw += some value (delta yaw prob), then it setHeadPitch(getHeadPitch + *yaw*).  This is much more likely getting and setting the entity's head yaw

**Comment by asiekierka** [comment]
One of the recent PRs merged fixed this.
