### ISSUE TITLE
The startTime parameter of Brain.remember is incorrect

### ISSUE THREAD

**Issue by enbrain** [asiekierka/MinecraftPOMF#3399]
It should be `duration`. It's a bad match from [20w10a](https://github.com/FabricMC/yarn/commit/1b7aa91a4ddc43fd259bc4011834e7e5112143b8#diff-d50255fd81242e9db855cd3c554979f54aa7dd47c5c71390990e16c56d431ca5).

**Comment by apple502j** [comment]
Ah, that makes much more sense.

**Comment by apple502j** [comment]
Renaming to `expiry` as that is the term used in the class. Mojang calls this TTL but Yarn generally avoids initialisms.
