### ISSUE TITLE
net.minecraft.village -> net.minecraft.entity.villager

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#340]
What is currently in the package: https://github.com/FabricMC/yarn/tree/18w50a/mappings/net/minecraft/village

Only `VillageDoor` and `VillageProperties` are actually related to villages; others are about villagers. Moreover, these two things are generated by villager entities on need (see vanilla village mechanism).
@jamierocks need your comment..

If such a package change is to be made, the `VillagerEntity` will go into this package as well.

**Comment by Player3324** [comment]
My personal preference from a cursory look is putting the villager entity in entity and everything else in "some world feature package"."village".

Rationale: This is support code for a feature that is recognized as world gen similar to dungeons, even that isn't strictly the case from a technical pov. It is not purely entity specific, making it less suitable for entity/*, and the primary mc package shouldn't have too many direct children.

**Comment by liach** [comment]
Those code are not for feature. In vanilla, village objects are not created when villages are generated; village objects are created to control the spawning of iron golems, breeding of villagers, and reputation of players (iron golems' attack targets) village objects are created by the villagers generated in the villages instead.

**Comment by jamierocks** [comment]
I'm yet to have a complete understanding of the village classes, will have to take a deeper look into them soon (with work and Christmas, this may be a week or two off though - we can always revert/correct changes though if need be).

**Comment by falkreon** [comment]
VillageProperties _is serialized_ into NBT in villages.dat, and has been for a while. It's part of the savegame / map, making them probably belong to `.world` or `.world.village`. The same goes for VillageDoor.

Villager, SimpleVillager, VillagerInventory, VillagerRecipeList, and VillagerRecipe all look like gui-related classes:
* VillagerEntities use a BasicInventory, not a VillagerInventory. VillagerInventory seems to be a fake inventory that syncs recipes down to the client when the trade gui is open.
* I'll need to do more digging, but VillagerRecipeList and VillagerRecipe seem to only be used by SimpleVillager, and-
* SimpleVillager is client-only, and I don't see any other implementations of Villager.
So maybe `.gui` or `.gui.villager`

Given that a lot of people will probably be looking specifically for village-related classes, I'm not wholly opposed to keeping them in `.village`, but if they move, they probably want to split up along these lines.

**Comment by liach** [comment]
@falkreon raid is serialized as well, but it is put into enitiy/raid package instead. so your point on village does not stand. the simple villager is for sync, but what's synced is not always gui (e.g. tracked data)

btw you didn't address where villager profession, type, and data should go to

**Comment by falkreon** [comment]
Odd. Could have sworn I left a comment here but it's gone.

Raid and RaidManager seem to go in `.world` along with the lightweight village classes, since they're part of the world, serialized with world save, and not sync'd.

RaiderEntity belongs in `.entity.mob` since all its subclasses are there.

VillagerProfession, VillagerType, and VillagerData are tightly coupled with the Entity (VillagerProfession is never even sync'd unless something drastic changed, only VillagerType is), so they probably head for `.entity.passive` to live next to their entity, like HorseArmorType lives there for horses.

As these things get mapped, the sorting will only intensify :)

**Comment by liach** [comment]
fyi the whole villager data is synced for rendering. btw, would the world package be too crowded if we put all persistent states there?

**Comment by falkreon** [comment]
Just peeked at the EntityTracker for it, yeah, you're right. That's new! (or, at least, wasn't that way in 1.12).

Even so, I think when something is primarily used inside an Entity and its EntityTracker, it's okay to be in the Entity package.

**Comment by liach** [comment]
I'd say keep it in `village` package. The villager subpackage would be too deep.
