### ISSUE TITLE
Extremely controversial: Block -> BlockType; Item -> ItemType; ItemStack -> Item

### ISSUE THREAD

**Issue by Prospector** [asiekierka/MinecraftPOMF#342]
Is this an insane idea? Probably. But it would be consistent with BlockEntityType, ParticleType, EntityType, etc.

you should probably 👎 right now

**Comment by LemmaEOF** [comment]
The main thing is that there's already a `BlockEntity` class that necessitates `BlockEntityType` being called as such. There isn't a necessity for blocks or items.

**Comment by Prospector** [comment]
ItemStack tho

**Comment by LemmaEOF** [comment]
Then that would require Item -> ItemStackType and that would just be hell. Plus, there's already official Mojang established names for Block and Item, but not BlockEntity and the like.

**Comment by dblsaiko** [comment]
I was going to suggest this at some point, actually. Exactly the same renames. So I'm all for it :D

**Comment by Daomephsta** [comment]
I'm all for this. The new name better communicates that the classes are flyweights, which is a common pitfall for new modders.

**Comment by 3TUSK** [comment]
For reference, Sponge API uses `BlockType`<sup>[1]</sup> and `ItemType`<sup>[2]</sup> for the same concept. 

[1]: https://jd.spongepowered.org/7.1.0/org/spongepowered/api/block/BlockType.html
[2]: https://jd.spongepowered.org/7.1.0/org/spongepowered/api/item/ItemType.html

**Comment by liach** [comment]
sponge api does have many nice names, e.g. text instead of component

**Comment by falkreon** [comment]
Not completely opposed.

"Type" is a loaded word, and that flyweight sense that we're trying to communicate might not come across. What about `BlockKind`/`ItemKind`?

I think we should keep `ItemStack` though.

**Comment by liach** [comment]
Or `Block/ItemRegistryEntry`

**Comment by dblsaiko** [comment]
Nah, it's main job isn't to be a registry entry.

**Comment by NikkyAI** [comment]
i think `type` might not be the best choice but `kind` works well enough

**Comment by Ansraer** [comment]
tbh I am not a huge fan. I can understand where you are coming from, but we always had Block and all modders are used to them. Plus Block type would kind of imply that there is an actual Block too.
I am completely against changing ItemStack btw. That name perfectly describes what an ItemStack is.

**Comment by dblsaiko** [comment]
"all modders are used to them" is not a good reason. There's a lot of names that were changed from the well known ones despite that in Yarn mappings, eg. BlockEntity

**Comment by Prospector** [comment]
I think it's a thoroughly shit idea but "modders are used to them" is the worst argument you could've pulled out because that does not matter

**Comment by Prospector** [comment]
With a vote ratio of 3:1 I will close this
