### ISSUE TITLE
Extremely controversial: Block -> Tile

### ISSUE THREAD

**Issue by asiekierka** [asiekierka/MinecraftPOMF#343]
:rofl: :rofl: :rofl: :rofl: :rofl:

**Comment by kashike** [comment]
![pls stop](https://i.imgur.com/RlEqP6k.png)

**Comment by liach** [comment]
This is not Minecraft alpha. This is Minecraft modern.

**Comment by jamierocks** [comment]
"First of all, calling blocks “Tiles” in the codebase is horribly confusing." - https://notch.tumblr.com/post/760983716/my-worst-code-design-decision

I hope this wasn't serious...

**Comment by LemmaEOF** [comment]
> I hope this wasn't serious…

this is riffing on #342, we're having a laugh about it in the irc.
