### ISSUE TITLE
No unpick definitions results in genSources not working

### ISSUE THREAD

**Issue by reoseah** [asiekierka/MinecraftPOMF#3448]
It seems that if there's no `*.unpick` files in `unpick-definitions` folder, Yarn build creates empty `extras/definitions.unpick` inside resulting jars, and this later causes crash with Loom when using `genSources`.

The crash looks like this:
```
./gradlew genSources                                                           

> Configure project :
Fabric Loom: 1.0.16
:remapping 1 mods from modApi
:remapping 2 mods from modImplementation
:remapping sources

> Task :unpickJar FAILED
Exception in thread "main" daomephsta.unpick.constantmappers.datadriven.parser.UnpickSyntaxException: Line 1: Missing version
        at daomephsta.unpick.impl.constantmappers.datadriven.DataDrivenConstantMapper.<init>(DataDrivenConstantMapper.java:52)
        at daomephsta.unpick.api.constantmappers.ConstantMappers.dataDriven(ConstantMappers.java:23)
        at daomephsta.unpick.cli.Main.unpick(Main.java:62)
        at daomephsta.unpick.cli.Main.main(Main.java:47)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unpickJar'.
```

This happened after gradle code and versions of tooling in Legacy Fabric's repo were made up to date with this repo, as described here https://github.com/Legacy-Fabric/yarn/issues/253

I did the following and it does happen with Fabric Yarn too
1. clone this repo
2. go to `unpick-definitions/` and delete all `.unpick` files (leaving only `unpick.json`)
3. execute `./gradlew build`

— resulting files, `yarn-(version+build)-v2.jar` and `yarn-(version+build)-mergedv2.jar` have empty `definitions.unpick` file, which is what fails Loom's `genSources` with error shown above

**Comment by iMonZ** [comment]
Any news here?

**Comment by modmuss50** [comment]
I dont think this is a Yarn issue at all? It sounds like this has only been reproduced in legacy fabric, but not something we ever published?

I think its fair to assume that if you have an unpick.json in the mapping jar there is a valid `extras/definitions.unpick`.
