### ISSUE TITLE
PlayerEntity#getArrowType() can also get non-arrow projectiles

### ISSUE THREAD

**Issue by PatrickMSM** [asiekierka/MinecraftPOMF#3451]
The method `getArrowType` in `PlayerEntity` can also return other non-arrow projectiles, so instead it should be named something along the lines of `getProjectileType` or even `getProjectileStack`

**Comment by PatrickMSM** [comment]
An example for this is for crossbows, it can return fireworks too

**Comment by PatrickMSM** [comment]
Turns out that the method is actually inherited from `LivingEntity` and is overriden in `PlayerEntity`.

**Comment by PatrickMSM** [comment]
Issue fixed in pr #3452

**Comment by Juuxel** [comment]
But it's not fixed yet since the PR is open...

**Comment by PatrickMSM** [comment]
Once it gets accepted it will be fixed.
