### ISSUE TITLE
net.minecraft.client.util.SmoothUtil name is bad

### ISSUE THREAD

**Issue by Sollace** [asiekierka/MinecraftPOMF#3453]
Besides not following the usual convention of these kinds of classes ending in *Helper rather than Util, the name also implies that it's a class of static utility methods, which isn't at all true. It's actually a class Mojang uses as a generic "smoother".

They instantiate it twice in the Mouse class and call its `smooth` method incrementally, with the current x or z and the change versus time to smooth out the values.

Relevant usage (found in `Mouse.updateMouse`, variable names added for clarity):
```
        double time = GlfwUtil.getTime();
        double timeDifference = time - this.lastMouseUpdateTime;
        this.lastMouseUpdateTime = time;
        if (!this.isCursorLocked() || !this.client.isWindowFocused()) {
            this.cursorDeltaX = 0.0;
            this.cursorDeltaY = 0.0;
            return;
        }
        double sentitivity = this.client.options.getMouseSensitivity().getValue() * (double)0.6f + (double)0.2f;
        double speed = Math.pow(sentitivity, 3) * 8.0;
        if (this.client.options.smoothCameraEnabled) {
            double i = this.cursorXSmoother.smooth(this.cursorDeltaX * speed, timeDifference * speed);
            double j = this.cursorYSmoother.smooth(this.cursorDeltaY * speed, timeDifference * speed);
```

Suggested name changes:
`SmoothUtil` -> `TrailingInterpolator`
`SmoothUtil.smooth(double original, double smoother)` -> `TrailingInterpolator.step(double value, double timeDifference)`

Suggested package change:
`net.minecraft.util` -> `net.minecraft.util.math.noise`

**Comment by Juuxel** [comment]
Definitely shouldn't be in `util.math.noise` if it's used for mouse input (which is not worldgen noise), I think a rename to `Smoother` would be fine?

**Comment by Sollace** [comment]
> Definitely shouldn't be in `util.math.noise` if it's used for mouse input (which is not worldgen noise), I think a rename to `Smoother` would be fine?

Smoother sounds good!

My reasoning for putting it in noise is it seems to be related to those kinds of noise-y operations. I.e. like smoothing the output of a noise function.

Nothing I could see from the package name to indicate it's for world generation.

**Comment by Juuxel** [comment]
The package currently contains noise generation code, the smoother class isn't really related to those.
