### ISSUE TITLE
ModelElementFace.tintIndex -> ModelElementFace.layer

### ISSUE THREAD

**Issue by Sollace** [asiekierka/MinecraftPOMF#3454]
Second parameter to the ModelElementFace here is derived from the textures provided for the item in it's model json.
![image](https://user-images.githubusercontent.com/6429283/211101803-3a7a550e-5d49-4374-8b2c-ad3130a3a447.png)

It is the "layer" passed to this method, aka, the numerical index corresponding to the constants layer0 -> 0, layer1 -> 1, etc... defined at the top of this class

![image](https://user-images.githubusercontent.com/6429283/211103790-1c191ea3-2f7b-486c-935e-d04c3baa0b90.png)

Of course this means several downstream field names and method parameter names may need to be changed as well.

`ModelElementFace(cullFace, tintIndex, textureId, textureData)` -> `ModelElementFace(cullFace, layer, textureId, textureData)`
`ModelElementFace.tintIndex` -> `ModelElementFace.layer`
`BakedQuad.colorIndex` -> `BakedQuad.layer`
`BakedQuad(vertexData, colorIndex, face, sprite, shade)` -> `BakedQuad(vertexData, layer, face, sprite, shade)`
`BakedQuad.hasColor()` -> `BakedQuad.isBaseLayer()`
`BakedQuad.getColorIndex()` -> `BakedQuad.getLayerIndex()`
`ItemColors.getColor(item, tintIndex)` -> `ItemColors.getColor(stack, layer)`
`ItemColorProvider.getColor(var1, var2)` -> `ItemColorProvider.getColor(stack, layer)`

One complication, though, current name seems to be based on the crobbed Mojang name in the deserializer.

```
protected int deserializeTintIndex(JsonObject object) {
     return JsonHelper.getInt(object, "tintindex", -1);
}
```
Though IMO I'd rather go with it being the layer, or layerIndex, rather than tintindex because keeping it as it is creates confusion about whether it's meant to be a colour.

**Comment by haykam821** [comment]
No, the tint index does not correspond exactly to a layer in all scenarios, and multiple faces can share the same tint index. Layer faces are an exception as they are generated from a texture.
