### ISSUE TITLE
Calling BlockPos.stream(BlockPos Start, BlockPos End) and using a forEach loop that copies the elements into a list or array makes previous elements in that list/array return previous elements.

### ISSUE THREAD

**Issue by Blobanium** [asiekierka/MinecraftPOMF#3456]
Not to sure that this is a yarn thing or not or a bug within Minecraft itself or with yarn, but I feel like its yarn that is causing the issue so here's my hot take on this:

So the title should explain it all, might mind boggle some people on what I'm talking about. Feel free to change the title if my keywording is inaccurate.

So, we need placeholder code for a little bit of context.
```
        BlockPos[] someArray = new Blockpos[64];
        Stream<BlockPos> someBlockPosStream = BlockPos.stream(someBlockPos, someOtherBlockPos);
        AtomicInteger i = new AtomicInteger();
        boardStream.forEach(e -> {
            someArray[i] = e;
            System.out.println(Arrays.deepToString(someArray));
            i.getAndIncrement();
        });
```

This code with the system.out.println is Expected to return the following output (if you used (new BlockPos(-5, 66, -5), new BlockPos(-12, 66, -12)) as your input):
```
[class_2339{x=-12, y=66, z=-12}, null, null, null, null, null, null, null]
[class_2339{x=-12, y=66, z=-12}, class_2339{x=-11, y=66, z=-12}, null, null, null, null, null, null]
[class_2339{x=-12, y=66, z=-12}, class_2339{x=-11, y=66, z=-12}, class_2339{x=-10, y=66, z=-12}, null, null, null, null, null]
this goes on until all of the BlockPos positions from the stream has been copied.
```

But instead returns this
```
[class_2339{x=-12, y=66, z=-12}, null, null, null, null, null, null, null]
[class_2339{x=-11, y=66, z=-12}, class_2339{x=-11, y=66, z=-12}, null, null, null, null, null, null]
[class_2339{x=-10, y=66, z=-12}, class_2339{x=-10, y=66, z=-12}, class_2339{x=-10, y=66, z=-12}, null, null, null, null, null]
...
```
Im not exactly why this is happening, but seems to be an issue with blockpos itself

my yarn mappings is 1.19.2+build.8 if anything helps.

A workarround i found is to use an int[x][3] matrix, using GetX() Y, and Z methods and then reconstruct the BlockPos positions from there. (x is how many BlockPositions you want, and 3 is the blockpos itself, one for each dimension)

If theres anything else i need please let me know.

**Comment by Juuxel** [comment]
Yarn doesn't change the behaviour of game code, it just gives it human-readable names and documentation.

**Comment by Shnupbups** [comment]
As Juuz said, all Yarn does is make Minecraft's code human-readable. It does not alter any functionality. This does not look like an issue that relates to Yarn.

**Comment by haykam821** [comment]
Minecraft uses `BlockPos.Mutable` to optimize logic that would otherwise require large amounts of object allocation, such as iterating over a box of positions. As such, you are simply adding the same object to a collection. You can get around this behavior through workarounds like the one you mentioned or by calling `BlockPos#asLong`.
