### ISSUE TITLE
trim stuff does not appear in Registries or it’s own file

### ISSUE THREAD

**Issue by Danjhop4** [asiekierka/MinecraftPOMF#3474]
The net/minecraft/registry/OneTwentyBuiltinRegistries does not appear to register registries to do with trim items and it’s missing form registries too I can’t find any reference to trims we’re I would expect apart from registrytags

**Comment by apple502j** [comment]
If this is an actual bug report, please phrase it in better ways. This currently looks like a spam report or coding question.

**Comment by Danjhop4** [comment]
> If this is an actual bug report, please phrase it in better ways. This currently looks like a spam report or coding question.

How I saying I think a mapping is missing and it looks like a bot
