### ISSUE TITLE
Can’t find regegistries for trim stuff

### ISSUE THREAD

**Issue by Danjhop4** [asiekierka/MinecraftPOMF#3475]
I can’t find the trim registries in registries class or
One twenty built in registries class

**Comment by Danjhop4** [comment]
Don’t think it exists

**Comment by Shnupbups** [comment]
This isn't an issue with Yarn, please don't spam issues unrelated to mappings.
But for what it's worth, the Patterns are registered in `net/minecraft/item/trim/ArmorTrimPatterns` and the Materials in `net/minecraft/item/trim/ArmorTrimMaterials`.
