### ISSUE TITLE
cant access setblocktype class 

### ISSUE THREAD

**Issue by Danjhop4** [asiekierka/MinecraftPOMF#3499]
because its protected you cant have a block use it out side of the blocks class is there any way to open it up

**Comment by Danjhop4** [comment]
a bunch of block types need it

**Comment by Juuxel** [comment]
This is not a Yarn issue.

**Comment by Danjhop4** [comment]
> This is not a Yarn issue.

how when you need it

**Comment by kristofbolyai** [comment]
You don't understand what Yarn/mappings are; they are purely visual, the method is protected from Minecraft source code. Investigate [Access Wideners](https://fabricmc.net/wiki/tutorial:accesswideners) or [Invokers](https://fabricmc.net/wiki/tutorial:mixin_accessors).
