### ISSUE TITLE
protected class

### ISSUE THREAD

**Issue by Danjhop4** [asiekierka/MinecraftPOMF#3500]
![test](https://user-images.githubusercontent.com/106870098/219739840-f0dba394-30d8-4ca6-a095-f9ad012bdc22.png)
dont know were else to post this
the class cant be used to make a mod

**Comment by Danjhop4** [comment]
and dont give me rubbish about its the wrong place

**Comment by modmuss50** [comment]
@Danjhop4 The yarn issue tracker is for issues with the yarn names, not modding problems. This is not the first time we have had to close these issues.
