### ISSUE TITLE
net.minecraft.container.Container -> SharedGuiState?

### ISSUE THREAD

**Issue by falkreon** [asiekierka/MinecraftPOMF#351]
Container implies inventory. It's pretty easy to mistake this class for an inventory-only thing, but:
* it carries non-inventory numeric information, such as furnace or machine progress
* it's even used to sync not-really-numeric information, such as beacon effects
* it holds the syncId that's used to manage custom-packet-delivered information
* it manages button clicks such as in EnchantingTableContainer
* Slots and buttons have x/y locations. This also makes Container function as a structural description of the gui.

So the name `Container` never really worked for me. Keeping all this in mind, SharedGuiState may not be the best name here. It's hard to smurf-name all the specific instances. To make it a better package name, perhaps net.minecraft.guistate.GuiState instead. But I think if we can come to a good consensus on the purpose of the object we can find a much better fit.

**Comment by liach** [comment]
so UiData or UserInterfaceData?

**Comment by LemmaEOF** [comment]
`SyncedGui`?

**Comment by LemmaEOF** [comment]
@therealfarfetchd said that it's important that it's not a regular gui, so maybe `SyncedInterface` or something

**Comment by asiekierka** [comment]
19w02a Mojang says "createMenu"

**Comment by LemmaEOF** [comment]
From the #yarn channel in the discord:
- some of us hate the name menu, it reeks of notch and is vague
- debating things like ServerUi/ClientUi, Gui/GuiState
- ~~asie suggests we go K-ON! and call them Ui/Yui~~

**Comment by LemmaEOF** [comment]
I feel like we might need ultimately need to go to `Menu/Screen`, because of the policy of using Mojang names where we know them.

**Comment by Pannoniae** [comment]
I'd say "don't change a bad name to a worse name", even if it's a Mojang one.

**Comment by LemmaEOF** [comment]
The primary issue with `Container` is that it's voldename, so it's IMO worse than the Mojang name since it could get us in trouble.

**Comment by Prospector** [comment]
I agree that Container should go no matter what the replacement is because it makes so little sense and it would certainly not be named Container in yarn if it was not for voldemap.

I think Menu is good and GuiState is less good but bearable. I would say the name should be no longer than 10 characters though as it will be used quite often

**Comment by hea3ven** [comment]
I think GuiState is not the nicest name to look at, but it's the one that best displays its function. Another similar option is GuiController, makes sense if you look it as a sort of MVC pattern (Inventory = model, Gui = View, Container = Controller), but it's a bit longer than GuiState.

**Comment by hea3ven** [comment]
Should be ScreenState or ScreenController now that Gui has been renamed.

**Comment by falkreon** [comment]
I love everything about that except that it's long. We'd wind up not just with `CartographyTableScreenController`, but also `DoubleLockableScreenController` and `NameableScreenControllerProvider`. It's *exceptionally clear* though.

**Comment by hea3ven** [comment]
I feel that Controller is too generic to have in a game engine by itself, but in this case it doesn't clash with anything. Also, the package could be used to make it more specific. How about having it in the net.minecraft.screen.controller package?

**Comment by Prospector** [comment]
Controller is great 👍

**Comment by falkreon** [comment]
While I still think Controller is the most accurate name, #846 has very compelling reasons for adoption.
