### ISSUE TITLE
setSoundVolume() was removed in commit "22w42a"

### ISSUE THREAD

**Issue by JonathanHoffmann** [asiekierka/MinecraftPOMF#3596]
setSoundVolume() was removed from net.minecraft.client.option.GameOptions in the commit "22w42a" by player@player.to be004e39160fa1d7c665222c8c09c2724520754a

Is this intended? I couldn't figure out another way to change the sound volume, the corresponing getter still works just fine.

**Comment by haykam821** [comment]
This change is in Minecraft, not the Yarn mappings. You should access a sound category's option through the `GameOptions#getSoundVolumeOption` method and set the volume using the `SimpleOption#setValue` method.
