### ISSUE TITLE
Material.field_15921 -> UNUSED_PLANT

### ISSUE THREAD

**Issue by LemmaEOF** [asiekierka/MinecraftPOMF#361]
Material.field_15921 seems to be a fully orphaned material type. All we know about it is:
- it's got a MaterialColor of `FOLIAGE`
- it's destroyed by pistons
- SwordItem includes it in materials it can break faster

I think this may have been used for vines in the past, since I recall old pomf having a `VINE` material, but it seems Mojang has orphaned the material type with recent updates to vine and ladder functionality. Since it doesn't have anything to its name in vanilla, I think it would be best to call it an `UNUSED_PLANT` Material for now.

**Comment by YanisBft** [comment]
Can be closed
