### ISSUE TITLE
Tameable.method_48926 -> getWorld

### ISSUE THREAD

**Issue by Daomephsta** [asiekierka/MinecraftPOMF#3651]
`method_48926` is implemented by both `TameableEntity` and `AbstractHorseEntity` using a synthetic bridge method that returns `super.getWorld()`. There are no other implementations, so `method_48926` is definitely meant to be implemented by `Entity.getWorld()`, thus the names should be the same.

**Comment by liach** [comment]
From fabric discord bot, it says:

> Method Names

>Official: method_37908
>Intermediary: method_37908
>Yarn: method_48926

Official one shouldn't be `method_37908`. Maybe it's a toolchain bug.
