### ISSUE TITLE
The UnlockRecipesS2CPacket class also removes unlocked recipes

### ISSUE THREAD

**Issue by haykam821** [asiekierka/MinecraftPOMF#3670]
The `UnlockRecipesS2CPacket` class suggests that it is sent when new recipes are unlocked. While this is true when initializing and adding unlocked recipes, the packet also handles removing unlocked recipes (`UnlockRecipesS2CPacket.Action.REMOVE`). I suggest the name `UnlockedRecipesS2CPacket` for this class and its associated methods to clarify that it handles generic updating of unlocked recipes, much like how the `ChatSuggestionsS2CPacket` class supports adding, removing, and setting chat suggestions.

**Comment by Dev0Louis** [comment]
UpdateRecipesS2CPacket?

**Comment by Dev0Louis** [comment]
Oh no this implies that new recipes are added, your Name is better.

**Comment by bluebear94** [comment]
Or maybe `ChangeUnlockedRecipesS2CPacket`, though this one is borderline excessive.
