### ISSUE TITLE
java.lang.IllegalStateException: Unable to match Kotlin version from: 1.9.20-Beta-release-228

### ISSUE THREAD

**Issue by NotGoat01** [asiekierka/MinecraftPOMF#3671]
My mod wont build because of "java.lang.IllegalStateException: Unable to match Kotlin version from: 1.9.20-Beta-release-228"

**Comment by NotGoat01** [comment]
wait
why did you close it

**Comment by Shnupbups** [comment]
This is not a yarn issue
