### ISSUE TITLE
Classes and methods regarding iron golems offering poppies are named incorrectly

### ISSUE THREAD

**Issue by haykam821** [asiekierka/MinecraftPOMF#3704]
The iron golem's behavior of offering poppies is managed by the `IronGolemLookGoal` class,`IronGolemEntity#setLookingAtVillager` method, and `IronGolemEntity#lookingAtVillagerTicksLeft` field. However, according to the usages of the field in the `IronGolemFlowerFeatureRenderer` and `IronGolemEntityModel` classes, the actual functionality relates to raising the iron golem's arm and rendering a poppy.

**Comment by apple502j** [comment]
Not a yarnbug, accurate description of its behavior. Iron golems look at (baby) villagers and give them poppies.
