### ISSUE TITLE
[Bug] `getSerializer` of `RecipeJsonProvider` And `Recipe` Conflicts

### ISSUE THREAD

**Issue by Phoupraw** [asiekierka/MinecraftPOMF#3718]
`net.minecraft.class_1860.method_8119` is mapped to `net.minecraft.recipe.Recipe.getSerializer`. `net.minecraft.class_2444.method_17800` is mapped to `net.minecraft.data.server.recipe.RecipeJsonProvider.getSerializer`. If one class implements both the interfaces, the mod won't be built.

Class example:
[ExtendedCookingRecipe.java.txt](https://github.com/FabricMC/yarn/files/13259494/ExtendedCookingRecipe.java.txt)

Build failed:
[console_part.txt](https://github.com/FabricMC/yarn/files/13259493/console_part.txt)

**Comment by apple502j** [comment]
Closing as I could not find `method_17800`.

**Comment by Linguardium** [comment]
method_17800 was removed in 1.20.2

Since yarn has releases for previous versions as well, it may be worth it to update previous version yarn mappings
