### ISSUE TITLE
PlayerEntity#playSound overload is misleading.

### ISSUE THREAD

**Issue by Dev0Louis** [asiekierka/MinecraftPOMF#3760]
In PlayerEntity we have two methods
```java
	@Override
	public void playSound(SoundEvent sound, float volume, float pitch) {
		this.getWorld().playSound(this, this.getX(), this.getY(), this.getZ(), sound, this.getSoundCategory(), volume, pitch);
	}

	public void playSound(SoundEvent event, SoundCategory category, float volume, float pitch) {
	}
```
~~They seem like they are the same and a simple overload, but they are not.~~ 
~~One of them does nothing, this should be indicated by the name~~
Read: https://github.com/FabricMC/yarn/issues/3760#issuecomment-1889509637

**Comment by Juuxel** [comment]
Isn't the one that "does nothing" overridden to have logic in one of the sided subclasses?

**Comment by Dev0Louis** [comment]
> Isn't the one that "does nothing" overridden to have logic in one of the sided subclasses?

Oh my Idea just bugged they actually override it.
But their is still a difference.
```java
        this.networkHandler.sendPacket(new PlaySoundS2CPacket(Registries.SOUND_EVENT.getEntry(event), category, this.getX(), this.getY(), this.getZ(), volume, pitch, this.random.nextLong()));
```
Is the code for playSound on ServerPlayerEntity. It plays **only** for that player.
While the other method plays for everyone around **except** for the player.

**Comment by apple502j** [comment]
Not sure what this issue is asking for. Closing.

**Comment by Dev0Louis** [comment]
Wnat tne

**Comment by Dev0Louis** [comment]
The Issue is about the overload of playSound in PlayerEntity. 
The override of playSound(SoundEvent event, SoundCategory category, float volume, float pitch) in ServerPlayerEntity sends a PlaySoundS2CPacket to the player.

playSound(SoundEvent sound, float volume, float pitch) is not being overridden by the ServerPlayerEntity so the logic of PlayerEntity is run.
Which calls world#playSound with `this` as first parameter. Which except's the player from hearing the sound. 

These 2 Methods should not be an simple overload as they in ServerPlayerEntity have actually the opposite effect.
One makes only the player hear the sound the other makes everyone except for the player hear the sound

**Comment by apple502j** [comment]
One of the playSound comes from `Entity`, so that one stays. Regardless, so long as you are using it properly (see also: `ClientPlayerEntity#playSound`), the player should always hear the sound.

**Comment by Dev0Louis** [comment]
ClientPlayerEntity#playSound is being overriden by ClientPlayerEntity with a method that works as expected.
This does not happen for ServerPlayerEntity.  
It uses the Method from PlayerEntity which excludes itself from the playSound. Maybe a JavaDoc to clarify would be enough as I currently can't think of a better name, as the name is used in ServerPlayerEntity and ClientPlayerEntity to do 2 different things.

**Comment by apple502j** [comment]
So long as you call them in both sides (i.e. outside isClient check) this should work fine.
