### ISSUE TITLE
"darkness" vs "subtracted light"

### ISSUE THREAD

**Issue by asiekierka** [asiekierka/MinecraftPOMF#384]
>Iirc darkness is used in other places for similar function (specifically World operations). Should this be made consistent?

https://github.com/FabricMC/yarn/pull/380

**Comment by Runemoro** [comment]
+1 for darkness

**Comment by Niko-sk2x** [comment]
I think there is no way the `subtracted light` name didn't come in some way from MCP.

If `darkness` was in yarn earlier, i think this would be a better one. `subtracted light` looks really weird and doesn't really tell you what it may actually be for.

Another idea that definitely tells you what it's for, but may be a bit weird: `night level`.

**Comment by Blayyke** [comment]
With 1.14 full release so close, i think now would be a good time to make this change. Darkness sounds good, and getting rid of a voldemap name can't be anything but good.

**Comment by Runemoro** [comment]
I can't find any `subtractedLight` apart from the `Block.getSubtractedLight` and its related methods, which are correctly named (and in any case, a different name for that could be *opacity*, not *darkness*).
