### ISSUE TITLE
setStepHeight method is missing from 1.20.5 pre release

### ISSUE THREAD

**Issue by Universeds** [asiekierka/MinecraftPOMF#3844]
The setStepHeight method is missing from the net.minecraft.entity.Entity class.

https://maven.fabricmc.net/docs/yarn-1.20.5-pre1+build.3/net/minecraft/entity/Entity.html

**Comment by apple502j** [comment]
Not our issue. Mojang changes all the time. Time to find a replacement, I suppose.
