### ISSUE TITLE
mapJar creates an empty jar

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#385]
The `19w02a-mapped.jar` created by `gradlew mapJar` is empty. It also seems like it's not closing the file, since deleting the file without stopping the gradle daemon doesn't work, and running mapJar again without restarting the gradle daemon throws a file in use exception.

**Comment by modmuss50** [comment]
Thanks for the report, I’m currently reworking this to create an intermediary jar as well.

I will take this into account.
