### ISSUE TITLE
ColorHelper#Argb is NOT ARGB but ABGR

### ISSUE THREAD

**Issue by 1zun4** [asiekierka/MinecraftPOMF#3903]
Hi. The mappings for ColorHelper are wrong. They seem to be using ABGR in this case, not ARGB.
The functions named like this make sense to be used for ARGB, but Minecraft uses them for ABGR. 

If you do the following:
`fun toABGR() = ColorHelper.Argb.getArgb(this.a, this.b, this.g, this.r)`.
will display the colours correctly on for example the Glow shader.

However, the mappings tell you to do the following:
```java
/**
 * {@return the ARGB color value from its components}
 */
public static int getArgb(int alpha, int red, int green, int blue) {
    return alpha << 24 | red << 16 | green << 8 | blue;
}
```

**Comment by apple502j** [comment]
The names are correct (`ARGB = alpha << 24 | red << 16 | green << 8 | blue`). What is the problem? @1zun4

**Comment by 1zun4** [comment]
It seems it was related to https://github.com/CaffeineMC/sodium-fabric/commit/19a25aace8929a3c6bc2221fb1117bf8abbabe44 instead. Sorry!
