### ISSUE TITLE
error: package net.minecraft.client does not exist import net.minecraft.client.MinecraftClient;

### ISSUE THREAD

**Issue by SyutoBestCoder** [asiekierka/MinecraftPOMF#3915]
I am trying to add a import to my mod and I am getting this error 

version 1.20.4
java version JDK-21

**Comment by Shnupbups** [comment]
Not an issue with Yarn

**Comment by SyutoBestCoder** [comment]
> Not an issue with Yarn

any idea how to fix it?

**Comment by Octol1ttle** [comment]
You can help with mod development from the [Fabric Discord server](https://discord.gg/v6v4pMv), or by asking a question on the [GitHub Discussion](https://github.com/orgs/FabricMC/discussions) forums.
