### ISSUE TITLE
Gui -> Screen

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#395]
Mojang's name for `Gui` is actually `Screen`, as we can see from many vanilla strings. This name makes a lot more sense than `Gui`:
 - Some GUIs don't extend `Gui` and several of those can be open at the same time (chat hud, debug hud, etc.)
 - The GUIs that extend `Gui` fill the whole *screen* and only one can be open at once. The name "screen" makes this clear

**Comment by asiekierka** [comment]
Should we move to *GuiScreen for overlaid screens? (container screens etc)

**Comment by Prospector** [comment]
No, I think just Screen (and even if we did go with Gui and Screen, it would be ScreenGui as a screen would be a type of gui)

**Comment by Prospector** [comment]
This can be closed
