### ISSUE TITLE
Sound fields are misnamed. Shifted by one. 

### ISSUE THREAD

**Issue by Darkhax** [asiekierka/MinecraftPOMF#40]
A great deal of the sound fields have incorrect names. They have been shifted upwards by one position. I attempted to fix this issue in my PR, but tasks like these are mind numbing, and there are a lot of sounds.

**Comment by darkevilmac** [comment]
Would this be the result of an update to minecraft? I'm 100% sure those mappings were accurate as I was mapping them.

**Comment by asiekierka** [comment]
Very likely.

It would be much easier to use a text editor to fix this in that case.
