### ISSUE TITLE
MobEnitityWithAi -> PathfinderMob

### ISSUE THREAD

**Issue by se7kn8** [asiekierka/MinecraftPOMF#400]
Mojangs name for `MobEntitityWithAi` seems to be `PathfinderMob`.

**Comment by liach** [comment]
Any reference? As far as I know, vanilla entity goal/ai system is bound with the path finding system and look/move/jump action categories as well.

**Comment by Runemoro** [comment]
1.13 used to contain the string `"Use NearestAttackableTargetGoal.class for PathfinerMob mobs!"`, but it seems like it's gone in the latest 1.14 snapshot.

**Comment by liach** [comment]
In my opinion, even if you use a name to indicate the entity's navigation ability, the name should be `PathfindingMob` or `NavigatingMob` instead.

**Comment by se7kn8** [comment]
The string from @Runemoro is currently in an obfuscated class, but yes, this is my source.

**Comment by Juuxel** [comment]
`PathfinderMob(Entity)` sounds good to me as well.

**Comment by liach** [comment]
I like #1463's `PathAwareEntity`/`FavoredPathingEntity` etc better
