### ISSUE TITLE
java.lang.RuntimeException: Unfixable conflicts

### ISSUE THREAD

**Issue by itzchrisi** [asiekierka/MinecraftPOMF#4051]
A problem occurred configuring root project 'LegendClient_Ingame'.
> Failed to setup Minecraft, java.lang.RuntimeException: Unfixable conflicts

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
