### ISSUE TITLE
The CocoaBeansTreeDecorator class does not involve cocoa beans

### ISSUE THREAD

**Issue by haykam821** [asiekierka/MinecraftPOMF#4060]

**Comment by Shnupbups** [comment]
Yes it does though? Or are you being pedantic because the block is just 'cocoa'? I guess we can rename it `CocoaTreeDecorator`...

**Comment by zOnlyKroks** [comment]
Imo this doesn't really matter all that much, but CocoaTreeDecorator would also make sense.
