### ISSUE TITLE
"burnable" ->"fuel"

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#416]
In AbstractFurnaceBlockEntity:
 - `addBurnable` -> `addFuel`
 - `createBurnableMap` -> `createFuelTimeMap`

Because:
 - This is the name Mojang uses, as shown by the furnace block entity NBT
 - This is the name commonly used by Minecraft players
 - The [Wikipedia article for "Furnace"](https://en.wikipedia.org/wiki/Furnace) uses "fuel" 16 times to refer to the heat source, yet doesn't use the word "burnable" a single time
 - Fuel makes sense even if a mod adds a non-burnable fuel, like lava buckets
 - "burnable" is an adjective, not a noun. It should be "addBurnableItem" and "createBurnableItemMap" even if we wanted to use "burnable"

**Comment by asiekierka** [comment]
OK
