### ISSUE TITLE
[potential Yarn issue] Eating food causes a particle crash

### ISSUE THREAD

**Issue by LemmaEOF** [asiekierka/MinecraftPOMF#440]
[crash-2019-02-01_16.02.39-client.txt](https://github.com/FabricMC/yarn/files/2823757/crash-2019-02-01_16.02.39-client.txt)
Happens when eating any food on 19w05a, untested in prod so not sure if it's Yarn or not

Using mappings 19w05a.6, loader 0.3.5.106, API 0.1.5.87

**Comment by asiekierka** [comment]
Ah no this is actually an issue with API probably

**Comment by asiekierka** [comment]
Fixed in latest build.
