### ISSUE TITLE
Vector3f.normalize() doesn't actually normalize

### ISSUE THREAD

**Issue by grondag** [asiekierka/MinecraftPOMF#442]
https://github.com/FabricMC/yarn/blob/3ad526eaee973c21db434f84e3519709c5102f17/mappings/net/minecraft/client/util/math/Vector3f.mapping#L25

The code looks like a normalize, but it's missing the square root on the sum of squares, so the resulting vector has something other than unit length.

What to do about this depends on Mojang's intent.  If it's a bug, maybe call it `normalizeIncorrectly()` until fixed?  That might prevent someone from figuring this out the hard way like I did. 

If it's intentional, then I really have no idea what this operation should be called. `almostNormalize()`?

It's only used in a couple places, and I didn't dig too deep but my guess is that it's unintentional, but the defect that doesn't matter significantly for the way they use it, which means odds of it getting fixed are small...

Would be an easy PR to make but would like guidance from people more familiar with mappings on how to handle an odd situation like this.

**Comment by Runemoro** [comment]
By dividing it by the length squared, it's inverting the length of the vector (L -> 1/L), so either `invertLength` (though someone could think that's L -> -L). `reciprocal`, or `dotInverse`/`dotProductInverse`?

Are you sure it's a bug? Inverting the length of a vector may be intentional.

**Comment by grondag** [comment]
I would indeed think "inverse" is -L, so I like your `reciprocal` idea better.  

Not sure it's a bug - that's why I wrote "guess."  Bug is still my guess tho, because adding that... _thing_, plus dot- and cross products but _not_ adding a proper normalize makes little sense.

On the other hand, add() accepts primitives but subtract() accepts a Vector3f(), so the class has an unfinished feel to it overall.  Maybe they never got around to it...
