### ISSUE TITLE
IWorld -> WorldGeneratable

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#448]
https://discordapp.com/channels/507304429255393322/521545796882006027/540468184546017280

As I see, the `IWorld` thing is usually used in off-thread world generation. For example, the method that initializes entities on spawn takes an `IWorld` instead of a `World` because the entity may be spawned in a structure during world generation. This thing is not world after all, but is something suitable for world generation, hence `WorldGeneratable` instead of `GeneratableWorld`.

**Comment by Niko-sk2x** [comment]
I disagree.

For world generation, all you *really* need is `getBlockState`, `setBlockState`, `getBlockEntity`, `getHeight` and maybe some entity spawning if you include entities in world generation.

This class does far more than that and really is a more or less general interface with almost everything `World` needs to do.

It's also used all over the `Block` methods, as an argument, with many of them taking a superclass of it with less functionality (and one of the implementations is a class used to access blocks from chunk batcher threads).

This interfacee also could allow for a world-generation-specific implementation of IWorld that could be specifically optimized for it (for example to avoid going through ChunkManager, and instead access chunks directly from an array), but world generation is jus one of the many places where it's used.

**Comment by liach** [comment]
no. you need a lot of methods to check environments for world generation, including persistent data access. if what you said is right, please explain that getWorld method in that interface

**Comment by Niko-sk2x** [comment]
Still doesn't change the fact that its used for a lot more things and it also has methods that aren't used for world generation at all.

**Comment by liach** [comment]
that is because mojang probably names it badly internally and devs start to misunderstand

**Comment by liach** [comment]
Hmm, if we rename `IWorld` to `World`, what would the current `World` become? The main difference then is that `World` is sync and `IWorld` can be async.

**Comment by Niko-sk2x** [comment]
The main difference is that World is an abstract class that partially implements IWorld, while IWorld is a more general interface.

If World can't be named `BaseWorld` or `AbstractWorld`, ths current naming is probably the best you can get.

**Comment by LemmaEOF** [comment]
Someone over in the discord recommended changing it to `ProtoWorld`, based on the official Mojang name `ProtoChunk`.

**Comment by Player3324** [comment]
Proto implies a temporal relationship ("first version"/replaced later) instead of inheritance (derived/base still around). In the case case of "ProtoChunk", this kind of Chunk should be what is being used during world gen then replaced with a new Chunk instance once finished. If that's not the case Mojang's name choice is not good.

AbstractWorld should be reasonable for the base impl class if it's not taken, freeing World for the interface. This is the standard Java naming convention, I'd even go as far as using Abstract* for any base class that will be used with sub classes exclusively, even if it lacks the "abstract" modifier - the behavior is what matters.

**Comment by asiekierka** [comment]
I wouldn't be surprised if ProtoChunk/ProtoWorld are the interfaces which Mojang is trying to replace all usages of Chunk/World across the codebase with, eventually.

This is why I wouldn't want to use AbstractWorld yet - outside of fresh 1.13+ code, it's still the argument passed and the form you're expected to pass around worlds in.

**Comment by liach** [comment]
Closing. Will not work on this recently.
