### ISSUE TITLE
FontRenderer -> TextRenderer

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#465]
It actually renders text not fonts.

**Comment by 3TUSK** [comment]
> renders text not fonts

~~Call it `GlyphRenderer`~~

**Comment by Runemoro** [comment]
We already have `GlyphRenderer`. That renders a single type of glyph.

**Comment by 3TUSK** [comment]
Oops. Should have looked it up before dumping the differences between font, typeface and glyph...
