### ISSUE TITLE
move C2S/S2C to the front of names

### ISSUE THREAD

**Issue by LemmaEOF** [asiekierka/MinecraftPOMF#467]
ex. `TitleS2CPacket` -> `S2CTitlePacket`

**Comment by Runemoro** [comment]
And also rename them to anything that doesn't contain a number in the name

**Comment by Blayyke** [comment]
S2C is fine as it is IMO (at the start tho ofc)

**Comment by LemmaEOF** [comment]
Let's have that debate in a separate issue. It's not the goal of this, so it's not worth clogging up this issue with.

**Comment by asiekierka** [comment]
>And also rename them to anything that doesn't contain a number in the name

Fastutil first.

**Comment by YanisBft** [comment]
Any more input for this? I feel like this is really unnecessary and doesn't improve the names (and also makes it harder to find classes in tree view)

**Comment by Technici4n** [comment]
Same thing as `Block` suffix vs prefix imo... I am against this.

**Comment by YanisBft** [comment]
Closing this as people seem to not want such a refactor. If someone thinks this should still happen, please open a new issue/PR
