### ISSUE TITLE
ItemCooldownManager#isCooldown(ItemStack) dosen't make sense

### ISSUE THREAD

**Issue by raphydaphy** [asiekierka/MinecraftPOMF#488]
As it says in the title, `isCooldown` doesn't convey what the method does very well (it returns true if the stack has an active cooldown). `hasCooldown` or similar would be more appropriate and improve readability.

**Comment by asiekierka** [comment]
Why not ItemCooldownManager#isActive()?

**Comment by Runemoro** [comment]
> Why not ItemCooldownManager#isActive()?

To me that would mean that the item *isn't* cooling down.

Why not just `isCoolingDown`?
