### ISSUE TITLE
BlockPos -> Position

### ISSUE THREAD

**Issue by ChloeDawn** [asiekierka/MinecraftPOMF#490]
Feedback ticket for a controversial proposal. Reasons for and against this are much appreciated. "`BlockPos` is the known Mojang name" is not a valid argument in my opinion. Many classes have known Mojang names that are not used. I argue that `BlockPos` is actively used for more than just blocks. `Position` is a more generic representation of an int-based position vector.

**Comment by SquidDev** [comment]
The "nice" thing about `BlockPos` is that it indicates it's clamped to the coordinate grid. `Position` feels more vague (more suited for `Vec3f`), and doesn't really take into account the coordinate-grid specific methods that you have (such as offsetting by a direction).

**Comment by asiekierka** [comment]
Position is more suited for floating-point vectors.

**Comment by LemmaEOF** [comment]
Yeah, I'm gonna say that if we change `BlockPos` we still need to emphasize that it's an integer.

**Comment by ChloeDawn** [comment]
The feedback is appreciated and I do agree that this name would be more fit to a floating point vector.

**Comment by liach** [comment]
If you feel too bored, you can call it `IntegerLattice` instead

**Comment by Runemoro** [comment]
> you can call it IntegerLattice instead

The lattice is the set of all points. It would have to be IntegerLatticePoint/IntegerLatticePosition
