### ISSUE TITLE
Block.friction and related methods/fields are actually the opposite

### ISSUE THREAD

**Issue by squeek502** [asiekierka/MinecraftPOMF#499]
The `Block.friction` field and all its related fields/methods (`Block.Settings.friction`, etc) actually work such that a higher value means *less friction* and a lower value means *more friction*. For example, ice sets this field to 0.98 while the default is set to 0.6.

Can't really come up with too many good names. Maybe `frictionlessness`? Any one have better ideas?

**Comment by liach** [comment]
`resistance` `drag`

**Comment by squeek502** [comment]
> `resistance` `drag`

Need the reverse of those. Again, the higher the value of the field, the *less* friction/resistance/drag it has.

`sleekness`? `slickness`?

**Comment by liach** [comment]
`smoothness` `motionSmoothness`

**Comment by copygirl** [comment]
IMO it's still `friction`, just a multiplicatively applied factor. (Is that proper English?)
Perhaps to make this more clear you could name it `frictionFactor`.

**Comment by ChloeDawn** [comment]
`collisionInertia`

**Comment by squeek502** [comment]
Did some testing, and it's significantly weirder than I remembered. It doesn't really map cleanly to friction or slickness, because Minecraft's movement is totally strange. Here's what happens:

- If the value is low enough, you accelerate/stop extremely quickly and your movement speed also increases. For example, a value of 0.25 increases your walk speed to 1.75 blocks/tick
- With the default value of 0.6 that almost all blocks use, walk speed is 0.22 blocks/tick
- On ice (value=0.98) your acceleration/deceleration is slower and your walk speed is slightly slower at 0.21 blocks/tick
- If you set the value to 1.0 (a tiny bit higher than the ice value), you still accel/decel slow but your walk speed increases to 0.23 blocks/tick
- If you set the value to 1.1, you accel/decel really slow but your movement speed becomes unbounded, and you actually accelerate even while not pressing any movement keys at all (assuming you're not at a stand still)

So maybe it makes sense to think of it more in terms of acceleration...?

**Comment by copygirl** [comment]
> * If the value is low enough, you accelerate/stop extremely quickly and your movement speed also increases. For example, a value of 0.25 increases your walk speed to 1.75 blocks/tick

I wonder if that's an "error" in the acceleration method for low values and actually unintended.

**Comment by squeek502** [comment]
> I wonder if that's an "error" in the acceleration method for low values and actually unintended.

It's a side-effect of how the movement code in Minecraft works, so it's hard to tell if it's intended or not (my guess is it's in the realm of 'it works as long as we don't set the field to those low/high values, so we'll just not do that'). It's an extremely weird implementation all around, which makes naming things really tough.

**Comment by Runemoro** [comment]
`slipperiness`

> It doesn't really map cleanly to friction or slickness, because Minecraft's movement is totally strange.

This all makes sense. You need to walk slower on slippery surfaces to avoid falling.
