### ISSUE TITLE
Make yarn use intermediary names

### ISSUE THREAD

**Issue by shedaniel** [asiekierka/MinecraftPOMF#503]
Make yarn use intermediary names instead of Mojang names.
I feel like this can surely help PRs as they won't be broken by every Wednesday.

**Comment by modmuss50** [comment]
This is something we have had on the back of our minds for a while, it should help. Once engima is known to be stable we might be able to look into it some more.

All the gradle tasks for making an intermediary jar are currently present in yarn.
