### ISSUE TITLE
StringItem -> PlaceableItem

### ISSUE THREAD

**Issue by LemmaEOF** [asiekierka/MinecraftPOMF#525]
StringItem is now a generic class for any item that has a separate Block as a placeable form. This includes string as well as all seeds, carrots, potatoes, sweet berries, cocoa beans, nether wart, and redstone dust. Given this, I think the class should be renamed to reflect its new usage.

**Comment by Prospector** [comment]
It's not a placeable item, it's an ItemBlock with a different translation key from the block.

**Comment by Prospector** [comment]
perhaps `DistinctBlockItem`

**Comment by Daomephsta** [comment]
How about `AliasedBlockItem`?
