### ISSUE TITLE
Make field names match NBT names

### ISSUE THREAD

**Issue by freundTech** [asiekierka/MinecraftPOMF#545]
I noticed that in VillagerEntity the field names don't always match the names of the NBT tags they get stored in. I haven't checked if other entities are also affected yet.

For example `this.experience` is called "Xp" in NBT,`this.gossip` is "Gossips" and `this.buddyGolemId` is "BuddyGolem"  
I would suggest renaming them to `this.xp`, `this.gossips`, and `this.buddyGolem` respectively.
(Or maybe leave golem and just rename the other two, as that's kind of a special case)

If people agree with this I can also create a PR.

**Comment by liach** [comment]
no. an example comes from villager called willing; it is too ambiguous compared to willing to mate.

**Comment by liach** [comment]
Any more feedback on this?

**Comment by YanisBft** [comment]
We generally try to match NBT names, unless they are confusing or just wrong. If someone thinks this is an issue in yarn, please reopen an issue
