### ISSUE TITLE
Issue with MemoryModuleType.GOLEM_SPAWN_CONDITIONS mapping

### ISSUE THREAD

**Issue by DeadlyMC** [asiekierka/MinecraftPOMF#552]

**Comment by modmuss50** [comment]
What’s the issue?

**Comment by DeadlyMC** [comment]
https://pastebin.com/BEjZtRKj
I get this crash...
According to one of the guys from discord this is due to mappings (Can't access field or something)
In #user-general

**Comment by modmuss50** [comment]
Im not seeing anything wrong with the mappings. this is very little to go off.

**Comment by Runemoro** [comment]
Are all your mods for 19w12b?

**Comment by DeadlyMC** [comment]
Yes they are

**Comment by Prospector** [comment]
either way this has nothing to do with yarn, if anything it would be a bug in loom or something so it can be closed here

**Comment by DeadlyMC** [comment]
Please make sure to address this issue though
