### ISSUE TITLE
vehicle and riddenEntity

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#589]
We currently have:
 - hasVehicle
 - getRiddenEntity

One of them should be changed for consistency (isRiding or getVehicle), but which one?

I'm not sure either "vehicle" or "riding entity" accurately describe what it does since a horse isn't really a "vehicle", and you're not really "riding" a boat.

**Comment by Blayyke** [comment]
Imo vehicle is the better name. A horse is more of a vehicle than a boat is ridden I'd say. A middle ground would be preferable to either of these though, however I don't know of one.

**Comment by ChloeDawn** [comment]
"Vehicle" is the name Mojang use

See `Entity's Vehicle` in `Entity#populateCrashReport`
See `multiplayer.disconnect.invalid_vehicle_movement` in localization
See `{} was kicked for floating a vehicle too long!` in `ServerPlayNetworkHandler#method_18784`
See `{} (vehicle of {}) moved too quickly! {},{},{}` in `ServerPlayNetworkHandler#onVehicleMove`
