### ISSUE TITLE
LivingEntity.isChild -> isBaby

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#594]
`isChild` would mean the mob has a parent (was created by breeding two other mobs), which doesn't mean the mob is still a baby, and isn't always the case for baby mobs.

Also, Mojang seems to call "child" mobs "babies" since the `villager_babies` sensor checks if `villager.isChild()`. Most people also use "baby chicken", not "child chicken".

**Comment by Cynosphere** [comment]
Models also use isChild as a field to scale it down, which would also need to be changed.
