### ISSUE TITLE
init or initialize?

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#618]
There are many `init` methods and many `initialize` methods. We should pick one for consistency.

**Comment by liach** [comment]
`init`.

**Comment by Runemoro** [comment]
`initialize`.

Vote for either me or liach.

**Comment by asiekierka** [comment]
Mojang uses init, and for the 1.14 cycle we're sticking with deobf Mojang names, so... I think the answer is clear-cut, at least for now.

**Comment by Prospector** [comment]
close?

**Comment by Runemoro** [comment]
Was this fixed yet?

**Comment by Prospector** [comment]
oh maybe not but it sounds like we're going with init

**Comment by valoeghese** [comment]
Is this fixed yet :thinking:

**Comment by Runemoro** [comment]
Yes, it seems like `initialize` is gone.
