### ISSUE TITLE
ParticleParameters -> ParticleEffect

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#619]
```java
LOGGER.warn("Could not spawn particle effect {}", packet.getParameters());
```

The name "particle parameters" would be a better name for something that's passed along with the particle type to configure it, but here the particle parameters is all the necessary information to spawn the particle (including the type).

**Comment by liach** [comment]
The `ParticleParameters` itself looks more like an instance of a particle. Hence I suggest just `Particle`.
The structure of `ParticleType<T extends ParticleParameters>` -> `ParticleParameters` is much like that of `EntityType<T extends Entity>` -> `Entity` and `BlockEntityType<T extends BlockEntity>` -> `BlockEntity`.

**Comment by Runemoro** [comment]
> Hence I suggest just Particle.

`Particle` is taken by the client-side `Particle` class. The `ParticleParameters` is the "particle effect" class which exists on both sides and used by the client to spawn one or more particles.

**Comment by liach** [comment]
Hmm, the parameters should be fine... note that this parameters thing also carries the id information of the particle.

**Comment by JamiesWhiteShirt** [comment]
Parameter does not have to mean parameter strictly in the Java sense. ParticleParameters contains the parameters used to spawn a particle. It does not mean it has to be the exact object used as parameters to spawn it.

However, I think ParticleEffect is a better name, just disagreeing with the reasoning behind it.

**Comment by Blayyke** [comment]
+1 for ParticleEffect. Would make more sense, and the log message reinforces it.
