### ISSUE TITLE
Two classes named "Rotation"

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#630]
There are currently two classes named `Rotation`:

`net.minecraft.util.Rotation`:
```java
public enum Rotation {
    ROT_0,
    ROT_90,
    ROT_180,
    ROT_270;
```

`net.minecraft.util.math.Rotation`:
```java
public class Rotation {
    protected final float x;
    protected final float y;
    protected final float z;
```

One solution would be to name the first to `OrthogonalRotation`. Does anyone have any other ideas?

**Comment by liach** [comment]
Where is `OrthogonalRotation` used? If it is used only in block/structures, we can call it `BlockRotations`

Edit: or `StructureRotations`

**Comment by Runemoro** [comment]
It's used in many places, including as a parameter to BlockState.rotate()

**Comment by liach** [comment]
Any non-block/voxel usage?

**Comment by Runemoro** [comment]
It doesn't seem like it. BlockRotation could work.
