### ISSUE TITLE
yaw -> yRotation, pitch -> xRotation

### ISSUE THREAD

**Issue by NeunEinser** [asiekierka/MinecraftPOMF#632]
While yaw and pitch are the correct technical terms, I find them hard to understand and learn. I don't know how commonly they are used in English language, but being a non-native speaker, I never heard of them before.
The game does use `y_rotation` and `x_rotation` in selector arguments for these things. They are also, imo, more clear and it's more obvious what they mean if you don't know the technical terms.

**Comment by Pyrofab** [comment]
It is true that those terms are not used much. In fact, I didn't even know their equivalent in my native language until 5 minutes ago. However, they are easy to find and to understand, so I don't think it is an issue. They are also fairly common in video game jargon.
However, if Mojang uses different terms, it may be a change to consider.

**Comment by NeunEinser** [comment]
Well, at least I have to google which way around they are every time they come up, which is not very helpful. y and x rotation just have their meanings in the name.

**Comment by Pyrofab** [comment]
I'd rather learn a correct term that I may encounter in other codebases than rename stuff to avoid it, but that may be just me.

**Comment by Runemoro** [comment]
"x rotation" is more confusing than pitch. 

The pitch is the angle between the vector and the xz plane, it's only a rotation around the x axis if the vector is on the yz plane.

Also, while the terms "x rotation" and "y rotation" are rotations *around* the x and y axes, someone could interpret them as being angles from those axes, which makes them something completely different.

**Comment by Player3324** [comment]
Using a body-fixed xyz coordinate system that is distinct from the world-space xyz coordinate system to describe the rotation axis is much more confusing than the aeronautic terms. None of the body-fixed axes necessarily relate to the world space axes, it's just incidentally the case depending on the actual rotation values and order. Likewise e.g. the yz planes are potentially different.

**Comment by NeunEinser** [comment]
It's always around the world x/y axes. It's the rotation around the world's x axis and around the world's y axis. Always and ever in the contextes they are used.
That they could mean different things outside of Minecraft just does not matter imho, since we are talking about Minecraft mappings and not about mappings of an aeronautic system software.

Plus, as I said, Mojang also uses this naming convention.

**Comment by Runemoro** [comment]
> It's always around the world x/y axes

That's false. Rotating the vector (1, 0, 0) around the x axis does nothing. Changing its pitch, which means rotating it in the plane containing it and the y axis (or equivalently, around the xz-plane vector orthogonal to its projection on the xz plane, in this case the z axis) does something.

**Comment by NeunEinser** [comment]
Well, yes, but it's still, if you go from the default looking vector, around these axis exactly.

I still think these names would be better but since there doesn't seem to be much (or better: any) support for this, I am closing this now.

**Comment by Runemoro** [comment]
> if you go from the default looking vector

That's not always the case. I would expect a `setXRotation` method to do nothing if the vector is on the x axis, but a `setPitch` command to do something.
