### ISSUE TITLE
The mysterious neighborUpdate boolean

### ISSUE THREAD

**Issue by asiekierka** [asiekierka/MinecraftPOMF#634]
neighborUpdate received a boolean argument at the end some time ago. This is always false, unless if called through onBlockAdded/onBlockRemoved (which also have a same-meaning boolean argument added at the end), conversely those are called through Chunk.setBlockState (which is also now with a boolean argument at the end), which corresponds to flag 0x40 in World.setBlockState.

This flag seems to be emitted by at least Pistons, and at least one thing it controls is AbstractRailBlock's stack dropping (if boolean is true, the rail item is *not* dropped). I wonder if it's related to removing and placing blocks while a piston is being moved.

Please help figure out its intended use!

**Comment by NeunEinser** [comment]
I am currently not in a location were I can look at code, but that sounds like the "fix" (hack fix and semi-working) for tnt duping introduced during 1.13.
It prevents that additional block updates are sent, which in the case of activator rails is blockupdates through blocks (removal of redstone source)
If it prevents item dropping, it might be something slightly different too, but a flag for additional block updates exists, I am very certain.

**Comment by NeunEinser** [comment]
This youtube video is btw a good source about block updates after 1.13, specifically with pistons.
https://youtu.be/V5GkTTVaIEE

**Comment by Runemoro** [comment]
The same boolean is passed to `onBlockAdded` and `onBlockRemoved` too.

It seems to skip *some* block place/break/update actions such as rail drops and redstone neighbor updates, but not all (for example, chests will still drop their inventory even with the boolean set to true).

**Comment by hea3ven** [comment]
Wasn't there a bug where if you moved a rail with a piston (not sure if there were extra conditions) the rail block would be moved, but it would also spawn an item entity for the rail, thus dupping the rails? maybe it's a "fix" for that.

**Comment by Runemoro** [comment]
So maybe it should be named `moved` (the block added/removed was just moved from/to another position)?
