### ISSUE TITLE
Inconsistencies with loot table's Serializer vs Factory and (de)serialize vs (from/to)Json

### ISSUE THREAD

**Issue by NeunEinser** [asiekierka/MinecraftPOMF#636]
When working with loot table mappings, I found the inconsistency with these namings quite confusing. Here is a list of how it's done differently.

Package `net.minecraft.world.loot` (all classes):
- Inner class name: `Serializer`. 
- Implement `com.google.gson.JsonDeserializer` and `.JsonSerializer`
- Inherit `deserialize` and `serialize` namings from gson.
- No further methods

Package `net.minecraft.world.loot.entry`
- `LootEntries`:
  - Inner class name: `Serializer`
  - Implements `JsonDeserialiser` and `JsonSerializer`.
  - Calls `fromJson` and `toJson` of LootEntry classes using a registry, depending on an identifier.
  - Additional method: `getSerializer` (static): Takes a class and returns corresponding serializer.
- `LootEntry` and extending classes:
  - Inner class name: `Serializer`
  - Method names: `toJson` and `fromJson`
  - Additional methods:
    - `getIdentifier`: Returns identifier of entry.
    - `getType`: returns outer class as `Class<T>`

Package `net.minecraft.world.loot.condition` and `net.minecraft.world.loot.function`
- `LootConditions`/`LootFunctions`:
  - Inner class name: `Factory`
  - Implements `JsonDeserialiser` and `JsonSerializer`.
  - Calls `fromJson` and `toJson` of LootCondition classes using a registry, depending on an identifier.
  - No additional methods
- `LootCondition`/`LootFunction` and extending classes:
  - Inner class name: `Factory`
  - Method names:  `toJson` and `fromJson`
  - Additional methods:
    - `getId`: Returns identifier of entry.
    - `getConditionClass`/`getFunctionClass`: returns outer class as `Class<T>`
- `ApplyBonusLootFunction`:
  - Inner `Formula` class (with extending classes)
  - Has `toJson` and (static) `fromJson`, different implementations than other classes.
    - toJson modifies a given json object and adds stuff from own field names to it
    - fromJson returns a new instance of the class using a given json object and context.
  - Has additional methods.

I suggset to change everything to `Serializer` and `(de)serialize`, apart from the `Formula` classes from `ApplyBonusLootFunction`, which has different implementations of to and from json.

**Comment by liach** [comment]
to/from json names are chosen for they are more concise, especially when something can be converted to both nbt, json, and packet (e.g. advancement)

**Comment by NeunEinser** [comment]
I think I read from @Runemoro that deserialize and serialize are to be used in Serializer classes, while to and from Json are methods that convert to or from their own classes direcly.
Also we can't really change methods of classes that implement `com.google.gson`'s `JsonSerializer` and `JsonDeserializer`.

That's why I suggset to make it consistent and use Serializer namings for `net.minecraft.world.loot`, except for `ApplyBonusLootFunction`'s `Formula` class which does convert from and to its own class.

**Comment by liach** [comment]
I support calling all of these `Factory`.
