### ISSUE TITLE
Rename Goal.owner

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#661]
The naming of the "owner" field in `Goal` is inconsistent. Around half are named `owner`, and the other half are named `horse`, `cat`, `dolphin`, etc.

I suggest we rename `owner` to the entity type since:
 - Goals extend each other, and sometimes the subclass also has an owner field with a more specific type, which needs to have a different name than the superclass field
 - In some cases owner is confusing (for example, in AttackWithOwnerGoal, we have both `owner`, the owner of the goal, and `ownerOwner`, the owner of the owner of the goal)
 - Naming the owner based on the entity type makes it clear what kind of entity it is without having to look at the top of the class

**Comment by liach** [comment]
We should use the entity type till mojang makes goals have a generic parameter for its owner type like brain class does.

**Comment by YanisBft** [comment]
Fixed with #657 , can be closed
