### ISSUE TITLE
ChunkBatcher named wrong

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#662]
Based on the thread names, the `ChunkBatcher` are the *threads* created by the class currently named `ChunkBatcher`:

```java
private static final ThreadFactory THREAD_FACTORY = new ThreadFactoryBuilder().setNameFormat("Chunk Batcher %d").setDaemon(true).setUncaughtExceptionHandler(new UncaughtExceptionLogger(LOGGER)).build();
```

**Comment by liach** [comment]
Uh not really.
```java
crashReport5 = CrashReport.create(throwable, "Batching chunks");
```
This is straight from the method that is sent to the mailbox processor in the current Chunk Batcher. The name is ok. (19w40a)

**Comment by Runemoro** [comment]
No, we have many chunk batchers running at once, but only a single instance of `ChunkBatcher` at once (check this in debug). Therefore `ChunkBatcher` isn't the chunk batcher, it's responsible for creating chunk batchers.

**Comment by Runemoro** [comment]
I don't think there is a class that should be named `ChunkBatcher`, "Chunk Batcher" is the name of the thread, but the logic is spread out over different classes. Maybe we can call it something like `ChunkRenderSystem`?

**Comment by liach** [comment]
that class has changed in the recent updates. feel free to revisit.
