### ISSUE TITLE
maximum/minimum or max/min?

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#672]
Both are used right now, with maximum/minimum being slightly more common. We should agree on one for consistency.

**Comment by Runemoro** [comment]
Vote up this comment for maximum/minimum.

**Comment by Runemoro** [comment]
Vote up this comment for max/min.

**Comment by liach** [comment]
`max` `min` has been widely accepted as an abbreviation and appears more frequently in the parts that I touch in yarn.

**Comment by Prospector** [comment]
I can't think of any reason you'd ever want just a longer name that means the same thing. Usually max and min are just part of a name like a prefix or suffix so I think it's good

**Comment by Runemoro** [comment]
> I can't think of any reason you'd ever want just a longer name that means the same thing. Usually max and min are just part of a name like a prefix or suffix so I think it's good

Sur, I agre. Its muc mor readbl 2 us shrtr abbrvtins thn ful wrds.

**Comment by liach** [comment]
11 for `max`/`min` versus 2 `maximum`/`minimum`, the result is pretty clear.
![image](https://user-images.githubusercontent.com/7806504/66449282-25753b80-ea1a-11e9-8cfc-2e68c2d27254.png)

**Comment by Pyrofab** [comment]
Is the mismatch still an issue currently ? If so, I think this issue should remain open as long as the names are not fixed.

**Comment by liach** [comment]
There are like 4 or 5 mismatches still. Good point.
https://github.com/FabricMC/yarn/search?q=minimum&unscoped_q=minimum
