### ISSUE TITLE
Move all classes used by blaze3d classes to com.mojang.blaze3d package

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#673]
Some classes aren't really client-dedicated such as Snooper. Moreover, those used classes are more or less rendering libraries instead of classes that perform rendering logic.

**Comment by Runemoro** [comment]
Yes, based on the class name order, all classes between `ctb` and `cut` belong in blaze3d: https://gist.github.com/Runemoro/e8c45aabc8f7048d0414e42ea338d510

Snooper is probably misnamed. It has nothing to do with the snooper.

**Comment by asiekierka** [comment]
I think we should just wait for the full adaptation to your/jamierocks's notes and order-based information which I want to pull off on the 1.15 snapshot jump.

**Comment by liach** [comment]
most mojang packaging is fine, though we maty revise some (like the package for text)

**Comment by liach** [comment]
I want to close this one because this will cause some classes like SystemUtil be moved to b3d package (while it never belongs there)

**Comment by Runemoro** [comment]
`SystemUtil` isn't in the blaze3d package, it's in `net.minecraft`. See https://gist.github.com/Runemoro/e8c45aabc8f7048d0414e42ea338d510.

**Comment by liach** [comment]
but it was used by b3d so according to my old logic it will go com mojamg, which is wrong

**Comment by Runemoro** [comment]
Still, I personally think the blaze3d classes should be separated from the rest. We don't have to use `com.mojang.blaze3d` (though I don't see why not), but putting everything in `net.minecraft.render` doesn't make sense. It's clearly a separate, almost independent, library, and I'm guessing that they will eventually make it fully independent (are they still planning on open-sourcing it?)

**Comment by liach** [comment]
I'd wait for mojang to cut it clean before we cut it clean
