### ISSUE TITLE
net.minecraft.util.Void -> Unit

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#676]
It should be renamed to avoid having the same name as `java.lang.Void`. It's exactly the same as https://github.com/Mojang/DataFixerUpper/blob/master/src/main/java/com/mojang/datafixers/util/Unit.java except for not having a `toString` method.

**Comment by liach** [comment]
Yes please! Let's do it!

**Comment by ChloeDawn** [comment]
Imo `Nothing` would better represent an absence of value

**Comment by liach** [comment]
`Unit` is used by Kotlin and has been known as an absence of value as well.

**Comment by NeunEinser** [comment]
Unit sounds like a bad name for that, though, as it means something completely different in English. I never heard of unit being used that way.

**Comment by Runemoro** [comment]
@NeunEinser It's the [unit type](https://en.wikipedia.org/wiki/Unit_type).

**Comment by ChloeDawn** [comment]
#679

**Comment by Juuxel** [comment]
IMO `Unit` would be a good name.
