### ISSUE TITLE
Drop verbose 'Inv' wording from Inventrory methods.

### ISSUE THREAD

**Issue by modmuss50** [asiekierka/MinecraftPOMF#682]
Drops 'Inv' from all Inventory methods. What else am i getting a stack on? A carrot?
Named afg(class_3829) -> PasteCallback, its only ever called by things that 'paste' a BlockEntity in world and its not specific to Inventories, although its only implemented by Inventory inheritors and JukeboxBlockEntity, still not 100% on the name imo, feedback would be nice.

Taken from #330

**Comment by NeunEinser** [comment]
> Im for it, but I suggest keeping it on 
> 
>  `getInvSize` 
> `getInvWidth`
>  `canPlayerUseInv`
> `setInvProperty`
> `onInvOpen`
> `isInvEmpty`
> `getInvProperty`
> `onInvClose`
> `getInvPropertyCount`
> `getInvHeight`
> 
> This would leave us with the following changes
> 
> `getInvStack` -> `getStack`
> `takeInvStack` -> `takeStack`
> `setInvStack` -> `setStack`
> `getInvMaxStackAmount` -> `getMaxStackAmount`
> `removeInvStack` -> `removeStack`
> `isValidInvStack` -> `isValidStack`

_Originally posted by @modmuss50 in https://github.com/FabricMC/yarn/pull/330#issuecomment-449591284_

I think this sounds like a good approach. It's not clear that `setHeight` refers to the inventory's height, hence `setInvHeight`, it is however clear that `setStack` is something that happens in the inventory.

**Comment by liach** [comment]
My concern is name clashes with other methods, e.g. that two get world methods with different name+signature in hopper minecart (apparently entity and block entity have get world methods that are named differently)

**Comment by YanisBft** [comment]
Fixed by #1154
