### ISSUE TITLE
EntitySize -> EntityDimensions

### ISSUE THREAD

**Issue by Sollace** [asiekierka/MinecraftPOMF#715]
EntityDimensions and all the fields there-in are indirectly confirmed by Mojang through string constants in their code:

```
   public String toString() {
      return "EntityDimensions w=" + this.width + ", h=" + this.height + ", fixed=" + this.constant;
   }
```

EntitySize -> EntityDimensions
EntitySize.constant -> EntityDimensions.constant

In addition to that, I would also change these two methods to be more in line with what they seem to be doing:

EntitySize.resizeable(...) -> EntityDimensions.changing(...)
EntitySize.constant(...) -> EntityDimensions.fixed(...)

**Comment by ChloeDawn** [comment]
It was decided after discussion that EntitySize better represents this data class. I believe constant is fine too, representing an immutable size. Imo fixed doesn't really imply that well.

**Comment by Pyrofab** [comment]
I am personally not fond of having class names differ from the string representation, especially when the name is not particularly bad. It's just confusing to have blatant conflicting information.

**Comment by liach** [comment]
this mojang is indeed a bad obe. we have dimensions for worlds already! but the rename from constant to fixed i support.

**Comment by liach** [comment]
on a side note, i initially mapped this class before mojang overrode the toString method. we should add to the guideline about whether we are mapping to mojang names (which are sometimes incorrect or off) or correct names.

**Comment by Runemoro** [comment]
EntitySize is wrong. [The word "size" means only one value, and using it to refer to the dimensions of an object is bad English.](https://www.google.com/search?q=size+definition)

This class represents the *dimensions* of an entity (width, height), not the *size* of the entity (big, small). In fact, I think we already have another `getEntitySize` method somewhere (in the slime entity?) that returns a single number.

**Comment by Prospector** [comment]
This would be a good issue to get a PR going for

**Comment by liach** [comment]
`EntityDimensions` should be good as long as we call it `Dimensions` instead of `Dimension`. See the second definition at https://www.dictionary.com/browse/dimension

**Comment by Runemoro** [comment]
Yes, `Dimensions`, since it's a pair of two dimensions (width and height).

**Comment by Prospector** [comment]
EntityDimensions is literally what it says in the issue name and string...

**Comment by Sollace** [comment]
If everyone is on the side of doing a PR I can get one going later today.

Abd yes, I mean to say `Dimensions` not `Dimension`.

**Comment by Prospector** [comment]
Yup, go for it

**Comment by Sollace** [comment]
PR: https://github.com/FabricMC/yarn/pull/745
