### ISSUE TITLE
Consistency in client.network.packet

### ISSUE THREAD

**Issue by ExtraCrafTX** [asiekierka/MinecraftPOMF#773]
In order to be consistent with the other packets:
* [`OpenContainerPacket`](https://github.com/FabricMC/yarn/blob/1.14.3/mappings/net/minecraft/client/network/packet/OpenContainerPacket.mapping) -> `OpenContainerS2CPacket`
* [`SetTradeOffersPacket`](https://github.com/FabricMC/yarn/blob/1.14.3/mappings/net/minecraft/client/network/packet/SetTradeOffersPacket.mapping) -> `SetTradeOffersS2CPacket`

**Comment by liach** [comment]
Fixed in 4a2fe5bd1b2de0e8343f1ffb109717b77849ce78
