### ISSUE TITLE
SystemUtil -> ?

### ISSUE THREAD

**Issue by quat1024** [asiekierka/MinecraftPOMF#774]
`SystemUtil` contains a bunch of static methods. Some of them relate to a "system":

* fine-grained timers
* current operating system
* JVM flags

But many others are completely unrelated:

* patching miscellaneous holes in the Java standard library (`ifPresentOrElse`, `thenCombine`, `completeExceptionally`, `consume`, `get`, `toMap`, ...)
* a bit about the server worker
* reading and writing UUIDs from `Dynamic`s
* an identity hash strategy
* something about translation keys? lol

It appears to be less of a system-related class and more just a dumping ground for random functions that are too small to break into their own named helper class but too broadly applicable to keep near one call site.

Should this class be renamed?

Some suggestions being thrown around on Discord:

* `Misc`
* `Util`
* `Useful`
* `Varia`
* `Helper`
* `Etc`
* ~~Funny comedy suggesions:~~
  * ~~`Junk`~~
  * ~~`Stuff`~~
  * ~~`MiscellaneousGameSystemUtilities`~~
  * ~~`BucketOShi`~~

**Comment by kashike** [comment]
`Util` gets my vote. Simple and to the point.

**Comment by valoeghese** [comment]
Name it `ClassThatWeHaveNoIdeaWhatToNamePleaseHelp`

**Comment by Prospector** [comment]
I'd go with MinecraftUtil personally but also kashike is god so Util 👍

**Comment by Sollace** [comment]
Util  is good, however it does seem like the majority of the functions are system related. System also doesn't necessarily have to mean _just_ the Operating System. Patching Std lib functions, Uuid serialization, and anything with hashing sounds to me as something that technically qualifies as "system utilities". Not the OS system, but the Java system, they're just so low level. Just `Sys` would work.

There are also other naming strageties I've used such as `Objects`/`Strings`/`Collections`/etc...

**Comment by asiekierka** [comment]
Generally, kashike has a lot of wisdom here, so I'd go with Util.

**Comment by liach** [comment]
I personally support `Misc`.
