### ISSUE TITLE
Naming the two sets of old values in nm.entity.Entity

### ISSUE THREAD

**Issue by iamgreaser** [asiekierka/MinecraftPOMF#78]
Currently we have oldX/oldY/oldZ and M/N/O (the latter has not been deobf'd).

I'm thinking lerpX/lerpY/lerpZ would be good names for M/N/O. They are not as heavily used as oldXYZ.

Here's what they are used for anyway:
- oldXYZ is for the previous physical position and is used in physics calculations.
- MNO is for the previous visible position and is used for linearly interpolating visible positions between ticks.

Most cases of MNO look like this:

```
    this.c = this.b.M + (this.b.x - this.b.M) * a1;
    this.d = this.b.N + (this.b.y - this.b.N) * a1;
    this.e = this.b.O + (this.b.z - this.b.O) * a1;
```

Or this:

```
    this.M = this.x;
    this.N = this.y;
    this.O = this.z;
```

EntityRendererEntity has an exception, however this is similar to the first case:

```
    EntityRenderer.a(a1.getBoundingBox(), a2 - a1.M, a3 - a1.N, a4 - a1.O);
```

**Comment by copygirl** [comment]
Alternative names would be `prevPhysXYZ` and `prevVisXYZ` / `prevRenderXYZ` (or `old` / whatever instead of `prev`). This way it'd be more obvious what these are used for. Though I do like the sound of `lerpXYZ` for M/N/O, too. Would prefer `lerp`, but I wanted to throw this in as well, since it was mentioned in the IRC chat.

**Comment by maxpowa** [comment]
Using `lerp` here doesn't really make sense for MNO, as it's not actually a value that's come as a result of a linear interpolation, but rather a value that's used to calculate the interpolated value. cde would be far better off as lerp than MNO.

**Comment by iamgreaser** [comment]
~~`lerp` would make no more sense for cde as it would for MNO. They are both "previous keyframes".~~

EDIT: Redacted.

**Comment by asiekierka** [comment]
https://github.com/FabricMC/pomf/commit/474177781c180b1fd8b542c55c60056441e5d7a9
