### ISSUE TITLE
BoundingBox minX, minY, minZ ect -> x0, y0, z0, x1, y1, z1

### ISSUE THREAD

**Issue by Blayyke** [asiekierka/MinecraftPOMF#786]
MutableIntBoundingBox's `toString` override uses the names `x0`, `y0`, `z0` ect in the string.

**Comment by Runemoro** [comment]
Other Mojang toString methods use min and max. For consistency, we should use these everywhere.

**Comment by Blayyke** [comment]
I think these names are bad, but since we like using mojang names I brought this up. Could be an outdated toString though.

**Comment by haykam821** [comment]
The current names should be kept as the coordinates are guaranteed to be the lowest or highest of the two provided.
```java
this.minX = Math.min(x1, x2);
this.minY = Math.min(y1, y2);
this.minZ = Math.min(z1, z2);
this.maxX = Math.max(x1, x2);
this.maxY = Math.max(y1, y2);
this.maxZ = Math.max(z1, z2);
```

**Comment by YanisBft** [comment]
Closing this as current names are correct and consistent
