### ISSUE TITLE
MobEntity#isInDaylight is misleading

### ISSUE THREAD

**Issue by Pyrofab** [asiekierka/MinecraftPOMF#804]
While it does check that the mob is exposed to the sun, it has a (high) random chance of returning false. Currently, the method is specifically used by undead mobs to start burning / damage their helmet, which should probably be emphasized.

**Comment by natanfudge** [comment]
`shouldBurnDueToDaylight`

**Comment by juliand665** [comment]
`whetherOrNotIShouldCatchFireDueToDaylightInThisSpecificTickOfAllPossibleOnes`

jokes aside, i'd prefer "catch fire" over "burn" in this context, even if it's longer, so `shouldCatchFireDueToDaylight `
