### ISSUE TITLE
Access issues

### ISSUE THREAD

**Issue by modmuss50** [asiekierka/MinecraftPOMF#808]
`net.minecraft.world.chunk.light.ChunkLightProvider.hasUpdates()` accesses `net.minecraft.util.LevelPropagator.hasLevelUpdates()` witch is protected.

there is possibly some more access isssues that need fixing as well. Someone has a tool to check for these, where is it lol? Might not be a bad idea to fail the travis CI build if this is an issue.

**Comment by liach** [comment]
i think the command line checker from jamieswhiteshirt in enigma should suffice

**Comment by Runemoro** [comment]
I don't see what the problem is... `ChunkLightProvider` extends `LevelPropagator`.

**Comment by modmuss50** [comment]
Yes it does, but its not calling its super method, its calling the method from an instance of LevelPropagator (ChunkLightProvider.lightStorage)

![](https://ss.modmuss50.me/idea64_2019-08-04_21-12-01.png)

**Comment by JamiesWhiteShirt** [comment]
The tool to check for them is Enigma's checkMappings command. I know the access checker I wrote isn't entirely correct in that it can cause false positives. I have not looked into this particular instance, just letting you know.

**Comment by modmuss50** [comment]
Someone (not me) found this issue when running the game without the access transform fixes that fabric-loader applys.

I havent validated it my self in a running application, but idea is showing it up.
