### ISSUE TITLE
Value names of BlockRotation enum are not entirely accurate to what they are used for

### ISSUE THREAD

**Issue by RedstoneParadox** [asiekierka/MinecraftPOMF#809]
So the values imply that they're in increments of 90 or 180 degrees but they don't often seem to be used for that. I would suggest dropping the `90` from `CLOCKWISE_90` and `COUNTERCLOCKWISE_90` since they are used for that in general. I don't know what `CLOCKWISE_180` could be renamed to; maybe `REFLECT` or something?

**Comment by kgscialdone** [comment]
Perhaps `INVERT`?

**Comment by Sollace** [comment]
`MIRROR`?

**Comment by RedstoneParadox** [comment]
It seems as though I misspoke; They do only seem to be used for increments of 90 degrees, though I may have missed a few edge cases.

**Comment by liach** [comment]
Unfortunately, this issue is invalid because these field names are auto-generated from bytecode clues (enum names in ldc)
