### ISSUE TITLE
net.minecraft.client.model.Cuboid -> ModelPart

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#810]
It's not a cuboid, it can be composed of several boxes and has rotation point information. Then, `net.minecraft.client.model.Box` (which actually *is* a cuboid shape) should be renamed to `Cuboid` to avoid conflicting with `net.minecraft.util.math.Box`.

**Comment by Prospector** [comment]
Would even just Part be too generic? Seems a bit strange to have a model prefix when nothing else really does

**Comment by Sollace** [comment]
I wouldn't change `Box`. Box is the perfect name for it.

`ModelPart` is okay, though I'd suggest the variations`ModelSubPart`, `SubPart`.

Other names like `BoxSet`, `BoxList`, `RotatedBoxSet` and `RotatedBoxList` all fit as well.

**Comment by Pyrofab** [comment]
The model Box name is not great, because it conflicts with the utility box. And it never contains anything, so I think `Cuboid` is more appropriate.
