### ISSUE TITLE
AnimalEntity::method_20663, MobEntity::method_20636 -> canSpawnAt?

### ISSUE THREAD

**Issue by coderbot16** [asiekierka/MinecraftPOMF#830]
The MobEntity implementation calls BlockState::allowsSpawning or returns true if the spawn type is SpawnType.SPAWNER, whereas the AnimalEntity implementation checks for a light level of 9 or above and checks if the below block is a grass block.

**Comment by ghost** [comment]
Partially implemented in Shnupbups's most recent yarn pr (https://github.com/FabricMC/yarn/pull/854) they've mapped `AnimalEntity::method_20663` as `isValidNaturalSpawn`
