### ISSUE TITLE
Bee class issues.

### ISSUE THREAD

**Issue by ghost** [asiekierka/MinecraftPOMF#832]
The additions of bees to 19w34a has left some classes with now inaccurate names. Im unsure as to what they should now be named so I'm using this to document their function and as for a place for discussion.

Firstly, `class_1432` which is currently named `Bird` but now also used by BeeEntity and last I checked bees are not birds. Only used in `LivingEntity` to update Bees and Parrots `limbDistance` and `limbAngle` (Their limb refers to their wings in this case) It should be noted that Ghasts and more so Bats don't use this interface despite having similar features.
For code see near towards the bottom of LivingEntity's travel method (or search for Bird)

Secondly, `class_1331` which is currently named `ParrotMoveControl` but now also used by Bee.
This class's tick method has code similar to the base implementation in `MoveControl` however gives entities and upward motion aswell as no gravity when flying towards a target. When not moving towards a target bee specifically (through a boolean argument in the class constructor) have gravity reapplied to them.

**Comment by ghost** [comment]
Also had some discussion on discord [here](https://discordapp.com/channels/507304429255393322/608088354042544139/614592911555952681).

**Comment by Sollace** [comment]
One suggestion:

`ParrotMoveControl` -> `FlightMoveControl`

I'm not sure about `Bird`. My previous suggestion was something like `FlyingEntity` but I see it's really just an empty interface applied to birds and bees. Can anyone find some over cases where this interface is being used? Likely it's name isn't `Bird` but more closely to some trait Mojang wanted to differentiate parrots from other entities.

**Comment by Prospector** [comment]
I'd go with "Flutters" for the interface

**Comment by Pyrofab** [comment]
Flutters is a bit of a weird name for an interface in my opinion. Maybe `Fluttering` may be better ?

**Comment by Sollace** [comment]
`CanFlutter`

This is why I prefer the I prefix for interfaces, because then the name can
be `ICanFlutter`

**Comment by ghost** [comment]
In Bedrock `ParrotMoveControl` seems to be named `FlyMoveControl` but I like Sollace's suggestion of `FlightMoveControl`. Also `Flutters` seem like an appropiate name for the interface

**Comment by YanisBft** [comment]
I'm okay with `FlightMoveControl` and `FlyingEntity`, but I think `WingMoveControl` / `WingedEntity` would be more accurate, as ghasts are flying but don't have wings

**Comment by Sollace** [comment]
@Yanis48  I only suggested FlyingEntity before because I'd mistakenly assumed `Bird` was a class extending `Entity`. Using `Winged` is a good idea, though. I knew there was a term like that but just couldn't think of it at the time.

**Comment by ryantheleach** [comment]
Ghasts appear to hover. Parrots / Bees Flutter. Elytra / Dragon / phantom Soar, chickens soft-fall / glide.

(hover as in the word to describe helicopter/drone-like flight)

**Comment by Sollace** [comment]
@ryantheleach What do Chickens do?

**Comment by Sollace** [comment]
Also I'd say Ghasts rather _drift_ more than they hover.

**Comment by ghost** [comment]
Going to be making a PR with `FlightMoveControl` and `Flutters` If anyone can find a better name for `Flutters` please make a comment on the PR (will prob be up in a few minutes or so)

**Comment by Sollace** [comment]
> Flutters

And thus begins the slow and gradual onset of ponies...

**Comment by ghost** [comment]
PR seems to be approved (not merged yet), so I'll be closing this issue.

**Comment by modmuss50** [comment]
I approved it, and forgot to merge it :D sorry
