### ISSUE TITLE
Legal concerns

### ISSUE THREAD

**Issue by AfterRebelion** [asiekierka/MinecraftPOMF#850]
As stated in the bottom of https://www.minecraft.net/en-us/ , Minecraft is a trademarked word, so [any file in this repository that contains that word is in violation with that](https://github.com/FabricMC/yarn/search?q=minecraft&unscoped_q=minecraft).

Have a good day.

**Comment by Pannoniae** [comment]
Assuming this, anyone saying the word "Minecraft" is in legal problem.

**Comment by AfterRebelion** [comment]
Not exactly, [Microsoft guidelanes ](https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/general.aspx) state that you may use their trademarked names to reference their products, but in the same manner it says "you may not: use the trademarks more prominently than your product or service name"
As stated, Minecraft is used 3231 times in the proyect. [Yarn is used 3](https://github.com/FabricMC/yarn/search?q=yarn&unscoped_q=yarn)

**Comment by Archengius** [comment]
average mod has minecraft used 1000x times more than it's own name

**Comment by shedaniel** [comment]
partition to rename net.minecraft to net.cavegame

**Comment by Pannoniae** [comment]
Prominency does not mean "number of times" I think. I might be wrong, but it concerns about you plastering "MINECRAFT" all over your creation, pretending it's official, and barely including the "real" name of your work.

**Comment by modmuss50** [comment]
If Micosoft want to DMCA all [51,770](https://github.com/search?q=minecraft) repos that the name minecraft it in, then so be it yarn will be no more.

Untill that happens im not worried.
