### ISSUE TITLE
net.minecraft.client.render.Vec3d -> MutableVec3d

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#851]
In `net.minecraft.util.math` there is another `Vec3d` which has 3 public final double fields. This more popular vec3d is actually used in `net.minecraft.client.render` package as well, like in Camera; this one that needs a rename has 3 public (mutable) double fields, and is only used by the world renderer. Well `MutableVec3d` sounds good enough to me.

**Comment by liach** [comment]
The mojang vec3d is just a bit crazy, I need to sort them out 🤔

**Comment by apple502j** [comment]
Removed in 22w43a.
