### ISSUE TITLE
Block.isSolidMediumSquare -> hasTopRim or similar

### ISSUE THREAD

**Issue by tryashtar** [asiekierka/MinecraftPOMF#852]
`isSolidMediumSquare` is similarly named to `isSolidSmallSquare`, but this is a bit misleading.

`isSolidSmallSquare` is true for the top of a fence, for example. `isSolidMediumSquare` makes me think of a comparable larger centered square, but that's not the case, considering it's false for anvils but true for hoppers, cauldrons, and composters.

Also, `isSolidMediumSquare` doesn't take a direction, it only checks the top face of the block. Rails and redstone gates use it to determine valid placement.

Considering these facts, it seems as though the intent of this function is to check for an outer rim on the top face of a block. Indeed, `SOLID_MEDIUM_SQUARE_SHAPE` is created by taking a block shape and subtracting the inner portion.

**Comment by YanisBft** [comment]
Fixed in #848 by naming it `topCoversMediumSquare`

**Comment by tryashtar** [comment]
That's still a pretty poor name

**Comment by YanisBft** [comment]
Okay, I'll rename it `hasTopRim` then

**Comment by tryashtar** [comment]
Oh, thank you!
