### ISSUE TITLE
Vec3d.ORIGIN should be called ZERO

### ISSUE THREAD

**Issue by iamgreaser** [asiekierka/MinecraftPOMF#87]
While it's the origin in some contexts, in others it does not make sense. For instance, it's used as a fallback when attempting to normalise a vector that is very close to zero.

On the other hand, even when it's the origin, it still makes sense to call it the zero vector.

I'm working on a PR to map Vec3d and possibly some other things but renaming ORIGIN will have a lot of side effects which I do not want happening in the PR, hence this issue.

**Comment by asiekierka** [comment]
Sure.

**Comment by copygirl** [comment]
Closing issue since it's now part of #88?

**Comment by iamgreaser** [comment]
Yeap.
