### ISSUE TITLE
Block tick method names

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#872]
Here is a vote on block's tick methods' names on whether to have an `on` prefix.

`onScheduledTick()`, `onRandomDisplayTick()`, `onRandomTick()` :+1:
`scheduledTick()`, `randomDisplayTick()`, `randomTick()` :-1:

The `on` prefix exists for most methods, but `randomDisplayTick` exists previously as well in `Block` mappings. See #871.

<details>
<summary>
My personal opinion
</summary>

I personally support no `on` prefix, which is the :-1: option. When we sum up, count extra 1 to the :-1:
</details>

**Comment by i509VCB** [comment]
Since it isn't an event for say and closer to an actual implementation the `on` prefix doesn't make as much sense.

Also what does randomDisplayTick specifically do? Is it similar to the sand particles from floating sand or lava dripping?

**Comment by liach** [comment]
Random display tick is like lava dripping particles or lit redstone particles if I recall correctly

**Comment by Juuxel** [comment]
Yep, it's the client-sided block tick used for rendering block effects.

**Comment by natanfudge** [comment]
Can we get `activate` changed to `onActivate`?

**Comment by Juuxel** [comment]
I'd say `use`/`onUse` would be better to match the item method and the keybinding name.

**Comment by ghost** [comment]
I would also prefer `use` over `activate`

**Comment by natanfudge** [comment]
Either way it needs to be prefixed with `on` to match all of the other block events.

**Comment by liach** [comment]
In the gui code, mojang has `keyPressed` `mouseMoved` instead of `onKeyPressed` `onMouseMoved` etc.

**Comment by liach** [comment]
Up to now, people support no `on` prefix dominantly and #871 has changed to use no `on` prefix as well.

**Comment by liach** [comment]
sure, my mistake. sorry juuz!
