### ISSUE TITLE
TextRenderer -> Font

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#876]
(I think this was already known, but there wasn't any issue for this)

Screen's unobfuscated `TextRenderer` field is called `font`.

**Comment by liach** [comment]
Maybe mojang just call it `FontRenderer` instead, which they shorten it to `font`.

**Comment by Prospector** [comment]
A font renderer doesn't make much sense imo. You render text with a font. So it should either be TextRenderer or Font

**Comment by liach** [comment]
We already have a `net.minecraft.client.font.Font` interface, which offers glyphs for different characters.

**Comment by Juuxel** [comment]
That sounds like a better use for the name `Font`. Closing this.
