### ISSUE TITLE
net.minecraft.client.network.ClientDummyContainerProvider -> 

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#889]
class_747 is a simple text name-container combination.
It is not only used on the client; it is used by the trader interface on the client, but it is also used by a few other blocks (enchantment table, etc. that has a container but no block entity)

Maybe SimpleNamedContainerProvider?

**Comment by liach** [comment]
On a side note, this was originally mapped in 2351d30ec99350fbebcff0dd30dbad64fd022f81

**Comment by Juuxel** [comment]
I named it `n.m.menu.NamedMenuProviderWrapper` in the menu PR (would be `n.m.container.NamedContainerProviderWrapper` with current names).

**Comment by liach** [comment]
Should we name it `NamedContainerProviderImpl` or `SimpleNamedContainerProvider` as this is just a simple implementation

**Comment by Juuxel** [comment]
I think `SimpleNamedContainerProvider` sounds good. I'll also change #846 to use something similar.
