### ISSUE TITLE
PortalBlock -> NetherPortalBlock

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#895]
It's only used by `minecraft:nether_portal` and it's hardcoded to the nether.

**Comment by Juuxel** [comment]
Looks like there's also some fields and methods in Entity that reference "portals" when they specifically check for nether portals or move between the nether and the overworld.

**Comment by YanisBft** [comment]
@Juuxel not sure about renaming fields and methods referencing portals, as the nbt for portals never contains "nether"

**Comment by YanisBft** [comment]
can be closed
