### ISSUE TITLE
Registry.STRUCTURE_PIECE -> Registry.STRUCTURE_PIECE_TYPE

### ISSUE THREAD

**Issue by Draylar** [asiekierka/MinecraftPOMF#916]
`Registry.STRUCTURE_PIECE` wants a `StructurePieceType`, which is a factory for creating `StructurePiece`s. The name should be changed to `STRUCTURE_PIECE_TYPE` to reflect this (as is the case with the `BlockEntityType`/`EntityType` registries).

**Comment by JamiesWhiteShirt** [comment]
What is the name of the registry in the registry of registries? Probably `structure_piece`, in which case the name should remain.

**Comment by Draylar** [comment]
Is that because changing to `STRUCTURE_PIECE_TYPE` would require changing `structure_piece` to `structure_piece_type`, which would mess things up?
edit: and yes, it is `structure_piece` in the registry

**Comment by liach** [comment]
I don't think the names in registry are auto. So yes, we can do this change. Will mark this for a vote.

**Comment by LemmaEOF** [comment]
Well, `structure_piece` in the registry registry are hardcoded strings from mojang, iirc. I say we keep to `Registry.STRUCTURE_PIECE` since that's the standard for anything registered.

**Comment by liach** [comment]
fyi we already named the thing in the registry structure piece type.

**Comment by valoeghese** [comment]
The result of this vote seems conclusive
