### ISSUE TITLE
StructurePoolBasedGenerator mappings

### ISSUE THREAD

**Issue by Draylar** [asiekierka/MinecraftPOMF#919]
I still need to get familiar with yarn (and submitting mappings) before submitting these. If anyone wants to PR them, that'd be great, otherwise, I can do it in a few days. 

`StructurePoolBasedGenerator.class_4182` -> `StructureGenerator`
`StructurePoolBasedGenerator.class_4182.field_18700` -> `maxSize`[1]
`StructurePoolBasedGenerator.class_4182.field_18701` -> `pieceFactory`
`StructurePoolBasedGenerator.class_4182.field_18702` -> `chunkGenerator`
`StructurePoolBasedGenerator.class_4182.field_18703` -> `structureManager`
`StructurePoolBasedGenerator.class_4182.field_18704` -> `children`
`StructurePoolBasedGenerator.class_4182.field_18705` -> `random`
`StructurePoolBasedGenerator.class_4181.method_19306` -> `generatePiece`

The non-obvious arguments for the constructor of `class_4182` are `starting pool Identifier`, `max structure size`, and `children`[2] (for the list at the end). 

Args for `method_19306` are `piece`, `pieceBounds`, `minY`, and `currentSize`.

1* This is mapped as `size` in the village feature config, but in this context, `maxSize` seems more appropriate.

2* Note that the children list passed in is not one *used* by the generator, but rather one that the generator adds to in order to notify the class that calls the generator. In other words, it comes in empty (if that makes sense).

`class_4182` is the logic behind `StructurePoolBasedGenerator`. I'm not sure why they have it inside a subclass... from my brief overview, it seems to take a starting pool, generate a piece from it, and then generate all other needed pieces based on jigsaws inside each new piece, until the max size is hit, or no more jigsaws exist. I'd say `StructureGenerator` is appropriate, or something to that effect. 

`StructurePoolBasedGenerator.class_4181` -> `PieceWithBoundingBox`/`BoundedPiece`
`StructurePoolBasedGenerator.class_4181.field_18696` -> `piece`
`StructurePoolBasedGenerator.class_4181.field_18696` -> `pieceBounds`
`StructurePoolBasedGenerator.class_4181.field_18698` -> `minY`
`StructurePoolBasedGenerator.class_4181.field_18699` -> `currentSize`

`class_4181` is a structure piece with context on the overall structure size and its own bounding box. It seems to be used as a wrapper for holding information on all pieces being used in the structure's generation while also attaching them to the area (bounding box) they take up.

edit: on further look, `pieceBounds` might be better as `pieceShape`. This is because a variable that deserves the name `pieceShape` _more_ appears later on in the method.

Once I've finished tidying up the class, I'll post a link here.

**Comment by liach** [comment]
Since the pr is merged, I will close this.
