### ISSUE TITLE
"impl/" packages and when to use them?

### ISSUE THREAD

**Issue by copygirl** [asiekierka/MinecraftPOMF#93]
The usage of `impl` packages is still a bit unclear to me. I would honestly prefer not to use them unless there's a good reason.

For example: `net.minecraft.migration`, `net.minecraft.container`, `net.minecraft.client.audio` are good like they are. There's plenty of classes in the base package and lots of implementations.

On the other hand, `net.minecraft.world.chunk.generator` (currently) consists of `IChunkGenerator` and the `impl` subpackage has only 5 implementations and is pointless in this case.

**Comment by asiekierka** [comment]
Also note that net.minecraft.block.impl will break Minecraft, as all vanilla Block initializers seem to be protected.

**Comment by asiekierka** [comment]
Honestly, I'd say get rid of impl.

**Comment by copygirl** [comment]
I don't know... keeping `block` and `block.impl` separate seems like a good idea to me.

**Comment by asiekierka** [comment]
@copygirl That means nobody can use POMF without patching the game. Not a very good idea.

**Comment by copygirl** [comment]
Welp. It's decided! I'll take care of it a little later if you don't mind.

**Comment by asiekierka** [comment]
Sure

**Comment by darkevilmac** [comment]
Shame, I liked the whole impl thing. Will it be kept for other classes besides block, or will it be killed off entirely so things match up with each other a bit more.

**Comment by copygirl** [comment]
@darkevilmac I think we should keep it consistent then.

Are there any other cases of protected constructors we need to watch out for?
Is this something Enigma should be aware of?

**Comment by copygirl** [comment]
With the upcoming ability to change access modifiers so we're not restricted by silly Java access rules regarding `protected` we can (and probably should) split certain implementations into separate packages again. Do we bring them back as `impl` and what should be the general guidelines?

I'm personally for "if there's too many classes in one place and it makes sense, use an `impl` package", though I'd like to avoid `something/impl/foo` if it could just be `something/foo`.

**Comment by asiekierka** [comment]
We decided not to change access modifiers by default after all, not to mention that the new naming scheme makes it a bit less annoying to discern between a part of the abstract system and an implementation.
