### ISSUE TITLE
readFrom -> loadFrom

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#931]
We currently have 7 methods named `readFrom`, and 12 usages of `loadFrom`. We should pick one. I think `loadFrom` is better since it's *loading* data from a tag into the current object (not just reading the data and creating a new object, for example).

**Comment by liach** [comment]
load is indeed better. Let's use :+1: for load and :-1: for read (on the issue thread)

**Comment by natanfudge** [comment]
Also `readTag` -> `loadTag`?

**Comment by liach** [comment]
loadTag if the return type is tag. readTag if the param type is tag.

**Comment by natanfudge** [comment]
I would say the opposite.
