### ISSUE TITLE
VanillaLayeredBiomeSource -> OverworldLayeredBiomeSource

### ISSUE THREAD

**Issue by jaskarth** [asiekierka/MinecraftPOMF#944]
We can assume that it's vanilla because, well, it's in the Minecraft source. I think that `OverworldLayeredBiomeSource` flows better (Suggested by Valoeghese). I'd also suggest renaming `BiomeSourceType.VANILLA_LAYERED` to `BiomeSourceType.OVERWORLD_LAYERED` if we go through with this.

**Comment by Runemoro** [comment]
The registry ID is `vanilla_layered`.

**Comment by jaskarth** [comment]
Well I guess I missed that, thanks for pointing that out
