### ISSUE TITLE
Move util.ChunkPosDistanceLevelPropagator to world package

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#947]
Now, we have LevelPropagator and SectionDistanceLevelPropagator in net/minecraft/world/chunk and net/minecraft/util packages. We should look into grouping them into more similar packages. Since @runemoro named them, I will leave this to him.

**Comment by Runemoro** [comment]
It would be nice if everything could be in `net.minecraft.util` since they're used for things like points of interest and chunk loading, but Mojang is using a package-private method from `LevelPropagator` in `net.minecraft.world.chunk`!

**Comment by liach** [comment]
Now `SectionDistanceLevelPropagator` is moved to `world` package but `ChunkPosDistanceLevelPropagator` is still in `util`.

**Comment by liach** [comment]
Can be fixed by #1235
