### ISSUE TITLE
ClientConnection -> ?

### ISSUE THREAD

**Issue by liach** [asiekierka/MinecraftPOMF#953]
Appears that this class is likely called a packet handler from the available strings.
```java
ClientConnection clientConnection_1 = new ClientConnection(NetworkSide.SERVERBOUND);
ServerNetworkIo.this.connections.add(clientConnection_1);
channel_1.pipeline().addLast("packet_handler", clientConnection_1);
```
```java
protected void initChannel(Channel channel_1) throws Exception {
    channel_1.pipeline().addLast("packet_handler", clientConnection_1);
}
```
So `PacketHandler`? Might it be confusing with the actual packet listeners?

**Comment by liach** [comment]
Player has explained that this is a connection to another side, makes sense.

**Comment by Runemoro** [comment]
I completely disagree with @sfPlayer1. `ClientConnection` makes me think it's a connection to a client, while it's actually a connection to the server!

**Comment by liach** [comment]
not really. both s2c and c2s use this

**Comment by Runemoro** [comment]
Then why "client" connection if this is used for both client -> server and server -> client? It should just be `Connection`

**Comment by liach** [comment]
Since there is some debate and questions on discord, I am reopening this. Maybe just `Connection`?

**Comment by Runemoro** [comment]
For me `Connection` (or `MinecraftConnection` if you find `Connection` too ambiguous) is perfect.

**Comment by Pyrofab** [comment]
`MinecraftConnection`/`McConnection` could be a nice way to solve ambiguous imports

**Comment by Runemoro** [comment]
Not `McConnection`. We have `MinecraftClient`, `MinecraftServer`, not `McClient`, `McServer`.

**Comment by Player3324** [comment]
For me either of these works: ClientConnection, Connection, MinecraftConnection - i guess the last one has the best chances..

**Comment by liach** [comment]
`ClientConnection` has a point: it shows that the connection is to one remote socket. I wish we can find a better term for `client`, maybe `SocketConnection`?

**Comment by liach** [comment]
Or maybe `ChannelConnection` as it binds to a netty channel and handles stuff before the channel is available (queued packets)? And it also reads packets from the channel.

**Comment by liach** [comment]
In https://github.com/FabricMC/yarn/pull/2179/files#diff-e1b89a50c21d02f1a0eb5bebfda00974ac9009926793000aede48977eadf8c79R2 I added a piece of javadoc describing what it is. Maybe this should suffice given the large migration cost for a rename. Feel free to comment if you feel this is still relevant.
