### ISSUE TITLE
client.util.Texts -> ?

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#963]
There's also a `Texts` in `net.minecraft.text`. The client one has methods related to modifying texts for rendering purposes (wrapping lines and removing colors based on game options). The common one has methods for working with texts in general.

**Comment by liach** [comment]
`TextRendering`

**Comment by liach** [comment]
In #1297, I've renamed `class_341` from `Texts` to `ChatMessages`, as this is exclusively used by the chad hud logic.
