### ISSUE TITLE
Entity position setters

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#964]
There are multiple methods for setting entity positions, and they need a bit of improving.

- Confusingly, there are both `Entity.setPos()` and `Entity.setPosition()`.
  - `setPos` is the "basic" position setter - it just sets the fields.
  - `setPosition` calls `setPos` and also updates the entity's bounding box.
- There's `setPositionAndAngles` (two overloads, the BlockPos one calls the double one) that calls `method_22862` with the XYZ, sets the yaw and pitch, and calls `method_23311`.
  - `method_22862` calls `setPos`, and sets `prev(Render)X/Y/Z` to the passed XYZ.
  - `method_23311` calls `setPosition` with the entity's current coordinates. I'd assume it's for updating the bounding box.
- There's also `setPositionAnglesAndUpdate`, which calls `setPosition` but also sets the angles and `prevX/Y/Z/Yaw/Pitch`.

**Comment by Pyrofab** [comment]
I would suggest :
- `setPos` -> `setPosition`; `setPosition` -> `updatePosition`
- `method_22862` -> reposition
- `method_23311` -> `refreshPosition`

**Comment by liach** [comment]
Note that the current `setPosition` one also resets the bounding box of the entity.
