### ISSUE TITLE
Lead/Leash class naming inconsistency?

### ISSUE THREAD

**Issue by IbraheemR** [asiekierka/MinecraftPOMF#971]
`LeadKnotEntity` is named differently to `LeashEntityModel` and `LeashKnotEntityRenderer`.

#246 sees `LeashKnotEntity` renamed to `LeadKnotEntity`. I assume the others should follow suit.

**Comment by IbraheemR** [comment]
It seems many methods through out yarn use the word leash (mostly in `MobEntity` - `MobEntity#attachLeash`, `MobEntity#detachLeash`, `MobEntity#leashTag` etc)

**Comment by liach** [comment]
Lead is the item, leash (knot) is the entity (in vanilla).
