### ISSUE TITLE
Vector3f is in client.util.math

### ISSUE THREAD

**Issue by Juuxel** [asiekierka/MinecraftPOMF#978]
It's not client-only (as of 1.15-pre1).

**Comment by liach** [comment]
Hmm, these `Vector` stuff etc. are featured by their mutable fields and overwhelmingly client usage compared to their util.math counterparts. Interesting thing to look into.

**Comment by Runemoro** [comment]
The `Vec` and `Vector` naming is also very weird. It doesn't make sense to name two classes the same but with one name abbreviated. What's the important difference between `Vector3d` and `Vec3d` (why doesn't Mojang use a single class?).

**Comment by liach** [comment]
we have `Vec` for immutable types and `Vector` for mutable types.

**Comment by Runemoro** [comment]
Then I think `Vector` Should be `MutableVec`.

**Comment by liach** [comment]
@Yanis48 Actually I am not very sure on handling this yet; should we rename this to `Vector3f` to distinguish from the immutable vec3d in minecraft util math package and move to minecraft util math, or?

**Comment by YanisBft** [comment]
I think we should rename it to `Vec3f`, and move it to nm.util.math
