### ISSUE TITLE
ColoredBlock named wrong

### ISSUE THREAD

**Issue by Runemoro** [asiekierka/MinecraftPOMF#997]
It's implemented by the beacon, stained glass, but not wool or terracotta. It's used to dye the beacon beam.

`TransparentColoredBlock`?

**Comment by liach** [comment]
merging #867 into this one.

**Comment by Sollace** [comment]
What is wrong with calling it `ColoredBlock`?

(typing the murkanization like that hurts my brain)

**Comment by Runemoro** [comment]
> What is wrong with calling it ColoredBlock?

Without having read this issue, what would you have thought this code does when the player walks on some colored wool?

```java
if (blockUnderPlayer instanceof ColoredBlock) {
    player.sendMessage("You're standing on a " + ((ColoredBlock) blockUnderPlayer).getColor() + " block");
}
```

Also, I wasted time implementing this in a mod I'm porting to 1.15, not knowing that I wasn't even supposed to implement it for non-transparent blocks.

**Comment by liach** [comment]
StainedBlock?

**Comment by Sollace** [comment]
> 
> 
> > What is wrong with calling it ColoredBlock?
> 
> Without having read this issue, what would you have thought this code does when the player walks on some colored wool?
> 
> ```java
> if (blockUnderPlayer instanceof ColoredBlock) {
>     player.sendMessage("You're standing on a " + ((ColoredBlock) blockUnderPlayer).getColor() + " block");
> }
> ```
> 
> Also, I wasted time implementing this in a mod I'm porting to 1.15, not knowing that I wasn't even supposed to implement it for non-transparent blocks.

I'd imagine it would print "You're standing on a green block".

Was this added when mojang put in all the coloured glass, clays, and terracottas? Seems like a general-use tinted block to me.

**Comment by Runemoro** [comment]
> I'd imagine it would print "You're standing on a green block".

Except it doesn't, which is exactly the problem! Wool and other non-transparent colored blocks don't implement this class. Only the stained glass blocks do (used by the beacon to get new beam color).

**Comment by liach** [comment]
BeaconBeamStainable?

**Comment by Runemoro** [comment]
> BeaconBeamStainable

That makes it seem like the beacon beam stains it. Also, it could be used by mods to color their own light beam effects. I think the map renderer is also using this to adjust the color of thr blocks under it.

Is anything wrong with ColoredTransparentBlock? Another option could be ColorFilter.

**Comment by YanisBft** [comment]
can be closed
